var art_PRLAN = {
  "name": "prints collection",
  "edition": "1",
  "date": "29 Sep 2018",
  "objects": {
    "pr1": {
      "briefly": "Engraving after Edward Landseer - Scene from 'A Midsummer Night's Dream', 1857.",
      "image": "prints/pr1.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Scene from 'A Midsummer Night's Dream', 1857.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Scene from 'A Midsummer Night's Dream', 1857.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by artist",
      "Description.Measurement": " (height: 24&quot;, width: 36&quot;)"
    },
    "pr2": {
      "briefly": "Engraving after Edward Landseer - 'The Font', 1875.",
      "image": "prints/pr2.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - 'The Font', 1875.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "'The Font', 1875.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver (Thomas Landseer)",
      "Description.Measurement": " (height: 32&quot;, width: 24&quot;)"
    },
    "pr3": {
      "briefly": "Engraving after Edward Landseer - Windsor Forest, 1868.",
      "image": "prints/pr3.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Windsor Forest, 1868.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Windsor Forest, 1868.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, T. L. Atkinson",
      "Description.Measurement": " (height: 29&quot;, width: 23&quot;)"
    },
    "pr4": {
      "briefly": "Engraving after Edward Landseer - 'Dash, Hector, Nero and Lory'.",
      "image": "prints/pr4.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - 'Dash, Hector, Nero and Lory'.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "'Dash, Hector, Nero and Lory'.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver F. Bacon",
      "Description.Measurement": " (height: 22&quot;, width: 28&quot;)"
    },
    "pr5": {
      "briefly": "Engraving after Edward Landseer - The Otter Hunt.",
      "image": "prints/pr5.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - The Otter Hunt.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "The Otter Hunt.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver C. G. Lewis",
      "Description.Measurement": " (height: 31&quot;, width: 24&quot;)"
    },
    "pr6": {
      "briefly": "Engraving after Edward Landseer - The Pets, 1836.",
      "image": "prints/pr6.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - The Pets, 1836.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Pets, Lady Rachel Russell",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver W. H. Watt",
      "Description.Measurement": " (height: 13&quot;, width: 11&quot;)"
    },
    "pr7": {
      "briefly": "Engraving after Edward Landseer - Horses at the Fountain.",
      "image": "prints/pr7.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Horses at the Fountain.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Horses at the Fountain.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver J. H. Watt",
      "Description.Measurement": " (height: 19&quot;, width: 25&quot;)"
    },
    "pr8": {
      "briefly": "Engraving after Edward Landseer - Highland Lassie crossing the stream.",
      "image": "prints/pr8.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Highland Lassie crossing the stream.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Highland Lassie crossing the stream.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, John Outram",
      "Description.Measurement": " (height: 23&quot;, width: 17&quot;)"
    },
    "pr10": {
      "briefly": "Engraving after Edward Landseer - Mrs. Pack's pony, 1841.",
      "image": "prints/pr10.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Mrs. Pack's pony, 1841.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Mrs. Pack's pony and spaniels",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, T. Landseer",
      "Description.Measurement": " (height: 20&quot;, width: 25&quot;)"
    },
    "pr11": {
      "briefly": "Engraving after Edward Landseer - Prince George's Favourites, 1841.",
      "image": "prints/pr11.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Prince George's Favourites, 1841.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Prince George's Favourites, 1841.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Signed by artist. Engraver W. Gillet.",
      "Description.Measurement": " (height: 20&quot;, width: 25&quot;)"
    },
    "pr12": {
      "briefly": "Engraving after Edward Landseer - Maid and Magpie, 1862.",
      "image": "prints/pr12.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Maid and Magpie, 1862.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Maid and Magpie, 1862.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Signed by artist and engraver, S. Cousins.",
      "Description.Measurement": " (height: 28&quot;, width: 24&quot;)"
    },
    "pr14": {
      "briefly": "Engraving after Edward Landseer - The Challenge.",
      "image": "prints/pr14.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - The Challenge.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "The Challenge.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Unsigned (etched by Henry Walker, engraver John Burnet F.R.A.)",
      "Description.Measurement": " (height: 16&quot;, width: 36&quot;)"
    },
    "pr15": {
      "briefly": "Engraving after Edward Landseer - Cover Hack.",
      "image": "prints/pr15.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Cover Hack.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Cover Hack.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver C. G. Lewis",
      "Description.Measurement": " (height: 25&quot;, width: 31&quot;)"
    },
    "pr16": {
      "briefly": "Engraving after Edward Landseer - Hawking in olden times.",
      "image": "prints/pr16.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Hawking in olden times.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Hawking in olden times.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver C. G. Lewis",
      "Description.Measurement": " (height: 23&quot;, width: 27&quot;)"
    },
    "pr17": {
      "briefly": "Engraving after Edward Landseer - Waiting for the deer to rise.",
      "image": "prints/pr17.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Waiting for the deer to rise.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Waiting for the deer to rise.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, H. T. Ryall",
      "Description.Measurement": " (height: 22&quot;, width: 28&quot;)"
    },
    "pr18": {
      "briefly": "Engraving after Edward Landseer - (Children and animals).",
      "image": "prints/pr18.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - (Children and animals).",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Sutherland Children (?) (Children and animals).",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, S. Cousins",
      "Description.Measurement": " (height: 22&quot;, width: 18&quot;)"
    },
    "pr19": {
      "briefly": "Engraving after Edward Landseer - Saved - 1859.",
      "image": "prints/pr19.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Saved - 1859.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Saved - 1859.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, S. Cousins",
      "Description.Measurement": " (height: 21&quot;, width: 31&quot;)"
    },
    "pr20": {
      "briefly": "Engraving after Edward Landseer - Dignity and Impudence, 1841.",
      "image": "prints/pr20.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Dignity and Impudence, 1841.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Dignity and Impudence, 1841.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, T. Landseer",
      "Description.Measurement": " (height: 30&quot;, width: 24&quot;)"
    },
    "pr21": {
      "briefly": "Engraving after Edward Landseer - Highland Breakfast, 1876.",
      "image": "prints/pr21.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Highland Breakfast, 1876.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Highland Breakfast, 1876.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, J. C. Webb (?)",
      "Description.Measurement": " (height: 13&quot;, width: 17&quot;)"
    },
    "pr22": {
      "briefly": "Engraving after Edward Landseer - Islay, Macaw and Love Birds.",
      "image": "prints/pr22.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Islay, Macaw and Love Birds.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Islay, Macaw and Love Birds.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver C. G. Lewis",
      "Description.Measurement": " (height: 37&quot;, width: 19&quot;)"
    },
    "pr23": {
      "briefly": "Engraving after Edward Landseer - Lion and Lamb.",
      "image": "prints/pr23.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Lion and Lamb.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Lion and Lamb.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver T. Landseer.",
      "Description.Measurement": " (height: 25&quot;, width: 33&quot;)"
    },
    "pr24": {
      "briefly": "Engraving after Edward Landseer - Children of the Mist, 1856.",
      "image": "prints/pr24.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Children of the Mist, 1856.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Children of the Mist, 1856.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Signed by artist",
      "Description.Measurement": " (height: 20&quot;, width: 24&quot;)"
    },
    "pr25": {
      "briefly": "Engraving after Edward Landseer - The Woodcutter.",
      "image": "prints/pr25.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - The Woodcutter.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "The Woodcutter.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver C. G. Lewis",
      "Description.Measurement": " (height: 19&quot;, width: 24&quot;)"
    },
    "pr26": {
      "briefly": "Engraving after Edward Landseer - Twins.",
      "image": "prints/pr26.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Twins.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Twins.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Signed by artist, engraver T. Landseer",
      "Description.Measurement": " (height: 25&quot;, width: 21&quot;)"
    },
    "pr27": {
      "briefly": "Engraving after Edward Landseer - The Lost Sheep, 1864.",
      "image": "prints/pr27.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - The Lost Sheep, 1864.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "The Lost Sheep, 1864.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, T. Landseer",
      "Description.Measurement": " (height: 31&quot;, width: 17&quot;)"
    },
    "pr28": {
      "briefly": "Engraving after Edward Landseer - The Forester's Family.",
      "image": "prints/pr28.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - The Forester's Family.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "The Forester's Family.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "(Engraver: T. L. Atkinson)",
      "Description.Measurement": " (height: 22&quot;, width: 34&quot;)"
    },
    "pr29": {
      "briefly": "Engraving after Edward Landseer - [Highland Chief's] return from deer stalking.",
      "image": "prints/pr29.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - [Highland Chief's] return from deer stalking.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Highlanders return from deer stalking. (?)",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "(Engraver T. Ryall ?)",
      "Description.Measurement": " (height: 22&quot;, width: 28&quot;)"
    },
    "pr30": {
      "briefly": "Engraving after Edward Landseer - Not Caught yet? 1845.",
      "image": "prints/pr30.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Not Caught yet? 1845.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Not Caught yet? 1845.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Initialled by engraver, T. Landseer",
      "Description.Measurement": " (height: 21&quot;, width: 34&quot;)"
    },
    "pr31": {
      "briefly": "Engraving after Edward Landseer - Red Deer of Chillingham.",
      "image": "prints/pr31.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Red Deer of Chillingham.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Red Deer of Chillingham.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, T. Landseer",
      "Description.Measurement": " (height: 23&quot;, width: 24&quot;)"
    },
    "pr32": {
      "briefly": "Engraving after Edward Landseer - Yo-Ho-Pointers, 1874.",
      "image": "prints/pr32.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Yo-Ho-Pointers, 1874.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Yo-Ho-Pointers, 1874.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, T. Landseer",
      "Description.Measurement": " (height: 23&quot;, width: 33&quot;)"
    },
    "pr33": {
      "briefly": "Engraving after Edward Landseer - Twa dogs.",
      "image": "prints/pr33.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Twa dogs.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1974 (before)",
      "Identification.Title": "Twa dogs.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, T. Landseer [not to be confused with Twa Dogs (Neptune) engraved by B P Gibbon]",
      "Description.Measurement": " (height: 16&quot;, width: 20&quot;)"
    },
    "pr34": {
      "briefly": "Engraving after Edward Landseer - Deer Family, 1874.",
      "image": "prints/pr34.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Deer Family, 1874.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Deer Family, 1874.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, T. Landseer",
      "Description.Measurement": " (height: 27&quot;, width: 20&quot;)"
    },
    "pr35": {
      "briefly": "Engraving after Edward Landseer - Sick Monkey, 1875.",
      "image": "prints/pr35.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Sick Monkey, 1875.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Sick Monkey, 1875.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "(Engraver W H Simmons)",
      "Description.Measurement": " (height: 25&quot;, width: 19&quot;)"
    },
    "pr36": {
      "briefly": "Engraving after Edward Landseer - Braemar.",
      "image": "prints/pr36.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Braemar.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Braemar.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, T. Landseer",
      "Description.Measurement": " (height: 24&quot;, width: 24&quot;)"
    },
    "pr37": {
      "briefly": "Engraving after Edward Landseer - Doubtful Crumbs, 1862.",
      "image": "prints/pr37.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Doubtful Crumbs, 1862.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Doubtful Crumbs, 1862.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Signed by artist &amp; engraver - T. Landseer",
      "Description.Measurement": " (height: 25&quot;, width: 30&quot;)"
    },
    "pr38": {
      "briefly": "Engraving after Edward Landseer - Ptarmigan Hill, 1874.",
      "image": "prints/pr38.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Ptarmigan Hill, 1874.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Ptarmigan Hill, 1874.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, T. Landseer",
      "Description.Measurement": " (height: 21&quot;, width: 35&quot;)"
    },
    "pr39": {
      "briefly": "Engraving after Edward Landseer - The Widow, 1842.",
      "image": "prints/pr39.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - The Widow, 1842.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "The Widow, 1842.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver John Burnet",
      "Description.Measurement": " (height: 17&quot;, width: 22&quot;)"
    },
    "pr40": {
      "briefly": "Engraving after Edward Landseer - The Lassie Herding Sheep, 1843.",
      "image": "prints/pr40.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - The Lassie Herding Sheep, 1843.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "The Lassie Herding Sheep, 1843.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver John Burnet",
      "Description.Measurement": " (height: 19&quot;, width: 24&quot;)"
    },
    "pr41": {
      "briefly": "Engraving after Edward Landseer - Sentinel.",
      "image": "prints/pr41.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Sentinel.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Sentinel.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "(Engraver Thomas Landseer)",
      "Description.Measurement": " (height: 18&quot;, width: 23&quot;)"
    },
    "pr42": {
      "briefly": "Engraving after Edward Landseer - The Stone Breaker's Daughter, 1844.",
      "image": "prints/pr42.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - The Stone Breaker's Daughter, 1844.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "The Stone Breaker's Daughter, 1844.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver John Burnet",
      "Description.Measurement": " (height: 18&quot;, width: 24&quot;)"
    },
    "pr43": {
      "briefly": "Engraving after Edward Landseer - Hawk Trainer.",
      "image": "prints/pr43.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Hawk Trainer.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Hawk Trainer.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Initialled by artist (Engraver  John Burnet)",
      "Description.Measurement": " (height: 18&quot;, width: 24&quot;)"
    },
    "pr45": {
      "briefly": "Engraving after Edward Landseer - Spaniel and Pheasant",
      "image": "prints/pr45.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Spaniel and Pheasant",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Spaniel and Pheasant",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, T. Landseer",
      "Description.Measurement": " (height: 26&quot;, width: 19&quot;)"
    },
    "pr46": {
      "briefly": "Engraving after Edward Landseer - Piper and pair of Nutcrackers, 1865.",
      "image": "prints/pr46.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Piper and pair of Nutcrackers, 1865.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Piper and pair of Nutcrackers, 1865.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, S. Cousins",
      "Description.Measurement": " (height: 23&quot;, width: 19&quot;)"
    },
    "pr47": {
      "briefly": "Engraving after Edward Landseer - Beauty's Bath.",
      "image": "prints/pr47.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Beauty's Bath.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Beauty's Bath.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Signed by artist &amp; engraver - S. Cousins",
      "Description.Measurement": " (height: 21&quot;, width: 13&quot;)"
    },
    "pr48": {
      "briefly": "Engraving after Edward Landseer - Collie Dogs or the Shepherd's Bible.",
      "image": "prints/pr48.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Collie Dogs or the Shepherd's Bible.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Collie Dogs or the Shepherd's Bible.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, C. G. Lewis",
      "Description.Measurement": " (height: 19&quot;, width: 25&quot;)"
    },
    "pr49": {
      "briefly": "Engraving after Edward Landseer - Breakfast Party or Too Hot.",
      "image": "prints/pr49.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Breakfast Party or Too Hot.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Breakfast Party or Too Hot.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "(Engraver J. C. Webb)",
      "Description.Measurement": " (height: 13&quot;, width: 17&quot;)"
    },
    "pr50": {
      "briefly": "Engraving after Edward Landseer - No Place like Home.",
      "image": "prints/pr50.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - No Place like Home.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Be it ever so humble there's no place like home.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "(Engraver B. P. Gibbon)",
      "Description.Measurement": " (height: 17&quot;, width: 20&quot;)"
    },
    "pr51": {
      "briefly": "Engraving after Edward Landseer - Breeze (Retriever).",
      "image": "prints/pr51.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Breeze (Retriever).",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Breeze (Retriever).",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, C. G. Lewis",
      "Description.Measurement": " (height: 19&quot;, width: 24&quot;)"
    },
    "pr52": {
      "briefly": "Engraving after Edward Landseer - Abercorn Children, 1838.",
      "image": "prints/pr52.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Abercorn Children, 1838.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Abercorn Children, 1838.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver, S. Cousins",
      "Description.Measurement": " (height: 17&quot;, width: 17&quot;)"
    },
    "pr53": {
      "briefly": "Engraving after Edward Landseer - Highland Shepherd's Home, 1847.",
      "image": "prints/pr53.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Highland Shepherd's Home, 1847.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Highland Shepherd's Home, 1847.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver B. P. Gibbon",
      "Description.Measurement": " (height: 16&quot;, width: 20&quot;)"
    },
    "pr54": {
      "briefly": "Engraving after Edward Landseer - The Tethered Ram, 1845.",
      "image": "prints/pr54.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - The Tethered Ram, 1845.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "The Tethered Ram, 1845.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver J Burnet et al.",
      "Description.Measurement": " (height: 19&quot;, width: 24&quot;)"
    },
    "pr55": {
      "briefly": "Engraving after Edward Landseer - Roebuck and Rough Hounds.",
      "image": "prints/pr55.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Roebuck and Rough Hounds.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Roebuck and Rough Hounds.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver B. P. Gibbon",
      "Description.Measurement": " (height: 21&quot;, width: 17&quot;)"
    },
    "pr56": {
      "briefly": "Engraving after Edward Landseer - All that Remains of the glory of William Smith, 1836.",
      "image": "prints/pr56.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - All that Remains of the glory of William Smith, 1836.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "All that Remains of the glory of William Smith, 1836.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver John Pye",
      "Description.Measurement": " (height: 7&quot;, width: 6&quot;)"
    },
    "pr57": {
      "briefly": "Engraving after Edward Landseer - Low life (dog in doorway).",
      "image": "prints/pr57.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Low life (dog in doorway).",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1974 (before)",
      "Identification.Title": "Low life",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Measurement": " (height: 10&quot;, width: 8&quot;)"
    },
    "pr58": {
      "briefly": "Engraving after Edward Landseer - Retriever and Woodcock.",
      "image": "prints/pr58.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Retriever and Woodcock.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Retriever and Woodcock.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, T. Landseer",
      "Description.Measurement": " (height: 26&quot;, width: 18&quot;)"
    },
    "pr59": {
      "briefly": "Engraving after Edward Landseer - Shoeing.",
      "image": "prints/pr59.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Shoeing.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Shoeing.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "(Engraver, C. G. Lewis)",
      "Description.Measurement": " (height: 31&quot;, width: 24&quot;)"
    },
    "pr60": {
      "briefly": "Engraving after Edward Landseer - (Stag crossing Loch).",
      "image": "prints/pr60.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - (Stag crossing Loch).",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "The Sanctuary (Stag crossing Loch).",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, C. G. Lewis",
      "Description.Measurement": " (height: 15&quot;, width: 36&quot;)"
    },
    "pr61": {
      "briefly": "Engraving after Edward Landseer - Chillingham Cattle.",
      "image": "prints/pr61.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Chillingham Cattle.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Wild Cattle of Chillingham",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, T. Landseer",
      "Description.Measurement": " (height: 27&quot;, width: 19&quot;)"
    },
    "pr62": {
      "briefly": "Engraving after Edward Landseer - High Life, 1897.",
      "image": "prints/pr62.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - High Life, 1897.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1974 (before)",
      "Identification.Title": "High Life, 1897.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver C. C. Holyer [Not to be confused with High Life engraved by H. S. Beckwith in 1849]",
      "Description.Measurement": " (height: 19&quot;, width: 15&quot;)"
    },
    "pr63": {
      "briefly": "Engraving after Edward Landseer - Queen Victoria and Prince Albert.",
      "image": "prints/pr63.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Queen Victoria and Prince Albert.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1975 (before)",
      "Identification.Title": "Queen Victoria and Prince Albert.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Measurement": " (height: 22&quot;, width: 28&quot;)"
    },
    "pr102": {
      "briefly": "Bolton Abbey in the Olden Time.",
      "image": "prints/pr102.jpg",
      "Identification.BriefDescription": "Bolton Abbey in the Olden Time.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1974 (before)",
      "Identification.ObjectName.other name": "engraving",
      "Description.Note": "after painting by Landseer",
      "Description.Measurement": " (height: 22&quot;, width: 28&quot;)",
      "$Production.Person": [
        "artist: Landseer, Edwin Henry (1802-1873)",
        "engraver: Cousins, S"
      ]
    },
    "pr318": {
      "briefly": "Mezzotint by Samuel Cousins (after Sir Edwin Landseer 'The Connoisseurs' (1997.41)",
      "image": "prints/pr318.jpg",
      "Identification.BriefDescription": "Mezzotint by Samuel Cousins (after Sir Edwin Landseer 'The Connoisseurs' (1997.41)",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "1996",
      "Acquisition.Organisation": "vendor: Howarth Gallery, Burnley",
      "Identification.ObjectName.other name": "mezzotint",
      "Identification.Note": "framed",
      "Description.Measurement": " (height: 15&quot;, width: 21.25)",
      "$Production.Person": [
        "artist: Landseer, Edwin Henry (1802-1873)",
        "engraver: Cousins, Samuel"
      ]
    },
    "pr44": {
      "briefly": "Engraving after Edward Landseer - The Cat's Paw.",
      "image": "prints/pr44.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - The Cat's Paw.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "The Cat's Paw.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver C. G. Lewis",
      "Identification.Note": "framed",
      "Description.Measurement": " (height: 26&quot;, width: 23&quot;)"
    },
    "pr13": {
      "briefly": "Engraving after Edward Landseer - Laying down the law.",
      "image": "prints/pr13.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Laying down the law.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Laying down the law.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "Engraver T. Landseer.",
      "Description.Measurement": " (height: 23&quot;, width: 25&quot;)"
    },
    "pr9": {
      "briefly": "Engraving after Edward Landseer - Uncle Tom and his wife for sale, 1869.",
      "image": "prints/pr9.jpg",
      "Identification.BriefDescription": "Engraving after Edward Landseer - Uncle Tom and his wife for sale, 1869.",
      "Identification.ObjectName.simple name": "print",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Haworth, Jesse (Manchester)",
      "Acquisition.Date": "1908",
      "Identification.Title": "Uncle Tom and his wife for sale, 1869.",
      "Production.Person": "artist: Landseer, Edwin Henry (1802-1873)",
      "Description.Note": "signed by engraver, C. Mottram",
      "Identification.Note": "framed",
      "Description.Measurement": " (height: 21&quot;, width: 27&quot;)"
    }
  },
  "$props": [
    "briefly",
    "image",
    "Identification.BriefDescription",
    "Identification.ObjectName.simple name",
    "Association.Date",
    "Association.Period",
    "Acquisition.Method",
    "Acquisition.Person",
    "Acquisition.Date",
    "Acquisition.Note",
    "Production.Organisation",
    "Acquisition.Organisation",
    "Disposal.Note",
    "$Association.Period",
    "$Acquisition.Person",
    "Identification.ObjectName.other name",
    "Identification.Title",
    "Production.Person",
    "ConditionCheck.Condition",
    "ConditionCheck.Note",
    "ConditionCheck.Date",
    "Content.SummaryText",
    "Description.Note",
    "Description.Condition",
    "Identification.Note",
    "Disposal.Method",
    "Disposal.Organisation",
    "Disposal.Date",
    "Acquisition.ReferenceNumber",
    "Description.Material",
    "Description.Measurement",
    "Association.Note",
    "Conservation.Note",
    "Disposal.ReferenceNumber",
    "Reproduction.Note",
    "Association.Type",
    "Association.Person",
    "Description.Inscription",
    "Production.Date",
    "Production.Period",
    "Rights.Note",
    "$Description.Measurement",
    "Production.Note",
    "Identification.Title.other title",
    "Acquisition.CreditLine",
    "$Production.Person",
    "Production.Place",
    "Description.Completeness",
    "$Description.Note",
    "$Reproduction.Note",
    "$Content.SummaryText",
    "$tags"
  ],
  "$groups": [
    "$Identification",
    "$Association",
    "$Acquisition",
    "$Production",
    "$Disposal",
    "$Reproduction",
    "$ConditionCheck",
    "$Content",
    "$Description",
    "$Conservation",
    "$Rights"
  ],
  "$Identification": [
    "Identification.BriefDescription",
    "Identification.ObjectName.simple name",
    "Identification.ObjectName.other name",
    "Identification.Title",
    "Identification.Note",
    "Identification.Title.other title"
  ],
  "$Association": [
    "Association.Date",
    "Association.Period",
    "$Association.Period",
    "Association.Note",
    "Association.Type",
    "Association.Person"
  ],
  "$Acquisition": [
    "Acquisition.Method",
    "Acquisition.Person",
    "Acquisition.Date",
    "Acquisition.Note",
    "Acquisition.Organisation",
    "$Acquisition.Person",
    "Acquisition.ReferenceNumber",
    "Acquisition.CreditLine"
  ],
  "$Production": [
    "Production.Organisation",
    "Production.Person",
    "Production.Date",
    "Production.Period",
    "Production.Note",
    "$Production.Person",
    "Production.Place"
  ],
  "$Disposal": [
    "Disposal.Note",
    "Disposal.Method",
    "Disposal.Date",
    "Disposal.ReferenceNumber",
    "Disposal.Organisation"
  ],
  "$Reproduction": [
    "Reproduction.Note",
    "$Reproduction.Note"
  ],
  "$ConditionCheck": [
    "ConditionCheck.Condition",
    "ConditionCheck.Note",
    "ConditionCheck.Date"
  ],
  "$Content": [
    "Content.SummaryText",
    "$Content.SummaryText"
  ],
  "$Description": [
    "Description.Note",
    "Description.Condition",
    "Description.Material",
    "Description.Measurement",
    "Description.Inscription",
    "$Description.Measurement",
    "Description.Completeness",
    "$Description.Note"
  ],
  "$Conservation": [
    "Conservation.Note"
  ],
  "$Rights": [
    "Rights.Note"
  ]
};
