var cms_SCU = {
  "name": "sculpture collection",
  "edition": "1",
  "date": "29 Sep 2018",
  "objects": {
    "sc_loan001": {
      "briefly": "Nymph Disturbed at the Bath - marble statue on scagliola plinth. Formerly stood in Huntroyde.",
      "image": "scu/sc_loan001.jpg",
      "Identification.BriefDescription": "Nymph Disturbed at the Bath - marble statue on scagliola plinth. Formerly stood in Huntroyde.",
      "Identification.ObjectName.simple name": "statue and plinth",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Starkie, G P Le Gendre (Huntroyde, Padiham)",
      "Acquisition.Date": "1933.4.20",
      "Acquisition.Note": "AG+M minutes 1772(h) : A letter, dated the 29th ultimo, from Mrs. Le Gendre Starkie, of Huntroyde, was read in which she offered three works of sculpture for exhibition at Towneley Hall for an indefinite period. - The Chairman reported that he had inspected the sculpture and had agreed, on behalf of the Council, to accept the said loan.",
      "Identification.Title": "Nymph Disturbed at the Bath",
      "Production.Person": "artist: Duckett, Thomas (1804 - 1878)",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Crack on left of base, running from bottom of base upwards, approx. 18&quot; long. Surface dirt.",
      "Description.Note": "Monuments in Preston by Duckett include Robert Peel and Lord Derby in Aynhoc (???) Park. See also Burnley Express 13.5.1933",
      "Description.Material": "White marble and scagliola plinth.",
      "Description.Measurement": " (height: 67&quot;, width: 24&quot;, depth: 19&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "sc_loan002": {
      "briefly": "White marble statue of Venus after Canova",
      "image": "scu/sc_loan002.jpg",
      "Identification.BriefDescription": "White marble statue of Venus after Canova",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Starkie, G P Le Gendre Esquire, Huntroyde",
      "Acquisition.Date": "1933",
      "Acquisition.Note": "AG+M minutes 1772(h) : A letter, dated the 29th ultimo, from Mrs. Le Gendre Starkie, of Huntroyde, was read in which she offered three works of sculpture for exhibition at Towneley Hall for an indefinite period. - The Chairman reported that he had inspected the sculpture and had agreed, on behalf of the Council, to accept the said loan.",
      "Identification.ObjectName.other name": "copy of venere italica",
      "Identification.Title": "Venus",
      "Production.Person": "artist: Canova, Antonio (1757 - 1822) (after)",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Surface dirt.",
      "Description.Note": "Formerly stood in the Central Staircase, Huntroyde. See Whittaker's 'History of Whalley' 1876 and Burnley Express 13.5.1933. The statue appears to be one of a very large number of copies of the' Venere Italica' by Canova, now in the Palazzo Pitti, Florence. See Hugh Honour's &quot;Canova's Statues of Venus&quot; The Burlington Magazine, October 1972 p.658-670 (copy on file).",
      "Description.Material": "White marble",
      "Description.Completeness": "complete"
    },
    "sc_loan004": {
      "briefly": "Marble bust depicting Lord Strathallan. Inscribed on reverse 'Tate Sc.'",
      "image": "scu/sc_loan004.jpg",
      "Identification.BriefDescription": "Marble bust depicting Lord Strathallan. Inscribed on reverse 'Tate Sc.'",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "gift",
      "Acquisition.Date": "1926.8.19",
      "Acquisition.Note": "AG+M minute 3101(f) : The Hon. Secretary reported that he had accepted on loan from Lord O'Hagan the following marble busts for exhibition at Towneley Hall: ... 4. A bust of William 4th Viscount Strathallan ; died 1745.",
      "Acquisition.Organisation": "acquired from: O'Hagan, Lord",
      "Identification.Title": "Lord Strathallan",
      "Production.Person": "artist: Tate, Christopher J A",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "Cleaned 1981",
      "Description.Note": "The Towneley 'Black Book' records a 'plaster bust' of James Drummond, 6th Viscount Strathallan, first cousin of Charlotte Teresa Drummond, Wife of Peregrine Edward Towneley.",
      "Description.Material": "Marble",
      "Description.Measurement": " (height: 21&quot;, width: 17&quot;, depth: 8&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "incomplete (Fragment detached from back)"
    },
    "scu1": {
      "briefly": "King Menelaus of Sparta, carved white marble bust on green marble plinth. with white marble base. Bust, socle, plinth, base. Copy of sculpture in Vatican.",
      "image": "scu/scu1.jpg",
      "Identification.BriefDescription": "King Menelaus of Sparta, carved white marble bust on green marble plinth. with white marble base. Bust, socle, plinth, base. Copy of sculpture in Vatican.",
      "Identification.ObjectName.simple name": "bust and plinth",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Massey, Edward Stocks",
      "Acquisition.Date": "1904.8.29",
      "Acquisition.Note": "Art Gallery and Museum sub-committee meeting on 29th August 1904 resolved to accept Mr. Massey's offer &quot;to present ... for exhibition at Towneley Hall, the bust of Menelaus, now on exhibition there, and a series of replicas in marble of the busts of Caesars, Emperors of Rome&quot;",
      "Identification.Title": "King Menelaus of Sparta",
      "Production.Person": "artist: Anon",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Slight chipping around base of bust and edge of left shoulder. Slight surface dirt, especially on base of plinth.",
      "Description.Material": "white marble and green marble",
      "Description.Measurement": " (height: overall height 81&quot; bust height 28&quot;, width: 18&quot;, depth: 12&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete",
      "$Description.Note": [
        "There is also a small bronze copy of Menelaus in the collection [scu040].",
        "full_name: Marble Bust &quot;King Menelaus of Sparta&quot;"
      ]
    },
    "scu2": {
      "briefly": "Virgin and child with six saints, plaster cast in sections. Right hand side with Virgin and Child, St. Lawrence. St. Francis and St. Louise intact.",
      "image": "scu/scu2.jpg",
      "Identification.BriefDescription": "Virgin and child with six saints, plaster cast in sections. Right hand side with Virgin and Child, St. Lawrence. St. Francis and St. Louise intact.",
      "Identification.ObjectName.simple name": "altarpiece",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "1905",
      "Acquisition.Note": "For details of purchase of this along with 11 other plaster casts for the chapel in 1905 see &quot;TAGM Archives - Sculpture Collection&quot; on file",
      "Acquisition.Organisation": "vendor: G. Lelli, Florence",
      "Identification.Title": "Virgin and child with six saints",
      "Production.Person": "artist: Robbia, Luca Della (after)",
      "ConditionCheck.Condition": "poor",
      "Description.Note": "full_name: Plaster cast altarpiece 'Virgin and child with saints and angels' by: Luca della Robbia b.1437 d. 1528",
      "Description.Material": "plaster",
      "Description.Measurement": " (height: 4' 8.5&quot;, width: 5' 8&quot;)",
      "Production.Period": "20th century, early",
      "Description.Completeness": "incomplete (in sections)"
    },
    "scu3": {
      "briefly": "Body of Our Saviour supported by Angels, plaster cast of a relief panel in Victoria and Albert Museum, London.",
      "image": "scu/scu3.jpg",
      "Identification.BriefDescription": "Body of Our Saviour supported by Angels, plaster cast of a relief panel in Victoria and Albert Museum, London.",
      "Identification.ObjectName.simple name": "sculpture",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "1905",
      "Acquisition.Note": "For details of purchase of this along with 11 other plaster casts for the chapel in 1905 see &quot;TAGM Archives - Sculpture Collection&quot; on file",
      "Acquisition.Organisation": "vendor: E. Cantoni, London",
      "Identification.Title": "Body of Our Saviour supported by Angels",
      "Production.Person": "artist: Donatello (1386 - 1466) (After)",
      "Description.Note": "full_name: Plaster cast group 'Body of our saviour supported by angels. by Donatello b. 1386 d. 1466",
      "Description.Material": "Plaster Cast",
      "Description.Measurement": " (height: 3' 7.75&quot;, width: 3' 7.75&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu4": {
      "briefly": "Plaster cast figures of Virgin holding child.",
      "image": "scu/scu4.jpg",
      "Identification.BriefDescription": "Plaster cast figures of Virgin holding child.",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "1905",
      "Acquisition.Note": "For details of purchase of this along with 11 other plaster casts for the chapel in 1905 see &quot;TAGM Archives - Sculpture Collection&quot; on file",
      "Acquisition.Organisation": "vendor: Die General Versaltung der Koniglichen Museen, Berlin",
      "Identification.Title": "Virgin and Child",
      "Production.Person": "artist: Pisano, Giovanni (1240-1320) (After)",
      "ConditionCheck.Condition": "poor",
      "ConditionCheck.Note": "Surface chips. Considerable chipping around base. Considerable surface dirt.",
      "Description.Material": "Plaster Cast",
      "Description.Measurement": " (height: overall height 51&quot; (bottom half 26&quot; top half 25&quot;), width: 17&quot;, depth: 12&quot;)",
      "Production.Period": "20th century, early",
      "Description.Completeness": "incomplete (In two halves)",
      "$Description.Note": [
        "Copy of original in Arena Chapel, Padua.",
        "full_name: Plaster cast group 'Virgin and child' by Giovanni Pisano b. 1240 d. 1320"
      ]
    },
    "scu5": {
      "briefly": "Sculpture in plaster of Virgin and Child.",
      "image": "scu/scu5.jpg",
      "Identification.BriefDescription": "Sculpture in plaster of Virgin and Child.",
      "Identification.ObjectName.simple name": "sculpture",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "1905",
      "Acquisition.Note": "For details of purchase of this along with 11 other plaster casts for the chapel in 1905 see &quot;TAGM Archives - Sculpture Collection&quot; on file",
      "Acquisition.Organisation": "vendor: E. Cantoni, London",
      "Identification.Title": "Virgin and Child",
      "Production.Person": "artist: Quercia, Jacopo Della (1374-1438) (After)",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "very dirty,",
      "Description.Material": "Plaster",
      "Description.Measurement": " (height: 2'5&quot;, width: 13.5&quot;)",
      "Production.Period": "20th century, early",
      "Description.Completeness": "complete",
      "$Description.Note": [
        "&quot;Original in V and A Museum.&quot; according to the 1905 records, but in 2006 the V and A does not claim to own a 'Virgin and child' by Jacopo della Quercia",
        "full_name: Plaster cast group 'Virgin and child' by Jacopo della Quercia b. 1374 d. 1438"
      ]
    },
    "scu6": {
      "briefly": "Cast of marble group Virgin and Child in Notre Dame, Bruges.",
      "image": "scu/scu6.jpg",
      "Identification.BriefDescription": "Cast of marble group Virgin and Child in Notre Dame, Bruges.",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "1905",
      "Acquisition.Note": "For details of purchase of this along with 11 other plaster casts for the chapel in 1905 see &quot;TAGM Archives - Sculpture Collection&quot; on file",
      "Acquisition.Organisation": "vendor: Messrs. Brucciani, London",
      "Identification.Title": "Virgin and Child",
      "Production.Person": "artist: Michelangelo (1474-1563) (After)",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "Surface damage. Considerable surface dirt.",
      "Description.Note": "full_name: Plaster cast group 'Madonna and child' attributed to Michael Angelo b. 1474 d. 1563",
      "Description.Material": "Plaster Cast",
      "Description.Measurement": " (height: 54&quot;, width: 23&quot;, depth: 24&quot;)",
      "Production.Period": "20th century, early",
      "Description.Completeness": "complete"
    },
    "scu7": {
      "briefly": "Plaster cast figure 'Antinous'",
      "Identification.BriefDescription": "Plaster cast figure 'Antinous'",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "untraced find",
      "Acquisition.Note": "There is no evidence for the purchase of this object and it may have been left in the house by Lady O'Hagan in 1902",
      "Identification.Title": "Antoninus",
      "Description.Note": "full_name: Plaster cast figure 'Antinous'",
      "Disposal.Method": "transfer",
      "Disposal.Organisation": "transferee: to : Manchester City Art Gallery",
      "Disposal.Date": "1981.6.10",
      "Description.Material": "Plaster Cast"
    },
    "scu8": {
      "briefly": "Plaster cast figure 'Discobolus'",
      "Identification.BriefDescription": "Plaster cast figure 'Discobolus'",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "untraced find",
      "Acquisition.Note": "There is no evidence for the purchase of this object and it may have been left in the house by Lady O'Hagan in 1902",
      "Identification.Title": "Discobolus",
      "Description.Note": "full_name: Plaster cast figure 'Discobolus'",
      "Disposal.Method": "transfer",
      "Disposal.Organisation": "transferee: to : Manchester City Art Gallery",
      "Disposal.Date": "1981.6.10",
      "Description.Material": "Plaster Cast"
    },
    "scu9": {
      "briefly": "Plaster cast figure 'Germanicus'",
      "Identification.BriefDescription": "Plaster cast figure 'Germanicus'",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "untraced find",
      "Acquisition.Note": "There is no evidence for the purchase of this object and it may have been left in the house by Lady O'Hagan in 1902",
      "Identification.Title": "Germanicus",
      "Description.Note": "full_name: Plaster cast figure 'Germanicus'",
      "Disposal.Method": "transfer",
      "Disposal.Organisation": "transferee: to : Manchester City Art Gallery",
      "Disposal.Date": "1981.6.10",
      "Description.Material": "Plaster Cast"
    },
    "scu10": {
      "briefly": "Plaster cast figure 'St. George'",
      "Identification.BriefDescription": "Plaster cast figure 'St. George'",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "untraced find",
      "Acquisition.Note": "There is no evidence for the purchase of this object and it may have been left in the house by Lady O'Hagan in 1902",
      "Disposal.Note": "Very bad condition and broken",
      "Identification.Title": "St. George",
      "Description.Note": "full_name: Plaster cast figure 'St. George'",
      "Disposal.Method": "destroyed",
      "Disposal.Date": "1980.11",
      "Description.Material": "Plaster Cast"
    },
    "scu11": {
      "briefly": "Plaster cast figure 'The Wrestlers'",
      "Identification.BriefDescription": "Plaster cast figure 'The Wrestlers'",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "untraced find",
      "Acquisition.Note": "There is no evidence for the purchase of this object and it may have been left in the house by Lady O'Hagan in 1902",
      "Identification.Title": "The Wrestlers",
      "Description.Note": "full_name: Plaster cast figure 'The Wrestlers'",
      "Disposal.Method": "transfer",
      "Disposal.Organisation": "transferee: to : Manchester City Art Gallery",
      "Disposal.Date": "1981.6.10",
      "Description.Material": "Plaster Cast"
    },
    "scu12": {
      "briefly": "White marble bust of Augustus Caesar on green marble plinth with white marble base. Bust, socle, plinth, base. Socle inscribed 'Cesare Augusto' on front.",
      "image": "scu/scu12.jpg",
      "Identification.BriefDescription": "White marble bust of Augustus Caesar on green marble plinth with white marble base. Bust, socle, plinth, base. Socle inscribed 'Cesare Augusto' on front.",
      "Identification.ObjectName.simple name": "bust and plinth",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Massey, Edward Stocks (Bamford Hall, Rochdale)",
      "Acquisition.Date": "1906.3.2",
      "Identification.Title": "Augustus Caesar",
      "Production.Person": "artist: Anon",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Good condition, slight surface dirt.",
      "Description.Note": "full_name: Marble Bust &quot;Augustus Caesar&quot;",
      "Description.Material": "white marble and green marble",
      "Description.Measurement": " (height: bust height 25&quot;, width: 23&quot;, depth: 12&quot;)",
      "Description.Completeness": "complete"
    },
    "scu13": {
      "briefly": "White marble bust of Julius Caesar on green marble plinth with white marble base. Bust, socle, plinth, base. Copy of bust in the Vatican.",
      "image": "scu/scu13.jpg",
      "Identification.BriefDescription": "White marble bust of Julius Caesar on green marble plinth with white marble base. Bust, socle, plinth, base. Copy of bust in the Vatican.",
      "Identification.ObjectName.simple name": "bust and plinth",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Massey, Edward Stocks (Bamford Hall, Rochdale)",
      "Acquisition.Date": "1906.3.2",
      "Identification.Title": "Julius Caesar",
      "Production.Person": "artist: Anon",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Chips to base of bust and base of plinth. Surface dirt.",
      "Description.Note": "full_name: Marble Bust &quot;Julius Caesar&quot;",
      "Description.Material": "white marble and green marble",
      "Description.Measurement": " (height: bust height 28&quot;, width: 22&quot;, depth: 12&quot;)",
      "Description.Completeness": "complete"
    },
    "scu14": {
      "briefly": "Bronze statue of female figure. Inscribed 'F. Barbedienne Fondeur' and 'J. Clesinger 1853'. Stamped 'Reduction Mecanique'",
      "image": "scu/scu14.jpg",
      "Identification.BriefDescription": "Bronze statue of female figure. Inscribed 'F. Barbedienne Fondeur' and 'J. Clesinger 1853'. Stamped 'Reduction Mecanique'",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Barnes, Mrs (London)",
      "Acquisition.Date": "1907.6.19",
      "Identification.Title": "La Zingara",
      "Production.Person": "artist: Clesinger, Jean Baptiste",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Top section of first finger on left hand missing. Surface dirt.",
      "Description.Material": "Bronze",
      "Description.Measurement": " (height: 22.5&quot;, width: 8&quot;, depth: 8&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu15": {
      "briefly": "Bronze statue of female figure holding grapes. Inscribed 'F. Barbedienne Fondeur Ferdinand', '121' and 'Clodion'.",
      "image": "scu/scu15.jpg",
      "Identification.BriefDescription": "Bronze statue of female figure holding grapes. Inscribed 'F. Barbedienne Fondeur Ferdinand', '121' and 'Clodion'.",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Barnes, Mrs (London)",
      "Acquisition.Date": "1907.6.19",
      "Identification.Title": "Bacchante",
      "Production.Person": "artist: Claude, Michel (known as 'Clodion')",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Chip on first finger of left and on right wrist. Surface dirt.",
      "Description.Note": "After the Revolution, Clodion created sculptures on the grand scale for the French Government in the more formal neo-classical style - such as the Arc de Triomphe du Carrousel (1805-06) and the Place Vendome Column (180-09).",
      "Description.Material": "Bronze",
      "Description.Measurement": " (height: 21&quot;, width: 8&quot;, depth: 7&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu16": {
      "briefly": "Bronze statue depicting two Bacchantes, one holding a tambourine, dancing with an infant Satyr. Signed 'Clodion, 1762'. Stamped on base '1904'.",
      "image": "scu/scu16.jpg",
      "Identification.BriefDescription": "Bronze statue depicting two Bacchantes, one holding a tambourine, dancing with an infant Satyr. Signed 'Clodion, 1762'. Stamped on base '1904'.",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Barnes, Mrs (London)",
      "Acquisition.Date": "1907.6.19",
      "Identification.Title": "Bacchanalia",
      "Production.Person": "artist: Clodion (After)",
      "Description.Material": "Bronze",
      "Description.Measurement": " (height: 23&quot;, width: 11&quot;, depth: 10&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu17": {
      "briefly": "Two Bronze Urns (copies of the Towneley vase) on cement plated bases. Plaque on front of base inscribed 'Presented by Mrs A. B. Barnes'.",
      "image": "scu/scu17.jpg",
      "Identification.BriefDescription": "Two Bronze Urns (copies of the Towneley vase) on cement plated bases. Plaque on front of base inscribed 'Presented by Mrs A. B. Barnes'.",
      "Identification.ObjectName.simple name": "two bronze urns",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Barnes, Mrs (London)",
      "Acquisition.Date": "1907.6.19",
      "Identification.Title": "Two Bronze Urns (Copies of the Towneley vase)",
      "Production.Person": "artist: Unknown",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "Pieces broken off bases. Some surface dirt.",
      "Description.Note": "full_name: Two bronze urns",
      "Description.Material": "Bronze",
      "Description.Measurement": " (height: 20&quot;, width: 8.5&quot; diameter)",
      "Description.Completeness": "complete (Pieces broken off base but present.)"
    },
    "scu18": {
      "briefly": "White marble bust of Hadrianus on green marble plinth with white marble base. Bust, socle, plinth, base. Socle inscribed 'Hadrianus' on front.",
      "image": "scu/scu18.jpg",
      "Identification.BriefDescription": "White marble bust of Hadrianus on green marble plinth with white marble base. Bust, socle, plinth, base. Socle inscribed 'Hadrianus' on front.",
      "Identification.ObjectName.simple name": "bust and plinth",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Massey, Edward Stocks (Bamford Hall, Rochdale)",
      "Acquisition.Date": "1907.8.19",
      "Identification.Title": "Hadrianus",
      "Production.Person": "artist: Anon",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "good condition, no chips. Surface dirt.",
      "Description.Note": "full_name: Marble bust &quot;Hadrianus&quot;",
      "Description.Material": "white marble and green marble",
      "Description.Measurement": " (height: bust height 28&quot; overall height 82&quot;, width: 26.25&quot;, depth: 14&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu19": {
      "briefly": "White marble bust of Claudius on green marble plinth with white marble base. Bust, title label, socle, plinth, base. Title label inscribed 'Claudius' on front.",
      "image": "scu/scu19.jpg",
      "Identification.BriefDescription": "White marble bust of Claudius on green marble plinth with white marble base. Bust, title label, socle, plinth, base. Title label inscribed 'Claudius' on front.",
      "Identification.ObjectName.simple name": "bust and plinth",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Massey, Edward Stocks (Bamford Hall, Rochdale)",
      "Acquisition.Date": "1909.4.21",
      "Identification.Title": "Claudius",
      "Production.Person": "artist: Anon",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Crack on base of rear of bust, surface dirt.",
      "Description.Note": "full_name: Marble bust &quot;Claudius&quot;",
      "Description.Material": "white marble and green marble",
      "Description.Measurement": " (height: bust height 28.75&quot;&quot; overall height 84&quot;, width: 25&quot;, depth: 17&quot;)",
      "Description.Completeness": "complete"
    },
    "scu20": {
      "briefly": "A set of five 'scagliola' and white marble pedestals, each with white marble base",
      "Identification.BriefDescription": "A set of five 'scagliola' and white marble pedestals, each with white marble base",
      "Identification.ObjectName.simple name": "pedestal",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "1909",
      "Acquisition.Organisation": "vendor: Mr. Whitaker, Church Street, Burnley",
      "Description.Material": "marble"
    },
    "scu21": {
      "briefly": "Happier Than a King - White marble figure lying on an alabaster cushion. Signature inscribed on cushion (back) P. C. E. Fiaschi, Title in French inscribed on cushion (front).",
      "image": "scu/scu21.jpg",
      "Identification.BriefDescription": "Happier Than a King - White marble figure lying on an alabaster cushion. Signature inscribed on cushion (back) P. C. E. Fiaschi, Title in French inscribed on cushion (front).",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "gift",
      "Acquisition.Date": "1922 (circa)",
      "Acquisition.Note": "Not mentioned in AG+M minutes but the Hon. Secretary's Report for the year ending 31st March, 1923 reports among others, the following gift - Marble Statuette, &quot;Happier than a King&quot; from the Directors of the Burnley Football Club, which was brought back by the Burnley Team after their tour in Italy. (The tour took place in May and June 1922 and was reported in the local newspapers of that period.)",
      "Acquisition.Organisation": "acquired from: Burnley Football Club",
      "Identification.Title": "Happier Than a King (Heureuse plus qu'un Roi)",
      "Production.Person": "artist: Fiaschi, Emilio (1858-1941)",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Good condition but bruising on front of cushion.",
      "Description.Note": "full_name: Marble figure &quot;Happier than a King&quot;",
      "Description.Material": "White marble and alabaster",
      "Description.Measurement": " (height: 13&quot;, width: 16&quot;, depth: 12&quot;)",
      "Description.Inscription": " (inscription : engraving : base of cushion : : P. C.  E. Fiaschi (Professor Com Emilio Fiaschi))",
      "Production.Period": "20th century, early",
      "Production.Note": "The Italian sculptor Emilio Fiaschi studied at the Istituto di belle arti in Florence from 1883 to 1885. In 1890 he won the competition of sculptors from Volterra with the bust of Mario Ricciarelli.",
      "Description.Completeness": "complete"
    },
    "scu22": {
      "briefly": "2 plaster casts of the Kay Shuttleworth brother in medallion form. Relief portraits in profile. Framed together in wooden, rectangular frame. Each medallion 14.5&quot; dia.",
      "image": "scu/scu22.jpg",
      "Identification.BriefDescription": "2 plaster casts of the Kay Shuttleworth brother in medallion form. Relief portraits in profile. Framed together in wooden, rectangular frame. Each medallion 14.5&quot; dia.",
      "Identification.ObjectName.simple name": "2 plaster casts in medallion form",
      "Acquisition.Method": "gift",
      "Acquisition.Date": "1921.7.28",
      "$Acquisition.Person": [
        "donor: Shuttleworth, Lord",
        "donor: Shuttleworth, Lady"
      ],
      "Identification.Title": "Late Rt. Hon. Lawrence Ughtred Kay Shuttleworth and Rt. Hon. Edward James Kay Shuttleworth 1921",
      "Production.Person": "artist: Carrick, A (A.R.S.A)",
      "Description.Note": "full_name: Two plaster casts in Medallion form - 1. Late Rt. Hon. Lawrence Ughtred Kay-Shuttleworth, Captain, R.F.A. - 2. Late Rt. Hon. Edward James Kay-Shuttleworth, 7th Rifle Brigade.",
      "Description.Material": "Plaster",
      "Description.Measurement": " (height: 19&quot;, width: 34.5&quot;)",
      "Description.Completeness": "complete"
    },
    "scu22b": {
      "briefly": "framed plaster cast recording the names of Lawrence and Edward Shuttleworth, who died in 1917.",
      "image": "scu/scu22b.jpg",
      "Identification.BriefDescription": "framed plaster cast recording the names of Lawrence and Edward Shuttleworth, who died in 1917.",
      "Identification.ObjectName.simple name": "plaster cast",
      "Acquisition.Method": "gift",
      "Acquisition.Date": "1921.7.28",
      "$Acquisition.Person": [
        "donor: Shuttleworth, Lord",
        "donor: Shuttleworth, Lady"
      ],
      "Production.Person": "artist: Carrick, A (A.R.S.A)"
    },
    "scu23": {
      "briefly": "The Chatelaine, bronze bust on wooden stand. Inscribed on reverse 'Fond A Bruno Roma'",
      "image": "scu/scu23.jpg",
      "Identification.BriefDescription": "The Chatelaine, bronze bust on wooden stand. Inscribed on reverse 'Fond A Bruno Roma'",
      "Identification.ObjectName.simple name": "bust on plinth",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: Gilbert, Walter (62-66 Weaman Street, Birmingham)",
      "Acquisition.Date": "1927.2.17",
      "Identification.Title": "The Chatelaine (Portrait of Lady O'Hagan)",
      "Production.Person": "artist: Gilbert, Alfred M V O",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Slight surface dirt.",
      "Description.Material": "Bronze bust on wooden plinth",
      "Description.Measurement": " (height: 27&quot;, width: 26&quot;, depth: 14&quot;)",
      "Production.Period": "20th century",
      "Description.Completeness": "incomplete",
      "$Description.Note": [
        "chain and key missing (&quot;necklace&quot;); Exhibited 1986 'Alfred Gilbert, Sculptor and Goldsmith' Royal Academy, London, 1986. Cat. No. 110.",
        "full_name: Bronze bust &quot;The Chatelaine&quot; by Alfred Gilbert M.V.O. Rome"
      ]
    },
    "scu24": {
      "briefly": "The Virtuoso, bronze bust on wooden stand. Inscribed on reverse 'Fond A Bruno Roma'",
      "image": "scu/scu24.jpg",
      "Identification.BriefDescription": "The Virtuoso, bronze bust on wooden stand. Inscribed on reverse 'Fond A Bruno Roma'",
      "Identification.ObjectName.simple name": "bust on plinth",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: Gilbert, Walter (62-66 Weaman Street, Birmingham)",
      "Acquisition.Date": "1927.2.17",
      "Identification.Title": "The Virtuoso (Portrait of Edward Stocks Massey)",
      "Production.Person": "artist: Gilbert, Alfred M V O",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Slight surface dirt",
      "Description.Material": "Bronze bust on wooden plinth",
      "Description.Measurement": " (height: 29&quot;, width: 26&quot;, depth: 15&quot;)",
      "Production.Period": "20th century",
      "Description.Completeness": "complete",
      "$Description.Note": [
        "Exhibited 1986 'Alfred Gilbert, Sculptor and Goldsmith' Royal Academy, London, 1986. Cat. No. 159.",
        "full_name: Bronze bust &quot;The Virtuoso&quot; by Alfred Gilbert M.V.O. Rome"
      ]
    },
    "scu26": {
      "briefly": "The Rt. Hon Lady O'Hagan - bronze bust on bronze plinth",
      "image": "scu/scu26.jpg",
      "Identification.BriefDescription": "The Rt. Hon Lady O'Hagan - bronze bust on bronze plinth",
      "Identification.ObjectName.simple name": "bust and plinth",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: Gilbert, Walter (Birmingham)",
      "Acquisition.Date": "1929.5.17",
      "Identification.Title": "The Rt. Hon Lady O'Hagan",
      "Production.Person": "artist: Gilbert, Walter (1870 - 1946)",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Good condition. Slight surface dirt.",
      "Description.Note": "full_name: Bronze bust The Late Rt. Hon Lady O'Hagan by Walter Gilbert",
      "Description.Material": "Bronze",
      "Description.Measurement": " (height: 15&quot;, width: 12&quot;, depth: 9&quot;)",
      "Production.Period": "20th century",
      "$tags": ["WalterGilbert"]
    },
    "scu27": {
      "briefly": "Marble bust of Lucy Ellen Towneley on painted wooden plinth. Bust, socle, plinth. Inscribed on reverse 'L. MacDonald Fecit Roma 1841'.",
      "image": "scu/scu27.jpg",
      "Identification.BriefDescription": "Marble bust of Lucy Ellen Towneley on painted wooden plinth. Bust, socle, plinth. Inscribed on reverse 'L. MacDonald Fecit Roma 1841'.",
      "Identification.ObjectName.simple name": "bust and plinth",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Parker, Denham, Mrs, London",
      "Acquisition.Date": "1928",
      "Identification.Title": "Lucy Ellen Towneley 1841",
      "Production.Person": "artist: MacDonald, Lawrence",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Some chips on plinth. Surface dirt.",
      "Description.Note": "full_name: Lucy Ellen Towneley Mother of Richard Towneley",
      "Description.Material": "White marble",
      "Description.Measurement": " (height: 21&quot;, width: 16&quot;, depth: 9&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu28": {
      "briefly": "Painted plaster bust depicting Rev. Canon Winfield, Vicar of St. James, Burnley 1887-1929. Plaster painted bronze effect.",
      "image": "scu/scu28.jpg",
      "Identification.BriefDescription": "Painted plaster bust depicting Rev. Canon Winfield, Vicar of St. James, Burnley 1887-1929. Plaster painted bronze effect.",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "gift",
      "Acquisition.Date": "1928.8.16",
      "$Acquisition.Person": [
        "donor: Stevens, Dr",
        "donor: Stevens, Mrs"
      ],
      "Identification.Title": "Rev. Canon Winfield",
      "Production.Person": "artist: Lindley-Millican, Alice (A.R.S.O.P)",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "Surface damage. Surface dirt.",
      "Description.Material": "Plaster (painted bronze effect)",
      "Description.Measurement": " (height: 26&quot;, width: 23&quot;, depth: 12&quot;)",
      "Production.Period": "20th century",
      "Description.Completeness": "complete",
      "$Description.Note": [
        "Rev. Canon Winfield was Vicar of St. James, Burnley 1887-1929. Was a member of Burnley School Board and the Local Education Committee for 27 years.",
        "full_name: Plaster cast bust. Rev Canon Winfield B.A. by Mrs Millican A.R.S.O.P."
      ]
    },
    "scu29": {
      "briefly": "Alabaster bust of female.",
      "image": "scu/scu29.jpg",
      "Identification.BriefDescription": "Alabaster bust of female.",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Smith, Mrs (Cliviger)",
      "Acquisition.Date": "1927.4.21",
      "Identification.Title": "The Jewess",
      "Production.Person": "artist: Unknown",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "Small chip to left shoulder. Considerable surface dirt.",
      "Description.Note": "full_name: Marble bust &quot;The Jewess&quot;",
      "Description.Material": "Alabaster",
      "Description.Measurement": " (height: 18&quot;, width: 15.5&quot;, depth: 10&quot;)",
      "Description.Completeness": "complete"
    },
    "scu30": {
      "briefly": "Plaster cast bust of John Towneley. Inscribed 'LA(e) Macdonald Roma 1838.",
      "image": "scu/scu30.jpg",
      "Identification.BriefDescription": "Plaster cast bust of John Towneley. Inscribed 'LA(e) Macdonald Roma 1838.",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "gift",
      "Acquisition.Date": "1902 (circa)",
      "Acquisition.Note": "Not mentioned in AG+M minutes nor in early exhibition catalogues, this bust can be seen in a photograph of the Entrance Hall around 1915 and was probably left in store at Towneley when the family departed in 1902.",
      "Acquisition.Organisation": "acquired from: O'Hagan, Lady (Burnley)",
      "Identification.Title": "John Towneley 1806 - 1878",
      "Production.Person": "artist: MacDonald, Lawrence (1799-1878)",
      "ConditionCheck.Condition": "poor",
      "ConditionCheck.Note": "Surface chipping. Considerable surface dirt.",
      "Description.Note": "full_name: Plaster bust of John Towneley by L. A. Macdonald",
      "Description.Material": "Plaster Cast",
      "Description.Measurement": " (height: 26&quot;, width: 18&quot;, depth: 13&quot;)",
      "Production.Date": "1838",
      "Description.Completeness": "complete"
    },
    "scu31": {
      "briefly": "Painted plaster cast bust of Venus",
      "image": "scu/scu31.jpg",
      "Identification.BriefDescription": "Painted plaster cast bust of Venus",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "gift",
      "Acquisition.Date": "1902 (circa)",
      "Acquisition.Note": "Not mentioned in AG+M minutes nor in early exhibition catalogues, this bust can be seen in a photograph of the Entrance Hall dated around 1915-1920. It was probably left in store at Towneley when the family departed in 1902.",
      "Acquisition.Organisation": "acquired from: O'Hagan, Lady (Burnley)",
      "Identification.Title": "Venus",
      "Production.Person": "artist: Unknown",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "painted surface cracked on front, falling away at back with half removed.",
      "Description.Material": "Plaster Cast",
      "Description.Measurement": " (height: 31&quot;, width: 20&quot;, depth: 13&quot;)",
      "Description.Completeness": "complete",
      "$Description.Note": [
        "Inscribed on back of base &quot;D. BRUCCIANI&quot;. In the latter part of the 19th and early part of the 20th century the Royal Academy relied on the firm of D. Brucciani and Company for its day-to-day supply of plaster casts. Domenico Brucciani was born in Lucca in 1815 and came to England in the 1830s. By 1837 he had set up his business in Covent Garden and in 1864 his Galleria boasted copies of all the finest statuary in existence. The Academy thought so highly of this establishment that during the First World War they raised sufficient funds to tide the firm over the war period and avoid the dispersion of its huge collection of casts and moulds.",
        "full_name: Plaster bust of Venus"
      ]
    },
    "scu32": {
      "briefly": "Marble bust Head of a man",
      "Identification.BriefDescription": "Marble bust Head of a man",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "untraced find",
      "Acquisition.Note": "only known from inventory record",
      "Identification.Title": "Head of a man",
      "Production.Person": "artist: Unknown",
      "Description.Note": "full_name: Marble bust Head of a man"
    },
    "scu33": {
      "briefly": "Full length, winged figure of a child holding a bag of money. Inscribed on plinth 'The Genius of Commerce'.",
      "image": "scu/scu33.jpg",
      "Identification.BriefDescription": "Full length, winged figure of a child holding a bag of money. Inscribed on plinth 'The Genius of Commerce'.",
      "Identification.ObjectName.simple name": "statue and plinth",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Cooper, C, Mrs, Great Brookham",
      "Acquisition.Date": "1936.4.23",
      "Acquisition.Note": "AG+M minute 1788(h) : The Town Clerk submitted offers of the gift of the under-mentioned exhibits:- ... A piece of statuary entitled 'Genius of Commerce', from Mrs. E. Cooper, of Great Brookham.",
      "Identification.Title": "The Genius of Commerce 1861",
      "Production.Person": "artist: Fontana, G (Snr.)",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "surface dirt, ? has missing toe been retained?",
      "Description.Note": "full_name: Marble statue &quot;Genius of Commerce&quot; by : G. Fontana Snr. 1861.",
      "Description.Material": "Marble",
      "Description.Measurement": " (height: 44&quot;, width: 15&quot;)",
      "Description.Completeness": "incomplete (Left big toe snipped)"
    },
    "scu34": {
      "briefly": "Marble bust - subject unknown",
      "Identification.BriefDescription": "Marble bust - subject unknown",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "untraced find",
      "Acquisition.Note": "only known from inventory record",
      "Identification.Title": "unknown",
      "Production.Person": "artist: Unknown",
      "Description.Note": "full_name: Marble bust - subject unknown",
      "Description.Measurement": " (height: &quot;, width: &quot;, depth: &quot;)"
    },
    "scu35": {
      "briefly": "Oak statue of virgin figure holding child.",
      "image": "scu/scu35.jpg",
      "Identification.BriefDescription": "Oak statue of virgin figure holding child.",
      "Identification.ObjectName.simple name": "oak statue",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Dean, W H, Burnley",
      "Acquisition.Date": "1937.2.18",
      "Acquisition.Note": "AG+M minute 1165(m) : The Town Clerk submitted offers of the under-mentioned exhibits:- Oak Statue, &quot;Virgin and Child&quot;, from Mr. W. Dean, Burnley",
      "Identification.Title": "Virgin and Child",
      "Production.Person": "artist: Unknown",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "Head re-glued with Evostick Dec. 1983. Toes and leg of child damaged.",
      "Description.Material": "Oak",
      "Description.Measurement": " (height: 30&quot;, width: 12&quot;, depth: 9&quot;)",
      "Production.Period": "16th century",
      "Description.Completeness": "complete",
      "$Description.Note": [
        "Exhibited 18.1.1998 - 8.3.1998 'Who Was Who in Burnley', Towneley Hall.",
        "full_name: Carved oak statuette &quot;Virgin and Child&quot; 16th century Burgundian 30&quot; high"
      ]
    },
    "scu36": {
      "briefly": "Life size statues in bronze of a stag and a doe deer.",
      "image": "scu/scu36.jpg",
      "Identification.BriefDescription": "Life size statues in bronze of a stag and a doe deer.",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: Laycock, F (Skipton)",
      "Acquisition.Date": "1948.10.21",
      "Acquisition.Note": "AG+M minute 4829(g): The Town Clerk reported that, as requested by this Sub-Committee the Chairman (Mr. Alderman Bushby) had purchased from Mr. F. Laycock, of Skipton, a pair of life-size bronze deer (which were formerly at Lowther Castle) at a cost of £65. RESOLVED - (1) That the action of the Chairman be confirmed, and that cost thereof and the cost of minor repairs and cartage be paid for out of moneys provided by the Massey Bequest Fund; and (2) That the Parks , Small Holdings and Allotments Committee be requested to allow the same to be placed in a suitable position in the flower garden adjoining Towneley Hall.",
      "Identification.Title": "Bronze Deer",
      "Production.Person": "artist: Unknown",
      "Description.Material": "Bronze",
      "Description.Completeness": "incomplete",
      "$Description.Note": [
        "only one deer accounted for, deer vandalised prior to 1971 (see file)",
        "full_name: Two full size bronze statues of deer"
      ]
    },
    "scu37": {
      "briefly": "Bust of unknown man inscribed 'R. Rinaldi F. Roma 1866'.",
      "image": "scu/scu37.jpg",
      "Identification.BriefDescription": "Bust of unknown man inscribed 'R. Rinaldi F. Roma 1866'.",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: Bushby, Mr (Burnley)",
      "Acquisition.Date": "1950.7.20",
      "Acquisition.Note": "AG+M minute 1212(i): The Chairman (Mr. Alderman Bushby) reported that he had authorised the purchase of a marble pedestal from the Cliffe Castle Sale at Keighley, and that a rouge marble tapering pedestal and a white marble bust by R. Rinaldi (1866) had been purchased for 37/6d. plus the cost of carriage.",
      "Identification.Title": "marble bust of unknown man",
      "Production.Person": "artist: Rinaldi, Rinaldo (1793-1873)",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Surface dirt.",
      "Description.Material": "Marble",
      "Description.Measurement": " (height: 21&quot;, width: 16&quot;, depth: 12&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete",
      "$Description.Note": [
        "Height of socle 6&quot;, diameter 10.5&quot;. Inscribed on back 'R. Rinaldi F. Roma 1866'. Rinaldo di Rinaldi, born in Padua in 1793, was a pupil of Canova and died in Rome in 1873.",
        "full_name: Marble bust and rouge marble pedestal by R. Rinaldi (1866)"
      ]
    },
    "scu38": {
      "briefly": "White marble statue on wooden plinth, plinth made 2002. Inscribed ' W. Theed. Sc. London, 1867' on right hand side of base and 'The Prodigal's Return' on front of base.",
      "image": "scu/scu38.jpg",
      "Identification.BriefDescription": "White marble statue on wooden plinth, plinth made 2002. Inscribed ' W. Theed. Sc. London, 1867' on right hand side of base and 'The Prodigal's Return' on front of base.",
      "Identification.ObjectName.simple name": "statue and plinth",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Greenwood, A (Colne)",
      "Acquisition.Date": "1952.6.12",
      "Acquisition.Note": "AG+M minute 667(k): The Curator reported that the following gifts had been offered to the Towneley Hall Art Gallery and Museum - ... 18. By Mr A. Greenwood of Colne - marble statue &quot;The Prodigal Son&quot; sculptured by W. Threed of London, 1867",
      "Identification.Title": "The Prodigal's Return 1867",
      "Production.Person": "artist: Theed, W (1804 - 1891)",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Chip to left of base of statue. Surface dirt, staining on base.",
      "Description.Note": "full_name: Marble statue &quot;The Prodigal's Return&quot; by W. Theed, London 1867",
      "Description.Material": "White Marble and wooden plinth",
      "Description.Measurement": " (height: 45&quot;, width: 24&quot;, depth: 13&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu39": {
      "briefly": "Alabaster bust on green marble base. Depicts Joan of Arc wearing armour and holding a sword and shield. Inscribed 'JEANNE D'ARC' on base of bust.",
      "image": "scu/scu39.jpg",
      "Identification.BriefDescription": "Alabaster bust on green marble base. Depicts Joan of Arc wearing armour and holding a sword and shield. Inscribed 'JEANNE D'ARC' on base of bust.",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: Bushby, Mr (Burnley)",
      "Acquisition.Date": "1953.1.13",
      "Acquisition.Note": "AG+M minute 3224(k): The Chairman reported that the Curator and he had attended a public auction sale, and had purchased the following articles :- Alabaster bust &quot;Jeanne D'Arc&quot; £2-10s-0d.",
      "Identification.Title": "Jeanne d'Arc",
      "Production.Person": "artist: Unknown",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Surface chips and bruising. Surface dirt.",
      "Description.Note": "full_name: Alabaster bust &quot;Jeanne D'Arc&quot;",
      "Description.Material": "Alabaster and marble",
      "Description.Measurement": " (height: 16&quot; excluding base. Base 1.75&quot; high 14&quot; wide and 6.5&quot; deep, width: 19.5&quot;, depth: 7.5&quot;)",
      "Description.Completeness": "complete"
    },
    "scu40": {
      "briefly": "Copy bronze plated bust of Menelaus. Marked on reverse.",
      "image": "scu/scu40.jpg",
      "Identification.BriefDescription": "Copy bronze plated bust of Menelaus. Marked on reverse.",
      "Identification.ObjectName.simple name": "bust and plinth",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: Bushby, Mr (Burnley)",
      "Acquisition.Date": "1953.1.13",
      "Acquisition.Note": "AG+M minute 3224(k): The Chairman reported that the Curator and he had attended a public auction sale, and had purchased the following articles :- West African fetish and copy bronze bust of statue in Towneley Hall £0-10s-0d",
      "Identification.Title": "Menelaus",
      "Production.Person": "artist: Unknown",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Good condition. Surface dirt.",
      "Description.Note": "full_name: Bronze bust &quot;Menelaus&quot;",
      "Description.Material": "Bronze plated",
      "Description.Measurement": " (height: 8&quot; excluding plinth. Plinth 2&quot; h 5&quot; diameter, width: 4&quot;, depth: 4&quot;)",
      "Description.Completeness": "complete"
    },
    "scu41": {
      "briefly": "White marble statue on painted marble plinth. Inscription on base of statue 'John Adams Acton Fecit Rome, 1865' and 'Emily and the White Doe of Rylstone'. Moveable socle on marble plinth. Figure's veil has blue and white painted edge line.",
      "image": "scu/scu41.jpg",
      "Identification.BriefDescription": "White marble statue on painted marble plinth. Inscription on base of statue 'John Adams Acton Fecit Rome, 1865' and 'Emily and the White Doe of Rylstone'. Moveable socle on marble plinth. Figure's veil has blue and white painted edge line.",
      "Identification.ObjectName.simple name": "statue and plinth",
      "Acquisition.Method": "bequest",
      "Acquisition.Person": "donor: Pemberton, E L (Nelson)",
      "Acquisition.Date": "1953.3.10",
      "Acquisition.Note": "AG+M minute 3991(f): The Curator reported that the late Ernest Edward Pemberton of Nelson had, under his will, bequeathed a marble statue &quot;Emily and the White Doe of Rylstone&quot; to the Towneley Hall Museum, and that the bequest had now been received at the Museum.",
      "Identification.Title": "Emily and the White Doe of Rylstone 1865",
      "Production.Person": "artist: Acton, John Adams",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Small chips to base of statue. Small chips to base of plinth. Considerable surface dirt.",
      "Description.Material": "Marble and painted marble plinth.",
      "Description.Measurement": " (height: 38&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete",
      "$Description.Note": [
        "Statue based on poem by Wordsworth.",
        "full_name: Marble statue on base &quot;Emily and the White Doe of Rylstone&quot;"
      ]
    },
    "scu42": {
      "briefly": "The Medici Venus - marble statue on wooden plinth. Copy of classical status in the Uffizi, Florence.",
      "image": "scu/scu42.jpg",
      "Identification.BriefDescription": "The Medici Venus - marble statue on wooden plinth. Copy of classical status in the Uffizi, Florence.",
      "Identification.ObjectName.simple name": "statue and plinth",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: King, D J, Mrs, Hebden Bridge",
      "Acquisition.Date": "1954.2.9",
      "Acquisition.Note": "AG+M minutes 1947(b): The Sub-Committee considered an offer by Mrs. D. J. King of Hebden Bridge to sell for £5 a statue in Florentine Marble and to sell other articles. RESOLVED - (1) That the statue be purchased and the cost thereof and the cost of removal to Towneley Hall be paid for out of moneys allocated to this Sub-Committee by the Massey Bequest Sub-Committee;",
      "Identification.Title": "The Medici Venus",
      "Production.Person": "artist: Anon",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Slight chipping to base of statue. Higher cherub missing left wing. Slight surface dirt.",
      "Description.Note": "full_name: Florentine marble statue &quot;Venus de Medici&quot;",
      "Description.Material": "Florentine marble and wooden plinth",
      "Description.Measurement": " (height: 60&quot;, width: 18&quot;, depth: 20&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu43": {
      "briefly": "Boxwood figure of Christ with arms outstretched and flowing hair. No crucifix.",
      "image": "scu/scu43.jpg",
      "Identification.BriefDescription": "Boxwood figure of Christ with arms outstretched and flowing hair. No crucifix.",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "1957.4.9",
      "Acquisition.Note": "AG+M minute 1534(e) 85 : ... the Curator reported that he had been offered a 16th century boxwood figure of Christ Crucified (without the cross) by Mary Bellis of Hungerford, Berkshire, at the price of £68. RESOLVED - That the figure be purchased and that the cost be defrayed out of moneys allocated to this Sub-Committee from the Massey Bequest Fund.",
      "Acquisition.Organisation": "vendor: Mary Bellis Antiques, Hungerford",
      "Identification.Title": "Crucified Christ",
      "Production.Person": "artist: Unknown",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "Finger broken and missing. Crack running down centre of back, approx. 2.5&quot; long.",
      "Description.Note": "full_name: Carved boxwood figure of Christ crucified (Spanish 17/18th century) 11 3/4&quot; high",
      "Description.Material": "Boxwood",
      "Description.Measurement": " (height: 14&quot;, width: 9.5&quot;, depth: 3&quot;)",
      "Production.Date": "1600 to 1799",
      "Description.Completeness": "incomplete (Left little finger missing. No crucifix.)"
    },
    "scu44.1": {
      "briefly": "wooden carving of Horse and Cart with Firewood",
      "image": "scu/scu44.1.jpg",
      "Identification.BriefDescription": "wooden carving of Horse and Cart with Firewood",
      "Identification.ObjectName.simple name": "wooden carving",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Hartley, Mr (Padiham)",
      "Acquisition.Date": "1969.9.28",
      "Acquisition.Note": "information from Permanent Collection Book [1932-1974]",
      "Identification.Title": "Carved Horse and Cart with Firewood",
      "Production.Person": "artist: Unknown",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "Surface dust. horse's ear broken and missing",
      "Description.Note": "full_name: Wood carving group Russian - Horse and cart with firewood",
      "Description.Material": "Wood",
      "Description.Measurement": " (height: 6&quot;, width: 13&quot;, depth: 4&quot;)",
      "Production.Period": "20th century",
      "Description.Completeness": "complete"
    },
    "scu44.2": {
      "briefly": "wooden carvings of two horses and carriage with three figures in carriage",
      "image": "scu/scu44.2.jpg",
      "Identification.BriefDescription": "wooden carvings of two horses and carriage with three figures in carriage",
      "Identification.ObjectName.simple name": "wooden carving",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Hartley, Mr (Padiham)",
      "Acquisition.Date": "1969.9.28",
      "Identification.Title": "Two horses and carriage with three figures in carriage",
      "Production.Person": "artist: Unknown",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "Surface dust. right horse's front leg snapped, still present.",
      "Description.Note": "full_name: Wood carving group Russian - Two horses and carriage with three figures in carriage",
      "Description.Material": "Wood",
      "Description.Measurement": " (height: 6&quot;, width: 11&quot;, depth: 4&quot;)"
    },
    "scu45": {
      "briefly": "Clytie -white marble bust on white marble socle copy by unknown artist",
      "image": "scu/scu45.jpg",
      "Identification.BriefDescription": "Clytie -white marble bust on white marble socle copy by unknown artist",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Sharrocks, Mr (Burnley)",
      "Acquisition.Date": "1946.9.19",
      "Acquisition.Note": "AG+M minutes 4013(g) : The Town Clerk reported that Mr. Sharrocks, of Cleveland Mount, Burnley, had offered to give a white marble bust of Clytie for exhibition, in the Museum,",
      "Identification.Title": "&quot;Clytie&quot;",
      "Production.Person": "artist: Nollekens, Joseph, R A (after)",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Chips around leaf-like effects to bottom of statue. Gash on right of neck. hole on left shoulder to rear of figure. Considerable surface dirt.",
      "Description.Note": "full_name: Marble bust &quot;Clytie&quot;",
      "Description.Material": "White marble",
      "Description.Measurement": " (height: 26&quot;, width: 18.5&quot;, depth: 12&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu46": {
      "briefly": "Bronze bust of Bernard Van Dieren on oak stand",
      "image": "scu/scu46.jpg",
      "Identification.BriefDescription": "Bronze bust of Bernard Van Dieren on oak stand",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: Epstein, Jacob",
      "Acquisition.Date": "1943.6.17",
      "Acquisition.Note": "AG+M minutes 2366(g) : The Sub-Committee inspected a bronze bust of the musical composer, Bernard von Dieren, sculptured by Jacob Epstein, which was offered to this Sub-Committee by the sculptor for £220, of which amount he agreed that one-half should be given to the Merchant Navy Comforts Services. RESOLVED - That the bust and a suitable stand for the same be purchased out of moneys in the General Exhibits Account",
      "Identification.Title": "Bernard Van Dieren 1984-1936",
      "Production.Person": "artist: Epstein, Jacob",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Slight surface dirt.",
      "Description.Material": "Bronze bust on oak plinth.",
      "Description.Measurement": " (height: 19&quot;, width: 20&quot;, depth: 10.5&quot;)",
      "Production.Period": "20th century",
      "Description.Completeness": "complete",
      "$Description.Note": [
        "See Epstein 'Let there be Sculpture', published as 'Epstein an Autobiography' London 1963 pp78-79, pp 101-102. Telephone conversation with Dr. Evelyn Suber 2.6.1998. Bust of Van Dieren sculpted 1934-5 (was exhibited at Leicester Galleries in March 1935). Original plaster is in the Clarke Art Institute, Williamston, Massachusetts - probably given by Lady Epstein in the mid 1960's or 70's. Scottish National Gallery of Modern Art has Epstein's 'Risen Christ' for which artist used Van Dieren as a model.",
        "full_name: Bust of Bernard Van Dieren 1884-1936 by Jacob Epstein (Bronze)"
      ]
    },
    "scu47": {
      "briefly": "Inscribed plaque showing a man and woman fighting for a pair of breeches (both have one leg in them), with an upset beehive and a cock and hen at their sides.",
      "image": "scu/scu47.jpg",
      "Identification.BriefDescription": "Inscribed plaque showing a man and woman fighting for a pair of breeches (both have one leg in them), with an upset beehive and a cock and hen at their sides.",
      "Identification.ObjectName.simple name": "inscribed plaque",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Halstead, E (Cliviger)",
      "Acquisition.Date": "1981",
      "Identification.Title": "Fight for the Breeches",
      "Production.Person": "artist: Bailey, E B",
      "ConditionCheck.Condition": "good",
      "Description.Note": "full_name: Inscribed plaque - Fight for the Breeches",
      "Description.Material": "Marble inlaid with lead",
      "Description.Completeness": "complete"
    },
    "scu48": {
      "briefly": "Marble bust on painted wooden plinth. Inscribed 'Thomas O'Hagan C' and 'Presented by his friends'.",
      "image": "scu/scu48.jpg",
      "Identification.BriefDescription": "Marble bust on painted wooden plinth. Inscribed 'Thomas O'Hagan C' and 'Presented by his friends'.",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "gift",
      "Acquisition.Date": "1939.8.17",
      "Acquisition.Note": "AG+M minutes 2838(f) : The Hon Secretary reported that the marble bust of the Rt. Hon. Thomas O'Hagan, Lord Chancellor of Ireland, by Shakespere Wood, referred to in Minute No. 2381(b) had safely arrived at Towneley Hall and that Lord O'Hagan had also sent an illuminated address which was presented to his father along with the marble bust. In September 2006, the illuminated address was stored in the sculpture collection file in the General Office.",
      "Acquisition.Organisation": "acquired from: O'Hagan, Lord (Ickworth Lodge, Suffolk)",
      "Identification.Title": "Thomas O'Hagan. C. (1812-1885)",
      "Production.Person": "artist: Wood, Shakespeare",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Some chips and cracks on plinth. Surface dirt.",
      "Description.Note": "full_name: Marble bust &quot;Lord O'Hagan&quot; by Shakespeare Wood",
      "Description.Material": "White marble",
      "Description.Measurement": " (height: 29&quot;, width: 18&quot;, depth: 12&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu49": {
      "briefly": "disposal record - wooden sculpture depicted a grebe.",
      "Identification.BriefDescription": "disposal record - wooden sculpture depicted a grebe.",
      "Identification.ObjectName.simple name": "sculpture",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: Taplin, Guy (Wivenhoe, Essex)",
      "Acquisition.Date": "1990",
      "Disposal.Note": "see paper disposal record attached to exit form",
      "Identification.Title": "Grebe",
      "Production.Person": "artist: Taplin, Guy (1939 - )",
      "Disposal.Method": "destroyed",
      "Disposal.Date": "2014.7",
      "Description.Material": "Driftwood",
      "Description.Measurement": " (height: 11&quot;, width: 25&quot;, depth: 10&quot;)",
      "Disposal.ReferenceNumber": "DPF2014.1 (exit reference number: exit185)",
      "Production.Period": "20th century"
    },
    "scu50": {
      "briefly": "Plaster cast figure of St. Francis.",
      "image": "scu/scu50.jpg",
      "Identification.BriefDescription": "Plaster cast figure of St. Francis.",
      "Identification.ObjectName.simple name": "plaster cast",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "1905",
      "Acquisition.Note": "For details of purchase of this along with 11 other plaster casts for the chapel in 1905 see &quot;TAGM Archives - Sculpture Collection&quot; on file. Listed in &quot;Inventory of 1938&quot; as lent to School of Art and destroyed by damage 14.12.1933.",
      "Acquisition.Organisation": "vendor: E. Cantoni, London",
      "Identification.Title": "St. Francis",
      "Production.Person": "artist: Donatello (After)",
      "ConditionCheck.Condition": "poor",
      "ConditionCheck.Note": "Surface chips. Considerable surface dirt.",
      "Description.Material": "Plaster Cast",
      "Description.Measurement": " (height: 63&quot;, width: 21&quot;, depth: 13&quot;)",
      "Production.Period": "20th century, early",
      "Description.Completeness": "complete (neck broken and mended.)",
      "$Description.Note": [
        "Original figure forms part of the bronze altarpiece in S. Antonio, Padua.",
        "full_name: Plaster cast figure &quot;St. Francis&quot; after Donatello b.1386 d.1466"
      ]
    },
    "scu51": {
      "briefly": "A pair of plaques in wooden frames, depicting St. Louis landing at Damietta and St. Louis returning from the Crusade.",
      "image": "scu/scu51.jpg",
      "Identification.BriefDescription": "A pair of plaques in wooden frames, depicting St. Louis landing at Damietta and St. Louis returning from the Crusade.",
      "Identification.ObjectName.simple name": "a pair of plaques",
      "Acquisition.Method": "bequest",
      "Acquisition.Person": "donor: Massey, E Stocks, Mrs",
      "Acquisition.Date": "1922.3.23",
      "Acquisition.Note": "AG+M minute 1646(g) : A letter, dated the 24th ultimo, from Messrs. Broughton, Holt and Middlemist, Solicitors, London, was read, in which they reported that the late Mrs. E. E. Massey, of Bamford Hall, had bequeathed to the Corporation for exhibition at the Towneley Museum a Black and White Drawing by Deneven Adams, two silver bronze medallions and a Japanese Marriage Chest. The Chairman reported that he had accepted the articles on behalf of the Corporation, and that they had been removed to Towneley Hall",
      "Identification.Title": "Crusaders 1851",
      "Production.Person": "artist: Justin",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Slight surface damage.",
      "Description.Material": "Copper electroplated with silver &amp; wood frame",
      "Description.Measurement": " (height: 14.5&quot; without frame 11.5&quot; (oval shaped), width: 18.5&quot; without frame 14.5&quot; (oval shaped))",
      "Production.Date": "1851",
      "Description.Completeness": "complete",
      "$Description.Note": [
        "See file for details: The plaques were modelled by the French sculptor, Justin, for the Great Exhibition of 1851.They were manufactured by Messrs. Elkington",
        "full_name: Two electroplated metal medallions &quot;Crusaders&quot; by Justin"
      ]
    },
    "scu52": {
      "briefly": "2 white silk covered shaped medallions depicting Earl of Beaconsfield and Marquis of Salisbury in profile. Velvet covered frames. Labels on reverse read 'By Royal Letters Patent. Stucco Manufacturing Co. 67 Briggate, Leeds'.",
      "image": "scu/scu52.jpg",
      "Identification.BriefDescription": "2 white silk covered shaped medallions depicting Earl of Beaconsfield and Marquis of Salisbury in profile. Velvet covered frames. Labels on reverse read 'By Royal Letters Patent. Stucco Manufacturing Co. 67 Briggate, Leeds'.",
      "Identification.ObjectName.simple name": "two circular medallions",
      "Acquisition.Method": "untraced find",
      "Identification.Title": "Earl of Beaconsfield and Marquis of Salisbury",
      "Production.Person": "artist: Unknown",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "Blue velvet around the edge of the frames rather worn and frayed.",
      "Description.Note": "full_name: two white medallions depicting Earl of Beaconsfield and Marquis of Salisbury in profile",
      "Description.Material": "Blue velvet and white silk",
      "Description.Measurement": " (height: 10&quot; diameter (circular), depth: 1.5&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu53": {
      "briefly": "Bust depicting the head of a young girl, in alabaster.",
      "image": "scu/scu53.jpg",
      "Identification.BriefDescription": "Bust depicting the head of a young girl, in alabaster.",
      "Identification.ObjectName.simple name": "bust",
      "Association.Period": "19th century",
      "Acquisition.Method": "untraced find",
      "Acquisition.Note": "not gift from the Honourable R. B. Kay-Shuttleworth as previously thought",
      "Identification.Title": "Head of a Young Girl 1864",
      "Production.Person": "artist: Raemaekers, J (Exh. 1864 - 1892)",
      "ConditionCheck.Condition": "poor",
      "ConditionCheck.Note": "Some surface chips. Star diadem chipped. Very dirty.",
      "Description.Note": "full_name: Bust depicting the head of a young girl, in alabaster",
      "Description.Material": "Alabaster (?)",
      "Description.Measurement": " (height: 14&quot;, width: 11.5&quot;, depth: 7&quot;)",
      "Description.Completeness": "complete"
    },
    "scu54": {
      "briefly": "marble bust of General Scarlett",
      "image": "scu/scu54.jpg",
      "Identification.BriefDescription": "marble bust of General Scarlett",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: Kershaw, M, Mrs (Lytham, Lancashire)",
      "Acquisition.Date": "1972.3",
      "Acquisition.Note": "Loans book Marble bust of General Scarlett loaned for exhibition 5.11.1971. After end of exhibition was purchased from owners &quot;see March Minutes 1972&quot; but was not added to permanent collection nor added to accession register until 2006.",
      "Identification.Title": "Bust of General Scarlett",
      "Production.Person": "artist: Noble, Matthew (1817-76)",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Date": "2006.10.5",
      "Description.Note": "full_name: Bust of Lt-General The Hon. Sir J Yorke Scarlett, G.C.B.",
      "Description.Material": "marble",
      "Production.Date": "1873",
      "Production.Period": "19th century",
      "Production.Note": "Another portrait bust of General Scarlett by Noble (completed in 1874) is set in an ornate niche in St. Peter's Church, Burnley.",
      "Description.Completeness": "complete"
    },
    "scu55": {
      "briefly": "Full length figure depicting St. John the Baptist dressed in animal skin. Painted plaster figure in 2 sections.",
      "image": "scu/scu55.jpg",
      "Identification.BriefDescription": "Full length figure depicting St. John the Baptist dressed in animal skin. Painted plaster figure in 2 sections.",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "1905",
      "Acquisition.Note": "For details of purchase of this along with 11 other plaster casts for the chapel in 1905 see &quot;TAGM Archives - Sculpture Collection&quot; on file",
      "Acquisition.Organisation": "vendor: Die General Versaltung der Koniglichen Museen, Berlin",
      "Identification.Title": "St. John the Baptist",
      "Production.Person": "artist: Benedetto (da Maiano) (b.1442 d.1497)",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "clear break between two halves, base very dirty",
      "Description.Note": "full_name: plaster cast figure of St. John the Baptist",
      "Description.Material": "Plaster",
      "Description.Measurement": " (height: 57&quot;, width: 19&quot;, depth: 12&quot;)",
      "Production.Period": "20th century, early",
      "Description.Completeness": "incomplete (in 2 sections)"
    },
    "scu56": {
      "briefly": "Full length figure of a woman in peasant/gypsy costume.",
      "image": "scu/scu56.jpg",
      "Identification.BriefDescription": "Full length figure of a woman in peasant/gypsy costume.",
      "Identification.ObjectName.simple name": "statue",
      "Acquisition.Method": "untraced find",
      "Acquisition.Note": "not gift from the Honourable R. B. Kay-Shuttleworth as previously thought",
      "Identification.Title": "Statue of a Woman",
      "Production.Person": "artist: Unknown",
      "ConditionCheck.Condition": "poor",
      "ConditionCheck.Note": "Right hand, base and foot broken (fragments also held), damage to cuff of left arm and hem of dress. Considerable surface dirt.",
      "Description.Note": "full_name: small marble statue of woman in peasant costume",
      "Description.Material": "Marble",
      "Description.Measurement": " (height: 21&quot;, width: 7.5&quot;, depth: 6&quot;)",
      "Description.Completeness": "complete"
    },
    "scu57": {
      "briefly": "Clytie - white marble bust on white marble socle. Inscribed 'Nollekens Ft. 1807'.",
      "image": "scu/scu57.jpg",
      "Identification.BriefDescription": "Clytie - white marble bust on white marble socle. Inscribed 'Nollekens Ft. 1807'.",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "gift",
      "Acquisition.Date": "2003",
      "Acquisition.Organisation": "acquired from: O'Hagan, Lord",
      "Identification.Title": "&quot;Clytie&quot;",
      "Production.Person": "artist: Nollekens, Joseph, R A",
      "ConditionCheck.Condition": "good",
      "Description.Note": "full_name: White marble bust on white marble socle. Inscribed 'Nollekens Ft. 1807'.",
      "Description.Material": "White marble",
      "Description.Measurement": " (height: 26&quot;, width: 18.5&quot;, depth: 12&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu58": {
      "briefly": "White marble bust of John Towneley (1731-1813) in the form of a term",
      "image": "scu/scu58.jpg",
      "Identification.BriefDescription": "White marble bust of John Towneley (1731-1813) in the form of a term",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "2008.2.8",
      "Acquisition.Note": "On loan at Towneley from O'Hagan family since 1926. Purchased with funding from the Towneley Hall Society.",
      "Acquisition.Organisation": "vendor: R. Holden Fine Art Agents",
      "Identification.Title": "John Towneley (1731-1813)",
      "Production.Person": "artist: Nollekens, Joseph R A (studio of)",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Slight surface dirt.",
      "Description.Note": "John Towneley was second surviving son of Richard Towneley (1689 - 1735) and inherited Towneley on the death of his nephew, Edward Towneley Standish, in 1807. Seen by Dino Tomasso, Oct. 2006. Not by Nolleken's hand; quality is not good enough, a studio work.",
      "Acquisition.ReferenceNumber": "432",
      "Description.Material": "White marble",
      "Description.Measurement": " (height: 18.5&quot;, width: 12&quot;, depth: 8.75&quot;)",
      "Production.Date": "1813 (circa)",
      "Production.Note": "There is an engraving published June 1. 1815 by W. Clarke, New Bond Street inscribed &quot;W. Behnes del.t Rob.t Cooper Scu&quot;",
      "Description.Completeness": "complete"
    },
    "scu59": {
      "briefly": "White marble bust of Barbara Towneley (1757-1836)",
      "image": "scu/scu59.jpg",
      "Identification.BriefDescription": "White marble bust of Barbara Towneley (1757-1836)",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "2008.2.8",
      "Acquisition.Note": "On loan at Towneley from O'Hagan family since 1926. Purchased with funding from the Towneley Hall Society.",
      "Acquisition.Organisation": "vendor: R. Holden Fine Art Agents",
      "Identification.Title": "Barbara Towneley (1757-1836)",
      "Production.Person": "artist: Griggs, William",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "Slight surface dirt.",
      "Description.Note": "Inscribed on the reverse 'Griggs'. The Towneley 'Black Book' records a bust of Barbara Towneley in the Red Drawing Room in 1844. Barbara Towneley was the eldest surviving daughter of John Towneley (1731 - 1813) and married Sir William Stanley of Wooton. She helped to found the Convent of the Holy Child Jesus, St. Leonards on Sea. A copy of the bust at the Convent was destroyed during World War II.",
      "Acquisition.ReferenceNumber": "432",
      "Description.Material": "White marble",
      "Description.Measurement": " (height: 17.5&quot;, width: 11&quot;, depth: 10&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu60": {
      "briefly": "White marble bust of Charles Townley (1737-1805) in the form of a term",
      "image": "scu/scu60.jpg",
      "Identification.BriefDescription": "White marble bust of Charles Townley (1737-1805) in the form of a term",
      "Identification.ObjectName.simple name": "bust",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "2008.11",
      "Acquisition.Note": "to be completed",
      "Acquisition.Organisation": "vendor: Daniel Katz Limited, London",
      "Identification.Title": "Charles Townley (1737-1805)",
      "Production.Person": "artist: Nollekens, Joseph, R A",
      "Acquisition.ReferenceNumber": "to be completed",
      "Description.Material": "White marble",
      "Description.Measurement": " (height: to be completed, width: to be completed, depth: to be completed)",
      "Production.Date": "1807",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu61": {
      "briefly": "carved conch shell with a relief of the procession of Dionysus (19th century)",
      "image": "scu/scu61.jpg",
      "Identification.BriefDescription": "carved conch shell with a relief of the procession of Dionysus (19th century)",
      "Identification.ObjectName.simple name": "shell",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Ashworth, Mr",
      "Acquisition.Date": "1946",
      "Acquisition.Note": "AG&amp;M sub-committee 1945-6 [minute 1176(g)] 24th January, 1946. The sub-committee informed Mr H. Ashworth of Burnley that they would accept, under his will, &quot;a large sea shell carved in cameo fashion&quot;.",
      "Production.Person": "artist: Unknown",
      "ConditionCheck.Condition": "good",
      "Description.Material": "conch shell",
      "Description.Measurement": " (height: 9.5&quot;, width: 7&quot;, depth: 6&quot;)",
      "Production.Period": "19th century",
      "Description.Completeness": "complete"
    },
    "scu62": {
      "briefly": "Swan Preening by Vivien Whitaker, a sculpture carved from one of the last pieces of English Alabaster",
      "image": "scu/scu62.jpg",
      "Identification.BriefDescription": "Swan Preening by Vivien Whitaker, a sculpture carved from one of the last pieces of English Alabaster",
      "Identification.ObjectName.simple name": "sculpture",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Whitaker, Vivien",
      "Acquisition.Date": "2011.2.9",
      "Acquisition.Note": "gift from the artist",
      "Production.Person": "artist: Whitaker, Vivien",
      "ConditionCheck.Condition": "good",
      "Acquisition.ReferenceNumber": "oef612",
      "Description.Measurement": " (height: _, width: _, depth: _)",
      "Production.Period": "21st century",
      "Description.Completeness": "complete"
    },
    "scu63": {
      "briefly": "Art Nouveau style bronze plaque depicting nude male harpist and Blackpool coat of arms.",
      "image": "scu/scu63.jpg",
      "Identification.BriefDescription": "Art Nouveau style bronze plaque depicting nude male harpist and Blackpool coat of arms.",
      "Identification.ObjectName.simple name": "plaque",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1972",
      "Acquisition.Note": "presented to Burnley Library by Mrs. E. Hitchon 1948",
      "Acquisition.Organisation": "acquired from: Burnley Central Library",
      "Production.Person": "artist: Unknown",
      "Description.Note": "Maker: Signed J. Millard 1907",
      "Description.Material": "bronze and oak",
      "Description.Measurement": " (height: 14.5&quot;, width: 8&quot;, depth: _)",
      "Description.Inscription": " (&quot;Blackpool Musical Festival&quot; Male Voice Choir winners of Grundy Trophy Conductor E. Hitchon. Given by Cuthbert C. Grundy)"
    },
    "scu64": {
      "briefly": "Jesmonite cast of the Townley Discobolus with wax finish",
      "image": "scu/scu64.jpg",
      "Identification.BriefDescription": "Jesmonite cast of the Townley Discobolus with wax finish",
      "Identification.ObjectName.simple name": "cast",
      "Acquisition.Method": "gift",
      "Acquisition.Date": "2015.3.17",
      "Acquisition.Organisation": "acquired from: Towneley Hall Society",
      "Production.Person": "artist: Lendzion, Andrew",
      "Acquisition.ReferenceNumber": "oef2015.1",
      "Description.Material": "resin (jesmonite)",
      "Description.Measurement": " (Height: 1.7 metres; Width: 1.05 metres; Depth 0.63 metres)",
      "Production.Date": "2010",
      "Acquisition.CreditLine": "Gift from the Towneley Hall Society to mark their 50th anniversary in 2015"
    },
    "scu65": {
      "briefly": "Plaster cast of the Townley Discobolus",
      "image": "scu/scu65.jpg",
      "Identification.BriefDescription": "Plaster cast of the Townley Discobolus",
      "Identification.ObjectName.simple name": "cast",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Lendzion, Andrew",
      "Acquisition.Date": "2015.3.17",
      "Production.Person": "artist: Lendzion, Andrew",
      "Acquisition.ReferenceNumber": "oef2015.2",
      "Description.Material": "plaster",
      "Description.Measurement": " (Height: 1.7 metres; Width: 1.05 metres; Depth 0.63 metres)",
      "Production.Date": "2010",
      "Acquisition.CreditLine": "Gift of the artist, Andrew Lendzion"
    },
    "scu25": {
      "briefly": "Edward Stocks Massey - bronze bust",
      "image": "scu/scu25.jpg",
      "Identification.BriefDescription": "Edward Stocks Massey - bronze bust",
      "Identification.ObjectName.simple name": "bust and plinth",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: Gilbert, Walter (Birmingham)",
      "Acquisition.Date": "1927.12.22",
      "Identification.Title": "The Late Edward Stocks Massey (1850 - 1909)",
      "Production.Person": "artist: Gilbert, Walter (1870 - 1946)",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "good condition but metal label removed, showing screw holes in base of bust",
      "Description.Material": "Bronze",
      "Description.Measurement": " (height: 17&quot;, width: 12&quot;, depth: 7&quot;)",
      "Production.Period": "20th century",
      "$Description.Note": [
        "See information on file",
        "full_name: Bronze bust The Late Edward Stocks Massey, J.P. by Walter Gilbert"
      ],
      "$tags": ["WalterGilbert"]
    }
  },
  "$props": [
    "briefly",
    "image",
    "Identification.BriefDescription",
    "Identification.ObjectName.simple name",
    "Association.Date",
    "Association.Period",
    "Acquisition.Method",
    "Acquisition.Person",
    "Acquisition.Date",
    "Acquisition.Note",
    "Production.Organisation",
    "Acquisition.Organisation",
    "Disposal.Note",
    "$Association.Period",
    "$Acquisition.Person",
    "Identification.ObjectName.other name",
    "Identification.Title",
    "Production.Person",
    "ConditionCheck.Condition",
    "ConditionCheck.Note",
    "ConditionCheck.Date",
    "Content.SummaryText",
    "Description.Note",
    "Description.Condition",
    "Identification.Note",
    "Disposal.Method",
    "Disposal.Organisation",
    "Disposal.Date",
    "Acquisition.ReferenceNumber",
    "Description.Material",
    "Description.Measurement",
    "Association.Note",
    "Conservation.Note",
    "Disposal.ReferenceNumber",
    "Reproduction.Note",
    "Association.Type",
    "Association.Person",
    "Description.Inscription",
    "Production.Date",
    "Production.Period",
    "Rights.Note",
    "$Description.Measurement",
    "Production.Note",
    "Identification.Title.other title",
    "Acquisition.CreditLine",
    "$Production.Person",
    "Production.Place",
    "Description.Completeness",
    "$Description.Note",
    "$Reproduction.Note",
    "$Content.SummaryText",
    "$tags"
  ],
  "$groups": [
    "$Identification",
    "$Association",
    "$Acquisition",
    "$Production",
    "$Disposal",
    "$Reproduction",
    "$ConditionCheck",
    "$Content",
    "$Description",
    "$Conservation",
    "$Rights"
  ],
  "$Identification": [
    "Identification.BriefDescription",
    "Identification.ObjectName.simple name",
    "Identification.ObjectName.other name",
    "Identification.Title",
    "Identification.Note",
    "Identification.Title.other title"
  ],
  "$Association": [
    "Association.Date",
    "Association.Period",
    "$Association.Period",
    "Association.Note",
    "Association.Type",
    "Association.Person"
  ],
  "$Acquisition": [
    "Acquisition.Method",
    "Acquisition.Person",
    "Acquisition.Date",
    "Acquisition.Note",
    "Acquisition.Organisation",
    "$Acquisition.Person",
    "Acquisition.ReferenceNumber",
    "Acquisition.CreditLine"
  ],
  "$Production": [
    "Production.Organisation",
    "Production.Person",
    "Production.Date",
    "Production.Period",
    "Production.Note",
    "$Production.Person",
    "Production.Place"
  ],
  "$Disposal": [
    "Disposal.Note",
    "Disposal.Method",
    "Disposal.Date",
    "Disposal.ReferenceNumber",
    "Disposal.Organisation"
  ],
  "$Reproduction": [
    "Reproduction.Note",
    "$Reproduction.Note"
  ],
  "$ConditionCheck": [
    "ConditionCheck.Condition",
    "ConditionCheck.Note",
    "ConditionCheck.Date"
  ],
  "$Content": [
    "Content.SummaryText",
    "$Content.SummaryText"
  ],
  "$Description": [
    "Description.Note",
    "Description.Condition",
    "Description.Material",
    "Description.Measurement",
    "Description.Inscription",
    "$Description.Measurement",
    "Description.Completeness",
    "$Description.Note"
  ],
  "$Conservation": [
    "Conservation.Note"
  ],
  "$Rights": [
    "Rights.Note"
  ]
};
