var cms_BOOKS = {
  "name": "books collection",
  "edition": "1",
  "date": "16 Nov 2023",
  "objects": {
    "book1": {
      "briefly": "History of Whalley (1801) - hardback, brown leather cover, height 303 mm.",
      "Identification.BriefDescription": "History of Whalley (1801) - hardback, brown leather cover, height 303 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: Drew, Paul (Cliviger)",
      "Acquisition.Date": "1981",
      "Identification.Title": "History of the original parish of Whalley first edition (1801)",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "inside back cover binding torn",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "A history of the original parish of Whalley, which had an area of over 100,000 acres covering most of north east Lancashire from Clitheroe and Colne in the north to Haslingden and Newchurch in the south. The book was dedicated to Charles Townley (1737-1805) and contains a short history of Towneley and the Towneley family.]"
    },
    "book2": {
      "briefly": "History of Whalley (1818) - hardback, black cover with red leather spine and corners, height 398 mm.",
      "Identification.BriefDescription": "History of Whalley (1818) - hardback, black cover with red leather spine and corners, height 398 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "2000.12",
      "Acquisition.Organisation": "vendor: Rochdale Bookshop, Rochdale",
      "Identification.Title": "History of the original parish of Whalley third edition (1818)",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "back cover loose",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "The third edition of the History of Whalley, published in 1818, corrected many of the errors of the first and second editions. It added a number of biographical memoirs of local people including several members of the Towneley family."
    },
    "book3": {
      "briefly": "Life of Sir George Radcliffe - hardback, buff cover with green spine, height 310 mm.",
      "Identification.BriefDescription": "Life of Sir George Radcliffe - hardback, buff cover with green spine, height 310 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "2001",
      "Acquisition.Organisation": "vendor: Rochdale Bookshop, Rochdale",
      "Identification.Title": "The life and original correspondence of Sir George Radcliffe",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "The wife of Sir George Radcliffe was the sister of Mary Towneley (1599-1690) and the Towneley family are mentioned in the letters. On page 165 is the first publication of an anecdote relating the meeting between Mary Towneley and Oliver Cromwell on the morning following the battle of Marston Moor."
    },
    "book4": {
      "briefly": "Old Halls in Lancashire and Cheshire - hardback, brown cover, height 325 mm.",
      "Identification.BriefDescription": "Old Halls in Lancashire and Cheshire - hardback, brown cover, height 325 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "2001",
      "Acquisition.Organisation": "vendor: Rochdale Bookshop, Rochdale",
      "Identification.Title": "Old Halls in Lancashire and Cheshire",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "spine badly torn, binding loose",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "Old Halls in Lancashire and Cheshire by Henry Taylor, published in 1884, includes reproductions of drawings made by Rev. S J Allen in Burnley in the 1830s."
    },
    "book5": {
      "briefly": "Itinerary of Lancaster - hardback, marbled cover with brown leather spine and corners, height 245 mm.",
      "Identification.BriefDescription": "Itinerary of Lancaster - hardback, marbled cover with brown leather spine and corners, height 245 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1972 (before)",
      "Acquisition.Note": "Included in Hector Thornton's library catalogue c.1970 but not recorded in the permanent collection ledger (1932-1972) or in any earlier accession register.",
      "Identification.Title": "Itinerary of Lancaster",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "back edge worn, &quot;914.72&quot; and &quot;942.72&quot; written in white crayon on spine",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "Itinerary of Lancaster written by Cyrus Redding, published in 1842, includes a description of a visit to Towneley on pages 185 to 189 together with two line drawings on page 186."
    },
    "book6": {
      "briefly": "The spending of the money of Robert Nowell - hardback, green cover, height 219 mm.",
      "Identification.BriefDescription": "The spending of the money of Robert Nowell - hardback, green cover, height 219 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "2000.1.31",
      "Acquisition.Note": "recorded as a permanent loan",
      "Acquisition.Organisation": "acquired from: Burnley Central Library",
      "Identification.Title": "The spending of the money of Robert Nowell",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "The spending of the money of Robert Nowell, edited from the original MSS. at Towneley Hall by Rev. Alexander B. Grosart, records the distribution of cloth among the poor of Burnley in 1569 to satisfy the requirements of Robert's will. It is a good indication of the Burnley population at that time and includes the names of all the domestic servants at Towneley Hall on 7th July 1569."
    },
    "book7": {
      "briefly": "Human passion delineated - hardback, buff cover with brown leather spine and corners, height 386 mm.",
      "Identification.BriefDescription": "Human passion delineated - hardback, buff cover with brown leather spine and corners, height 386 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Tyrrell, Elaine, Miss, Harrogate",
      "Acquisition.Date": "1977.7.7",
      "Identification.Title": "Human passion delineated",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "front lower corner worn",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "44 engravings from caricature drawings with accompanying commentary by John Collier aka Tim Bobbin, published at Rochdale in 1773."
    },
    "book8": {
      "briefly": "Penny Magazine 1834 - hardback, marble cover (very worn) with brown leather spine and corners, height 287 mm.",
      "Identification.BriefDescription": "Penny Magazine 1834 - hardback, marble cover (very worn) with brown leather spine and corners, height 287 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1972 (before)",
      "Identification.Title": "The Penny Magazine Volume III",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "12 monthly parts of Penny Magazine for 1834 bound by T. Rickard, Burnley, and containing 231 illustrations of a wide range of subjects."
    },
    "book9": {
      "briefly": "The Ursuline Manual - hardback, black leather cover, height 158 mm.",
      "Identification.BriefDescription": "The Ursuline Manual - hardback, black leather cover, height 158 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Higgin, W, Mr, Blackpool",
      "Acquisition.Date": "1969.6.9",
      "Identification.Title": "The Ursuline Manual",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "A collection of prayers , spiritual exercises etc., arranged for the young ladies and inscribed &quot;Margaret Parker aged 11 years - presented to her o the occasion of her making her first communion, December 25th 1852 by her sincere friend Caroline H Towneley - Towneley December 25th 1852&quot;"
    },
    "book10": {
      "briefly": "Corte di Roma - hardback, parchment covered, height 165 mm.",
      "Identification.BriefDescription": "Corte di Roma - hardback, parchment covered, height 165 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Townley, Frank (London)",
      "Acquisition.Date": "1949.8.5",
      "Acquisition.Note": "Provenance: Letter from Frank Townley explaining how the book came into his possession and offering the book is on file [Charles Towneley (1737-1805) - file 1 of 2 ]",
      "Identification.Title": "Corte di Roma",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "excellent except for 800 written in black ink on front cover and Towneley Art Gallery ink stamp on fly leaf.",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "Lo Stato Presente o sia la relazione della Corte di Roma, Andrea Tosi, Rome 1765 It has Charles Townley's Whitehall bookplate and contains a 'who was who' in the papal government at time he visited Rome."
    },
    "book11": {
      "briefly": "Illustrated prayer book - hardback, dark brown leather cover, height 144 mm.",
      "Identification.BriefDescription": "Illustrated prayer book - hardback, dark brown leather cover, height 144 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Smith, M, Mrs, Morecambe",
      "Acquisition.Date": "1942.2.19",
      "Identification.Title": "Prayer book printed in the reign of Charles II between 1679 and 1685",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "front cover almost completely loose; several missing and badly damaged pages at front and back. [labelled on modern cover, not on book itself]",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "Anglican prayer book from the reign of Charles II with numerous engravings of heads of saints and scenes from the Bible."
    },
    "book12": {
      "briefly": "Battle of Waterloo - hardback, pale blue cover with dark blue spine, height 257 mm.",
      "Identification.BriefDescription": "Battle of Waterloo - hardback, pale blue cover with dark blue spine, height 257 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Davids, Ann Gore, Mrs, London",
      "Acquisition.Date": "1951.2.28",
      "Acquisition.Note": "Donated along with award presented to A. Gore in 1798[CM/A/22]",
      "Identification.Title": "An historical account of the Battle of Waterloo",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "944.05 boldly written three times in black ink on front cover and Burnley ink stamp on title page and elsewhere",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "An historical account of the Battle of Waterloo, translated from the French by Arthur Gore in 1817. It includes 9 pages of engravings. Two of these show the positions of the two armies and fold out to 56 cm. ."
    },
    "book13": {
      "briefly": "Mary Elizabeth Towneley - hardback, blue cover, height 223 mm.",
      "Identification.BriefDescription": "Mary Elizabeth Towneley - hardback, blue cover, height 223 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1972 (before)",
      "Acquisition.Note": "The best preserved of several copies. It is marked in pencil &quot;1997/7&quot;. It may be one of two copies donated by The Sisters, The Convent of Notre Dame, 118 St. George's Road, Southwark, London SE1 on 14.9.1968.",
      "Identification.Title": "Mary Elizabeth Towneley - A Memoir",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "spine cover worn and back cover binding broken, otherwise in good condition with all pages securely bound.",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "Biography of the daughter of John Towneley (1806-1878) together with brief illustrated history of the Towneley and Tichborne families together with their pedigree."
    },
    "book14": {
      "briefly": "Geography book - hardback, brown leather cover, height 142 mm.",
      "Identification.BriefDescription": "Geography book - hardback, brown leather cover, height 142 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1972 (before)",
      "Acquisition.Note": "recorded previously part of Do/U collection in 1971",
      "Identification.Title": "Geography for schools and young persons",
      "ConditionCheck.Condition": "poor",
      "ConditionCheck.Note": "cover very worn, binding bad with many loose pages",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "A schools geography book with small number of block illustrations and two fold out maps of America and the British Isles"
    },
    "book15": {
      "briefly": "Prayer book (1680) - hardback, black leather cover, height 167 mm.",
      "Identification.BriefDescription": "Prayer book (1680) - hardback, black leather cover, height 167 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Mason, Anthony (Nelson)",
      "Acquisition.Date": "1975.5.8",
      "Acquisition.Note": "recorded in day book in 1975 as 1975.23",
      "Identification.Title": "Book of Common Prayer (1680)",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "242 written in white crayon on front cover and spine",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "Anglican prayer book published at the Theater in Oxford in 1680. The frontispiece  contains an engraving of a church interior. The book includes the names of former owners including Henry Simpson and Thomas Harker, who was at Burnley Grammar School in January 1713 and was an iron and tin plate worker at St James Street Burnley (August 17th 1767)."
    },
    "book16": {
      "briefly": "Cookery book - hardback, brown leather cover, height 174 mm.",
      "Identification.BriefDescription": "Cookery book - hardback, brown leather cover, height 174 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1972 (before)",
      "Acquisition.Note": "note dropped in &quot;Mr Mitson, 29 Hartington St., Brierfield&quot;",
      "Identification.Title": "English Housewifery",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "641.5 written in white crayon on front and spine, same written in black ink on front cover and frontispiece",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "English Housewifery exemplified in above four hundred and fifty receipts, giving directions in most parts of cookery by Elizabeth Moxon (14th edition published in 1800)."
    },
    "book17": {
      "briefly": "Hamilton's Vases - hardback, marble cover (very worn) with brown leather spine",
      "Identification.BriefDescription": "Hamilton's Vases - hardback, marble cover (very worn) with brown leather spine",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1972 (before)",
      "Acquisition.Note": "not recorded in Hector Thornton's library catalogue c.1970 but marked as a Towneley library book around 1980.",
      "Identification.Title": "Vases of the late Sir William Hamilton",
      "ConditionCheck.Condition": "fair",
      "ConditionCheck.Note": "738 written in white crayon on spine  and in black ink on title page together with Towneley stamp , both covers loose",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "Greek, Roman and Etruscan vases of the late Sir William Hamilton, contains 62 engravings  by Mr. Kirk. This second edition was published in 1814 with text taken mainly from the work of M. D'Hancarville, who was an associate of Charles Townley (1737-1805)."
    },
    "book18": {
      "briefly": "Venetian opera - hardback, pale blue dust cover, height 285 mm.",
      "Identification.BriefDescription": "Venetian opera - hardback, pale blue dust cover, height 285 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Worsthorne, Simon Towneley, Cliviger",
      "Acquisition.Date": "1954 (around)",
      "Acquisition.Note": "Included in Hector Thornton's library catalogue c.1970 but not recorded in the permanent collection ledger (1932-1972). It was most probably given as a gift in 1955.",
      "Identification.Title": "Venetian Opera in the Seventeenth Century",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Note": "780 in black ink on dust cover, Towneley ink stamp on title page.",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "Venetian Opera in the Seventeenth Century was written by Sir Simon Towneley while he was still a tutor at Worcester College, Oxford in 1953. The book is added to the collection as an example of books written by the Towneley family rather than for the book's specific content, which has no connection with the museum's other collections. (See also books by Katie Grant, a daughter of Sir Simon Towneley)."
    },
    "book19": {
      "briefly": "Lancashire Tales - serial, parts 1 to 14 unbound with red / brown paper cover on most parts",
      "Identification.BriefDescription": "Lancashire Tales - serial, parts 1 to 14 unbound with red / brown paper cover on most parts",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Bourne, Susan (Towneley Hall) (Curator)",
      "Acquisition.Date": "2001",
      "Identification.Title": "Lancashire Stories Part 1 to Part 14",
      "ConditionCheck.Condition": "poor",
      "ConditionCheck.Note": "14 separate parts, part 1 no covers, parts 2-6, 10 and 13 covers loose, part 7 front cover bottom half missing, part 8 back cover lost, part 9 front cover lost, parts 11, 12 and 14 covers intact but very brittle. The illustrated contents are in fair condition.",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "Part 1 first page fold-out (63 cm. wide print of famous Lancastrians)  was displayed in History of Whalley exhibition in 2001. The articles include several relating to the Towneley family. (REF: TAGM_booknote19.pdf)"
    },
    "book20": {
      "briefly": "Clarets Chronicles - hardback, coloured dust cover, height 247 mm. (Subscriber's Copy Number 404, signed by author, glued on fly leaf)",
      "Identification.BriefDescription": "Clarets Chronicles - hardback, coloured dust cover, height 247 mm. (Subscriber's Copy Number 404, signed by author, glued on fly leaf)",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "2007",
      "Acquisition.Organisation": "vendor: Burnley Football Club",
      "Identification.Title": "The Clarets Chronicles - the definitive history of Burnley Football Club 1882-2007",
      "ConditionCheck.Condition": "good",
      "ConditionCheck.Date": "2009.8.4",
      "Content.SummaryText": "details every season from 1882-2007"
    },
    "book21": {
      "briefly": "The Spiritual Combat - hardback, brown leather cover, height 133 mm.",
      "Identification.BriefDescription": "The Spiritual Combat - hardback, brown leather cover, height 133 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Parker, Evelyn Denham",
      "Acquisition.Date": "1972 (before)",
      "Acquisition.Note": "The donor was grand-daughter of Frances, Lady Camoys",
      "Identification.Title": "The Spiritual Combat to which are added The Peace of the Soul, Pious Reflections on death and of Penitence (1801)",
      "ConditionCheck.Condition": "poor",
      "ConditionCheck.Note": "front cover and flyleaf loose, ink shelfmark and Towneley library ink stamps on title page",
      "ConditionCheck.Date": "2009.8.11",
      "Content.SummaryText": "signed on fly leaf Frances Towneley 1821. Frances Towneley (1801-1880) married Thomas Stonor, 3rd Lord Camoys on 25th July 1821."
    },
    "book22": {
      "briefly": "The Life of St. Francis of Sales - hardback, brown leather cover, height 206 mm.",
      "Identification.BriefDescription": "The Life of St. Francis of Sales - hardback, brown leather cover, height 206 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Parker, Evelyn Denham",
      "Acquisition.Date": "1972 (before)",
      "Acquisition.Note": "The donor was grand-daughter of Frances, Lady Camoys",
      "Identification.Title": "The Life of St. Francis of Sales Vol. II by M De Marsollier (1812)",
      "ConditionCheck.Condition": "poor",
      "ConditionCheck.Note": "front cover and flyleaf loose, ink shelfmark and Towneley library ink stamps on title page",
      "ConditionCheck.Date": "2009.8.11",
      "Content.SummaryText": "signed on fly leaf Frances Towneley 1819. Frances Towneley (1801-1880) married Thomas Stonor, 3rd Lord Camoys on 25th July 1821. Inside front cover also has bookplate of Evelyn Denham Parker."
    },
    "book23": {
      "briefly": "Portfolio of Fragments ... relative to the Duchy of Lancaster - hardback, green cover, height 347 mm.",
      "Identification.BriefDescription": "Portfolio of Fragments ... relative to the Duchy of Lancaster - hardback, green cover, height 347 mm.",
      "Identification.ObjectName.simple name": "book",
      "Acquisition.Method": "purchase",
      "Acquisition.Date": "2001",
      "Acquisition.Organisation": "vendor: Rochdale Bookshop, Rochdale",
      "Identification.Title": "Portfolio of Fragments ... relative to the Duchy of Lancaster by M. Gregson (3rd edition by John Harland)"
    }
  },
  "$props": [
    "briefly",
    "image",
    "Identification.BriefDescription",
    "Identification.ObjectName.simple name",
    "Association.Date",
    "Association.Period",
    "Acquisition.Method",
    "Acquisition.Person",
    "Acquisition.Date",
    "Acquisition.Note",
    "Production.Organisation",
    "Acquisition.Organisation",
    "Disposal.Note",
    "$Association.Period",
    "$Acquisition.Person",
    "Identification.ObjectName.other name",
    "Identification.Title",
    "Production.Person",
    "ConditionCheck.Condition",
    "ConditionCheck.Note",
    "ConditionCheck.Date",
    "Content.SummaryText",
    "Description.Note",
    "Description.Condition",
    "Identification.Note",
    "Disposal.Method",
    "Disposal.Organisation",
    "Disposal.Date",
    "Acquisition.ReferenceNumber",
    "Description.Material",
    "Description.Measurement",
    "Association.Note",
    "Conservation.Note",
    "Disposal.ReferenceNumber",
    "Reproduction.Note",
    "Association.Type",
    "Association.Person",
    "Description.Inscription",
    "Production.Date",
    "Production.Period",
    "Rights.Note",
    "$Description.Measurement",
    "Production.Note",
    "Identification.Title.other title",
    "Acquisition.CreditLine",
    "$Production.Person",
    "Production.Place",
    "Description.Completeness",
    "$Description.Note",
    "$Reproduction.Note",
    "$Content.SummaryText",
    "$tags"
  ],
  "$groups": [
    "$Identification",
    "$Association",
    "$Acquisition",
    "$Production",
    "$Disposal",
    "$Reproduction",
    "$ConditionCheck",
    "$Content",
    "$Description",
    "$Conservation",
    "$Rights"
  ],
  "$Identification": [
    "Identification.BriefDescription",
    "Identification.ObjectName.simple name",
    "Identification.ObjectName.other name",
    "Identification.Title",
    "Identification.Note",
    "Identification.Title.other title"
  ],
  "$Association": [
    "Association.Date",
    "Association.Period",
    "$Association.Period",
    "Association.Note",
    "Association.Type",
    "Association.Person"
  ],
  "$Acquisition": [
    "Acquisition.Method",
    "Acquisition.Person",
    "Acquisition.Date",
    "Acquisition.Note",
    "Acquisition.Organisation",
    "$Acquisition.Person",
    "Acquisition.ReferenceNumber",
    "Acquisition.CreditLine"
  ],
  "$Production": [
    "Production.Organisation",
    "Production.Person",
    "Production.Date",
    "Production.Period",
    "Production.Note",
    "$Production.Person",
    "Production.Place"
  ],
  "$Disposal": [
    "Disposal.Note",
    "Disposal.Method",
    "Disposal.Date",
    "Disposal.ReferenceNumber",
    "Disposal.Organisation"
  ],
  "$Reproduction": [
    "Reproduction.Note",
    "$Reproduction.Note"
  ],
  "$ConditionCheck": [
    "ConditionCheck.Condition",
    "ConditionCheck.Note",
    "ConditionCheck.Date"
  ],
  "$Content": [
    "Content.SummaryText",
    "$Content.SummaryText"
  ],
  "$Description": [
    "Description.Note",
    "Description.Condition",
    "Description.Material",
    "Description.Measurement",
    "Description.Inscription",
    "$Description.Measurement",
    "Description.Completeness",
    "$Description.Note"
  ],
  "$Conservation": [
    "Conservation.Note"
  ],
  "$Rights": [
    "Rights.Note"
  ]
};
