var cms_WATCH = {
  "name": "watches collection",
  "edition": "1",
  "date": "29 Sep 2018",
  "objects": {
    "cwj3": {
      "briefly": "Silver single case watch. Plain case hallmarked London 1816. Verge movement with dust cap signed 'Roberts and Sons Dublin' No. 289. White enamel face with Roman hour numerals. Second hand, plain hands, with chain and silver seal attached.",
      "image": "watch/cwj3.jpg",
      "Identification.BriefDescription": "Silver single case watch. Plain case hallmarked London 1816. Verge movement with dust cap signed 'Roberts and Sons Dublin' No. 289. White enamel face with Roman hour numerals. Second hand, plain hands, with chain and silver seal attached.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Kirk, Miss",
      "Acquisition.Date": "1925.6.25",
      "Description.Condition": " (glass scratched, otherwise good)",
      "Description.Measurement": " (: diameter : 2.25&quot;)"
    },
    "cwj5": {
      "briefly": "Solid gold single case keyless watch in presentation case. Signed 'A. A. Appleton, 26 Manchester Road, Burnley'.",
      "image": "watch/cwj5.jpg",
      "Identification.BriefDescription": "Solid gold single case keyless watch in presentation case. Signed 'A. A. Appleton, 26 Manchester Road, Burnley'.",
      "Identification.ObjectName.simple name": "watch and case",
      "Acquisition.Method": "purchase",
      "Acquisition.Person": "vendor: Shop, Pawn (Burnley)",
      "Acquisition.Date": "1931",
      "Description.Condition": " (glass loose)",
      "Identification.Note": "Inscribed on backplate 'County Borough of Burnley presented by the Citizens of Burnley to No. 15067 Private Thomas Whitham, 1st Coldstream Guards as an expression of their most hearty congratulations upon his being awarded the Victoria Cross for bravery on the field of battle on July 31st, 1917. A Macgregor Sinclair, mayor, 6th October 1917.",
      "Description.Measurement": " (: diameter : 2.25&quot;)"
    },
    "cwj6": {
      "briefly": "Silver pair case watch. Plain inner and outer case both hallmarked Birmingham with unidentifiable date letter. Verge movement, unsigned numbered 9725. White enamel face with Roman hour numerals and plain brass hands.",
      "image": "watch/cwj6.jpg",
      "Identification.BriefDescription": "Silver pair case watch. Plain inner and outer case both hallmarked Birmingham with unidentifiable date letter. Verge movement, unsigned numbered 9725. White enamel face with Roman hour numerals and plain brass hands.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Pate, A N, Mr, Burnley",
      "Acquisition.Date": "1937",
      "Identification.Note": "Watch papers of John Owen and Son, Arnlwich; W. Barnett Llangefri; William Barnett, Llangefri",
      "Description.Measurement": " (: diameter : 2.5&quot;)"
    },
    "cwj10": {
      "briefly": "Swiss single case watch. Silver case, engraved with rococo scrolls and flowers. Hallmarked London 1853. Silver engine turned dial with Roman numerals and rococo scrolls and flowers engraved in the centre. Wound through face. Large figure plate. Movement signed 'A. Mabric Frs. Geneve'",
      "image": "watch/cwj10.jpg",
      "Identification.BriefDescription": "Swiss single case watch. Silver case, engraved with rococo scrolls and flowers. Hallmarked London 1853. Silver engine turned dial with Roman numerals and rococo scrolls and flowers engraved in the centre. Wound through face. Large figure plate. Movement signed 'A. Mabric Frs. Geneve'",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Holliday, G (Accrington)",
      "Acquisition.Date": "1948",
      "Description.Measurement": " (: diameter : 1.25&quot;)"
    },
    "cwj13": {
      "briefly": "Silver single case, keyless watch. Plain silver case engraved with escutcheon plate. Hallmarked Chester 1899. Lever escapement with dust cover. White enamel face with Roman hour numerals. Signed J. Graves, Sheffield. Inscribed 'The Express English Lever'. Plain hands.",
      "image": "watch/cwj13.jpg",
      "Identification.BriefDescription": "Silver single case, keyless watch. Plain silver case engraved with escutcheon plate. Hallmarked Chester 1899. Lever escapement with dust cover. White enamel face with Roman hour numerals. Signed J. Graves, Sheffield. Inscribed 'The Express English Lever'. Plain hands.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1970 (before)",
      "Description.Condition": " (second hand missing, engraving worn, glass scratched)",
      "Description.Measurement": " (: diameter : 2&quot;)"
    },
    "cwj14": {
      "briefly": "Silver watch , inner case only. Hallmarked London 1788.White enamelled dial with Roman hour numerals and Arabic minute numerals with polychrome river scene in centre. Movement signed 'Alex Hume, London 9032'. Verge movement. Beetle and poker hands.",
      "image": "watch/cwj14.jpg",
      "Identification.BriefDescription": "Silver watch , inner case only. Hallmarked London 1788.White enamelled dial with Roman hour numerals and Arabic minute numerals with polychrome river scene in centre. Movement signed 'Alex Hume, London 9032'. Verge movement. Beetle and poker hands.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Edwards, J, Mr, Burnley",
      "Acquisition.Date": "1957",
      "Description.Condition": " (face scratched and slightly cracked. Some soldering by hinge.)",
      "Description.Measurement": " (: diameter : 1.75&quot;)",
      "Production.Note": "Alex Hume not in Baillie or Britten"
    },
    "cwj17": {
      "briefly": "Silver pair case watch, inner case hallmarked London 1772. White enamel face with Roman hour numerals and Arabic minute numerals. Movement signed &quot;Geo. Washbourne GLO'ster No. 162'. Watch inscribed on reverse &quot;WC 1773&quot;.",
      "image": "watch/cwj17.jpg",
      "Identification.BriefDescription": "Silver pair case watch, inner case hallmarked London 1772. White enamel face with Roman hour numerals and Arabic minute numerals. Movement signed &quot;Geo. Washbourne GLO'ster No. 162'. Watch inscribed on reverse &quot;WC 1773&quot;.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Coulston, W, Mr, Burnley",
      "Acquisition.Date": "1967",
      "Description.Condition": " (outer case slightly dented, glass scratched.)",
      "Identification.Note": "Watch papers of 'Ben Watts, Cheltenham', 'R. B. Brown, Cheltenham', and 'Skarrat, Kingston'. Modern chain attached.",
      "Description.Measurement": " (: diameter : 2&quot;)"
    },
    "cwj18": {
      "briefly": "Silver single case keyless watch. Case engraved with flowers and scrolls not hall marked. Movement unsigned. White enamel face with pink border and gold flowers. Roman hour numerals, plain hands.",
      "image": "watch/cwj18.jpg",
      "Identification.BriefDescription": "Silver single case keyless watch. Case engraved with flowers and scrolls not hall marked. Movement unsigned. White enamel face with pink border and gold flowers. Roman hour numerals, plain hands.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Date": "1967",
      "Acquisition.Organisation": "acquired from: Messrs Shepherd & Catton, Burnley",
      "Description.Condition": " (slight dent to case, otherwise good)",
      "Description.Measurement": " (: diameter : 1.5&quot;)"
    },
    "cwj19": {
      "briefly": "Small single case keyless watch. Metal case engraved with scrolls and flowers and an escutcheon plate. White enamel face decorated with silver scrolls and gold flowers. Roman hour numerals and plain hands.",
      "image": "watch/cwj19.jpg",
      "Identification.BriefDescription": "Small single case keyless watch. Metal case engraved with scrolls and flowers and an escutcheon plate. White enamel face decorated with silver scrolls and gold flowers. Roman hour numerals and plain hands.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Date": "1967",
      "Acquisition.Organisation": "acquired from: Messrs Shepherd & Catton, Burnley",
      "Description.Condition": "good",
      "Description.Measurement": " (: diameter : 1.5&quot;)"
    },
    "cwj20": {
      "briefly": "Keyless silver single case watch. Case engraved with escutcheon plate. Hallmarked Chester 1881. Dust cap on movement. White enamel face with Roman hour numerals, second hand. Signed on dial 'J. W. Wignall, Burnley'. Perspex 'glass'.",
      "image": "watch/cwj20.jpg",
      "Identification.BriefDescription": "Keyless silver single case watch. Case engraved with escutcheon plate. Hallmarked Chester 1881. Dust cap on movement. White enamel face with Roman hour numerals, second hand. Signed on dial 'J. W. Wignall, Burnley'. Perspex 'glass'.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Coates, William, Mr, Burnley",
      "Acquisition.Date": "1969.7.2",
      "Description.Condition": " (slight dent to case, otherwise good)",
      "Description.Measurement": " (: diameter : 2.5&quot;)"
    },
    "cwj21": {
      "briefly": "Silver pair case watch. Hall mark on both cases London 1782. Enamel face, with Roman numerals and minutes in Arabic numerals with polychrome rural scene painted round edge of dial. Movement inscribed 'J. Barber Winster 441'.",
      "image": "watch/cwj21.jpg",
      "Identification.BriefDescription": "Silver pair case watch. Hall mark on both cases London 1782. Enamel face, with Roman numerals and minutes in Arabic numerals with polychrome rural scene painted round edge of dial. Movement inscribed 'J. Barber Winster 441'.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Mercer, M, Mrs (Wigtown, Northumberland)",
      "Acquisition.Date": "1967",
      "Description.Condition": " (Hands missing, enamel face scratched, outer case damaged and mended with solder, glass missing.)",
      "Identification.Note": "Two cloth watch papers and one watch paper of H. Blakeborough, Burnley.",
      "Description.Measurement": " (: diameter : 2&quot;)",
      "Production.Note": "J. Barber Winster not in Bailie or Britten. There is a long case clock by J. Barber Winster in Abbot Hall, Kendal."
    },
    "cwj22": {
      "briefly": "Silver single case watch. Plain case hallmarked Birmingham 1800. No glass, silver cover instead. Wound through face. Verge movement signed 'Chas. Norman London No. 83175'. White enamel face with Arabic hour numerals. Plain gold hand.",
      "image": "watch/cwj22.jpg",
      "Identification.BriefDescription": "Silver single case watch. Plain case hallmarked Birmingham 1800. No glass, silver cover instead. Wound through face. Verge movement signed 'Chas. Norman London No. 83175'. White enamel face with Arabic hour numerals. Plain gold hand.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Feboral, Mr (Burnley)",
      "Acquisition.Date": "1970 (before)",
      "Description.Condition": " (Case slightly dented. Face cracked and chipped. One hand missing, the other bent.)",
      "Description.Measurement": " (: diameter : 2&quot;)"
    },
    "cwj23": {
      "briefly": "Keyless single case watch. Silver case hallmarked Chester 1875. Engraved with escutcheon plate. White enamel face with Roman hour numerals. Second hand, plain hands. Dust cover over movement.",
      "image": "watch/cwj23.jpg",
      "Identification.BriefDescription": "Keyless single case watch. Silver case hallmarked Chester 1875. Engraved with escutcheon plate. White enamel face with Roman hour numerals. Second hand, plain hands. Dust cover over movement.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Duckworth, E, Mr, Fleetwood",
      "Acquisition.Date": "1967",
      "Description.Condition": " (engraving worn, slight crack on face.)",
      "Description.Measurement": " (: diameter : 2.5&quot;)"
    },
    "cwj24": {
      "briefly": "Silver single case watch. Case engraved with geometric pattern. Continental type balance bridge. White enamel face with Arabic hour numerals and visible mechanism. Plain hands.",
      "image": "watch/cwj24.jpg",
      "Identification.BriefDescription": "Silver single case watch. Case engraved with geometric pattern. Continental type balance bridge. White enamel face with Arabic hour numerals and visible mechanism. Plain hands.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1970 (before)",
      "Description.Condition": " (glass missing otherwise good)",
      "Description.Measurement": " (: diameter : 2.25&quot;)"
    },
    "cwj25": {
      "briefly": "Silver pair case watch. Plain inner and outer cases hallmarked London 1821. Verge movement with dustcap. Signed 'Harrison Liverpool N0. 5937'. White enamel face with Roman numerals. Plain hand (one missing).",
      "image": "watch/cwj25.jpg",
      "Identification.BriefDescription": "Silver pair case watch. Plain inner and outer cases hallmarked London 1821. Verge movement with dustcap. Signed 'Harrison Liverpool N0. 5937'. White enamel face with Roman numerals. Plain hand (one missing).",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1970 (before)",
      "Description.Condition": " (Hand missing, glass missing, face cracked and chipped. Slight denting in outer case.)",
      "Description.Measurement": " (: diameter : 2.75&quot;)"
    },
    "cwj26": {
      "briefly": "Gilded brass pair case watch. Inner and outer case plain. White enamel face with plain hands and Roman hour numerals. Verge movement signed 'Danes New Bond Street, London 1935'.",
      "image": "watch/cwj26.jpg",
      "Identification.BriefDescription": "Gilded brass pair case watch. Inner and outer case plain. White enamel face with plain hands and Roman hour numerals. Verge movement signed 'Danes New Bond Street, London 1935'.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1970 (before)",
      "Description.Condition": " (Gilding worn otherwise good)",
      "Identification.Note": "Watch papers of William Barnet, Llangefai; John Owen and Son Amlwich; John Brownbill, Prussian Street, Liverpool.",
      "Description.Measurement": " (: diameter : 2&quot;)"
    },
    "cwj27": {
      "briefly": "Single case silver gilt watch. Verge movement signed 'Rich Young Newcastle No. 201'. No hallmark on case. Case engraved with lattice work and pattern. Gold dial with raised Roman hour numerals and impressed decoration. Plain gold hands. Face inscribed 'Bull King and Co. London Swiss Made' (Marriage?)",
      "image": "watch/cwj27.jpg",
      "Identification.BriefDescription": "Single case silver gilt watch. Verge movement signed 'Rich Young Newcastle No. 201'. No hallmark on case. Case engraved with lattice work and pattern. Gold dial with raised Roman hour numerals and impressed decoration. Plain gold hands. Face inscribed 'Bull King and Co. London Swiss Made' (Marriage?)",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1970 (before)",
      "Description.Condition": " (poor, face and case, glass glued in.)",
      "Description.Measurement": " (: diameter : 2&quot;)",
      "Production.Note": "Richard Young clock and watch maker Newcastle b. 1773 d. 1815"
    },
    "cwj28": {
      "briefly": "Silver single case watch. Engine turned case with engraved escutcheon plate surrounded by strap.. Hallmarked Birmingham 1873. English lever movement with dust cap. No. 3647 unsigned. Silver engine turned face with raised Roman hour numerals and floral motifs, with engraved acanthus design in centre. Second hand.",
      "image": "watch/cwj28.jpg",
      "Identification.BriefDescription": "Silver single case watch. Engine turned case with engraved escutcheon plate surrounded by strap.. Hallmarked Birmingham 1873. English lever movement with dust cap. No. 3647 unsigned. Silver engine turned face with raised Roman hour numerals and floral motifs, with engraved acanthus design in centre. Second hand.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1970 (before)",
      "Description.Measurement": " (: diameter : 2.25&quot;)"
    },
    "cwj29": {
      "briefly": "Gilded brass single case watch. Case dark blue enamel over engine turning surrounded by pale blue border. White enamel face with Arabic numerals. Arrow shaped gold hands, wound through face. Verge movement signed 'Wightwick and Moss, Ludgate Street, London 2988'.",
      "image": "watch/cwj29.jpg",
      "Identification.BriefDescription": "Gilded brass single case watch. Case dark blue enamel over engine turning surrounded by pale blue border. White enamel face with Arabic numerals. Arrow shaped gold hands, wound through face. Verge movement signed 'Wightwick and Moss, Ludgate Street, London 2988'.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1970 (before)",
      "Description.Condition": " (enamel on reverse badly chipped, gold plate worn.)",
      "Description.Measurement": " (: diameter : 2&quot;)",
      "Production.Note": "Wightwick and Moss 1799-1836"
    },
    "cwj30": {
      "briefly": "Silver single case keyless watch. White enamel face with Roman numerals and second hand. Movement signed 'Jno. H. Scott, Burnley. Patent Lever No. 133'. Lever movement with dust cap. Simple brass beetle and poker hands. Case hallmarked London 1835",
      "image": "watch/cwj30.jpg",
      "Identification.BriefDescription": "Silver single case keyless watch. White enamel face with Roman numerals and second hand. Movement signed 'Jno. H. Scott, Burnley. Patent Lever No. 133'. Lever movement with dust cap. Simple brass beetle and poker hands. Case hallmarked London 1835",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1970 (before)",
      "Description.Condition": " (Engraving on case worn, glass cracked.)",
      "Description.Measurement": " (: diameter : 2&quot;)"
    },
    "cwj31": {
      "briefly": "Keyless single case silver watch. Engine turned case with engraved escutcheon plate. Hallmarked Birmingham 1919. White enamel face with Roman hour numerals. A second hand and plain gold hands.",
      "image": "watch/cwj31.jpg",
      "Identification.BriefDescription": "Keyless single case silver watch. Engine turned case with engraved escutcheon plate. Hallmarked Birmingham 1919. White enamel face with Roman hour numerals. A second hand and plain gold hands.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Law, Mr (Burnley)",
      "Acquisition.Date": "1970",
      "Acquisition.Note": "The watch was the property of donor's father-in-law, the late Mr J E Rawlinson.",
      "Description.Measurement": " (: diameter : 2&quot;)"
    },
    "cwj32": {
      "briefly": "Silver single case watch. Plain case. Hallmarked London 1848. Engine turned silver face with floral engraving and gold Roman numerals and a second hand. Dust cap over cover.",
      "image": "watch/cwj32.jpg",
      "Identification.BriefDescription": "Silver single case watch. Plain case. Hallmarked London 1848. Engine turned silver face with floral engraving and gold Roman numerals and a second hand. Dust cap over cover.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Law, Mr (Burnley)",
      "Acquisition.Date": "1970",
      "Acquisition.Note": "The watch was the property of donor's father-in-law, the late Mr J E Rawlinson.",
      "Description.Condition": " (Face slightly scratched, glass broken)",
      "Description.Measurement": " (: diameter : 2&quot;)"
    },
    "cwj33": {
      "briefly": "&quot;Sunwatch&quot; and instruction booklet. Rectangular brass box containing sundial, compass and table of latitudes (c. 1922)",
      "image": "watch/cwj33.jpg",
      "Identification.BriefDescription": "&quot;Sunwatch&quot; and instruction booklet. Rectangular brass box containing sundial, compass and table of latitudes (c. 1922)",
      "Identification.ObjectName.simple name": "sundial",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Nuttall, Mr (Clitheroe)",
      "Acquisition.Date": "1970",
      "Description.Measurement": " (: depth x width  : 3&quot; x 2&quot;)"
    },
    "cwj34": {
      "briefly": "French silver single case watch, wound through dial. Verge movement, large figure plate. White enamel dial with Roman hour numerals and Arabic minute numerals. Movement signed &quot;Chambon Fils A Paris No. 994&quot;",
      "image": "watch/cwj34.jpg",
      "Identification.BriefDescription": "French silver single case watch, wound through dial. Verge movement, large figure plate. White enamel dial with Roman hour numerals and Arabic minute numerals. Movement signed &quot;Chambon Fils A Paris No. 994&quot;",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Watson, R C, Mr (Arnside, Lancashire)",
      "Acquisition.Date": "1973",
      "Description.Condition": " (face chipped, glass broken)",
      "Description.Measurement": " (: diameter : 1.75&quot;)"
    },
    "cwj35a": {
      "briefly": "Keyless gold fob watch. White enamel dial with Roman numerals and seconds dial inscribed &quot;Thos. Russell &amp; Sons. Liverpool. Tempus Fugit. Swiss Made&quot;",
      "image": "watch/cwj35a.jpg",
      "Identification.BriefDescription": "Keyless gold fob watch. White enamel dial with Roman numerals and seconds dial inscribed &quot;Thos. Russell &amp; Sons. Liverpool. Tempus Fugit. Swiss Made&quot;",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Simpson, Linda, Mrs, Burnley",
      "Acquisition.Date": "1975",
      "Acquisition.Note": "The watch was the property of donor's late husband.",
      "Description.Measurement": " (: diameter : 2&quot;)"
    },
    "cwj35b": {
      "briefly": "9ct rose gold double watch albert with medallion",
      "image": "watch/cwj35b.jpg",
      "Identification.BriefDescription": "9ct rose gold double watch albert with medallion",
      "Identification.ObjectName.simple name": "watch chain",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Simpson, Linda, Mrs, Burnley",
      "Acquisition.Date": "1975",
      "Acquisition.Note": "The watch chain was the property of donor's late husband and the medallion belonged to his uncle.",
      "Identification.Note": "medallion inscribed &quot;Captain Burnley Swimming Club 1891&quot;",
      "Description.Measurement": " (: weight : 49gm.)"
    },
    "cwj36": {
      "briefly": "a. A silver cased fob watch, signed H. Midgley Rochdale with cartouche engraved on back. Enamel face with seconds dial. Case hallmarked Chester 1901 b. Gold watch chain with two watch keys",
      "image": "watch/cwj36.jpg",
      "Identification.BriefDescription": "a. A silver cased fob watch, signed H. Midgley Rochdale with cartouche engraved on back. Enamel face with seconds dial. Case hallmarked Chester 1901 b. Gold watch chain with two watch keys",
      "Identification.ObjectName.simple name": "watch and chain",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1970 (before)",
      "Description.Note": "chain : length (extended) : 15&quot;",
      "Description.Condition": " (Good, case slightly worn, second hand missing)",
      "Description.Measurement": " (watch : diameter : 3&quot;)"
    },
    "cwj37": {
      "briefly": "Silver cased fob watch. Not signed. Enamel face. Engine turned case with cartouche engraved on back. Hallmarked London 1872",
      "image": "watch/cwj37.jpg",
      "Identification.BriefDescription": "Silver cased fob watch. Not signed. Enamel face. Engine turned case with cartouche engraved on back. Hallmarked London 1872",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "1970 (before)",
      "Description.Condition": " (case very worn, enamel face chipped, opening mechanism jammed.)",
      "Description.Measurement": " (: diameter : 2.75&quot;)"
    },
    "cwj38": {
      "briefly": "18 carat gold cased keyless fob watch. Engraved on back 'CMF' for C. M. Foden. Enamel face, dial signed Waltham.",
      "image": "watch/cwj38.jpg",
      "Identification.BriefDescription": "18 carat gold cased keyless fob watch. Engraved on back 'CMF' for C. M. Foden. Enamel face, dial signed Waltham.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1972.11.14",
      "Acquisition.Note": "transferred from Burnley Central Library, having been presented to the Library by Mrs Kate Foden. This 18 carat gold watch was presented to C. M. Foden JP in recognition of long and faithful service as Honorary Secretary to the Mechanics' Institution by teachers and students, 1901. Presented to the Library by the late Mrs. Kate Foden. Mr C. M. Foden JP was Honorary Secretary to the Mechanics' Institute from 1868 to 1918. He supported the first W.E.A. class in Burnley in 1912, and was appointed Chairman of the Public Library in November, 1912. [1972.113.13]",
      "Acquisition.Organisation": "acquired from: Burnley Central Library",
      "Description.Condition": " (Good condition but glass (plastic) loose and back cannot be opened. Small crack and chip on enamel face at position 3.)",
      "Description.Measurement": " (: diameter : 3&quot;)"
    },
    "cwj39": {
      "briefly": "White metal with copper pendant. Pendant reads: &quot;Burnley &amp; Dist. Sunday Schools Methodist Union Celebrations 1932.&quot; Image of John Wesley on reverse.",
      "image": "watch/cwj39.jpg",
      "Identification.BriefDescription": "White metal with copper pendant. Pendant reads: &quot;Burnley &amp; Dist. Sunday Schools Methodist Union Celebrations 1932.&quot; Image of John Wesley on reverse.",
      "Identification.ObjectName.simple name": "watch chain",
      "Acquisition.Method": "untraced find",
      "Acquisition.Date": "2008 (before)",
      "Acquisition.Note": "found in Hall, 2007 together with &quot;lost property&quot; fob watch [day book entry 1979.22.1] not added to permanent collection.",
      "Description.Measurement": " (: length (extended) : 11.5&quot;)"
    },
    "cwj201": {
      "briefly": "Verge watch movement with enamel face with Roman numerals. Inscribed &quot;Thos. Brooks, London No.24&quot;",
      "image": "watch/cwj201.jpg",
      "Identification.BriefDescription": "Verge watch movement with enamel face with Roman numerals. Inscribed &quot;Thos. Brooks, London No.24&quot;",
      "Identification.ObjectName.simple name": "watch movement",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Measurement": " (: diameter : 1.5&quot;)",
      "Production.Note": "There are a number of watchmakers named 'Thomas Brooks' listed in Bailie"
    },
    "cwj202": {
      "briefly": "Watch movement, brass with enamel dial with Roman and Arabic numerals. Inscribed &quot;R. Williamson, London 6472&quot;",
      "image": "watch/cwj202.jpg",
      "Identification.BriefDescription": "Watch movement, brass with enamel dial with Roman and Arabic numerals. Inscribed &quot;R. Williamson, London 6472&quot;",
      "Identification.ObjectName.simple name": "watch movement",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Production.Person": "watchmaker: Williamson, Robert",
      "Description.Condition": " (face cracked and chipped)",
      "Description.Measurement": " (: diameter : 1.5&quot;)",
      "Production.Note": "Apprenticed 1658, Clockmakers Company 1666, Master of Clockmakers Company 1698-1714",
      "Production.Place": "+&lt;PlaceName&gt;London (near Royal Exchange)&lt;/PlaceName&gt;"
    },
    "cwj203": {
      "briefly": "Plain silver inner and outer case of pair case, inner case marked London 1751, outer case not marked. Watch papers of Thomas Parry Stoke-on-Trent (4)",
      "image": "watch/cwj203.jpg",
      "Identification.BriefDescription": "Plain silver inner and outer case of pair case, inner case marked London 1751, outer case not marked. Watch papers of Thomas Parry Stoke-on-Trent (4)",
      "Identification.ObjectName.simple name": "watch case",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Identification.ObjectName.other name": "pair case",
      "Description.Measurement": " (: diameter : 2.25&quot;)"
    },
    "cwj204": {
      "briefly": "&quot;Dutch forgery watch&quot; Dutch pair case watch. Plain silver inner case hallmarked London 1776. Silver and tortoiseshell pique outer case, the tortoiseshell painted underneath with fernlike designs. White enamel face with Roman hour numerals and Arabic minute numerals and arcaded minute hand, pierced brass hands. Continental type balance bridge movement signed 'Wm. Crayton, London 4981'.",
      "image": "watch/cwj204.jpg",
      "Identification.BriefDescription": "&quot;Dutch forgery watch&quot; Dutch pair case watch. Plain silver inner case hallmarked London 1776. Silver and tortoiseshell pique outer case, the tortoiseshell painted underneath with fernlike designs. White enamel face with Roman hour numerals and Arabic minute numerals and arcaded minute hand, pierced brass hands. Continental type balance bridge movement signed 'Wm. Crayton, London 4981'.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Condition": " (face scratched, some tortoiseshell missing)",
      "Description.Measurement": " (: diameter : 1.75&quot;)",
      "Production.Note": "Because of the supremacy of English watch making in the 18th century, a number of continental watches were signed with English sounding names. William Crayton is found on many Dutch watches, see T. P. Camerer Cuss 'Early Watches' The Country Life Book of Watches p.41 (Country Life, 1967)"
    },
    "cwj205": {
      "briefly": "&quot;Dutch forgery watch&quot; Dutch silver watch, plain inner case only, hallmarked London 1776. Verge movement with continental type balance bridge. Signed 'Tarts, London 8401'. White enamel face with Roman hour numerals and Arabic date numerals and arcaded minute ring. Pierced brass hands.",
      "image": "watch/cwj205.jpg",
      "Identification.BriefDescription": "&quot;Dutch forgery watch&quot; Dutch silver watch, plain inner case only, hallmarked London 1776. Verge movement with continental type balance bridge. Signed 'Tarts, London 8401'. White enamel face with Roman hour numerals and Arabic date numerals and arcaded minute ring. Pierced brass hands.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Condition": " (face badly chipped and cracked, glass scratched)",
      "Description.Measurement": " (: diameter : 1.75&quot;)",
      "Production.Note": "Because of the supremacy of English watch making in the 18th century, a number of continental watches were signed with English sounding names. 'Tarts' is found on many Dutch watches, see T. P. Camerer Cuss 'Early Watches' The Country Life Book of Watches p.41 (Country Life, 1967)"
    },
    "cwj206": {
      "briefly": "&quot;Dutch forgery watch&quot; Silver watch with inner case only. No hallmark. White enamel face. Roman hour numerals Arabic minute numerals. Pierced brass hands. Signed on face &quot;Worke, London.&quot; Verge movement continental type balance bridge movement signed 'Worke London 200'.",
      "image": "watch/cwj206.jpg",
      "Identification.BriefDescription": "&quot;Dutch forgery watch&quot; Silver watch with inner case only. No hallmark. White enamel face. Roman hour numerals Arabic minute numerals. Pierced brass hands. Signed on face &quot;Worke, London.&quot; Verge movement continental type balance bridge movement signed 'Worke London 200'.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Condition": " (face scratched otherwise good)",
      "Description.Measurement": " (: diameter : 1.5&quot;)",
      "Production.Note": "Because of the supremacy of English watch making in the 18th century, a number of continental watches were signed with English sounding names. Lack of a Christian name is an indication, see T. P. Camerer Cuss 'Early Watches' The Country Life Book of Watches p.41 (Country Life, 1967)"
    },
    "cwj207": {
      "briefly": "brass movement: No face Watch cock missing. Inscribed &quot;Geo. Rawlins, London 1779&quot;.",
      "image": "watch/cwj207.jpg",
      "Identification.BriefDescription": "brass movement: No face Watch cock missing. Inscribed &quot;Geo. Rawlins, London 1779&quot;.",
      "Identification.ObjectName.simple name": "watch movement",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Measurement": " (: diameter : 1.25&quot;)",
      "Production.Note": "Geo. Rawlins not in Britten or Baillie"
    },
    "cwj208": {
      "briefly": "Silver pair case watch inner and outer cases hallmarked London 1780. Both cases plain. White enamel face with Roman hour numerals. Plain hands. Verge movement signed 'Robt. Stroud, London RF 16925'.",
      "image": "watch/cwj208.jpg",
      "Identification.BriefDescription": "Silver pair case watch inner and outer cases hallmarked London 1780. Both cases plain. White enamel face with Roman hour numerals. Plain hands. Verge movement signed 'Robt. Stroud, London RF 16925'.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Condition": " (face cracked and chipped)",
      "Identification.Note": "Watch papers of Healy, Patricroft; P. Whittaker, Rawtenstall; J. M. Blakeborough, Burnley; W. Collinge, Cheapside, Burnley.",
      "Description.Measurement": " (: diameter : 2&quot;)",
      "Production.Note": "Robert Stroud, London, active before 1775-1822"
    },
    "cwj209": {
      "briefly": "Turkish market watch. Outer case silver with engraved border. Inner case plain silver. Both hallmarked London 1784. White enamel dial with Turkish numerals signed 'George Prior London'. Verge movement signed 'Geo. Charle, London, No. 7010. Figure plate with Turkish numerals.",
      "image": "watch/cwj209.jpg",
      "Identification.BriefDescription": "Turkish market watch. Outer case silver with engraved border. Inner case plain silver. Both hallmarked London 1784. White enamel dial with Turkish numerals signed 'George Prior London'. Verge movement signed 'Geo. Charle, London, No. 7010. Figure plate with Turkish numerals.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Production.Person": "watchmaker: Prior, George",
      "Description.Condition": " (glass missing, face cracked, inner case hinge broken and repaired with solder.)",
      "Description.Measurement": " (: diameter : 2.25&quot;)",
      "Production.Note": "At the end of the 18th century, demand for watches for the Turkish market was so great that James Prior bought movements from other makers and fitted them with cases specially designed for the Turkish market and painted 'James Prior' on the dial. See Kenneth Ullyet - Watch Collecting p. 74(Frederick Miller, 1970). George Charle also made Turkish market watches. See T. P. Cameron Cuss - The Country Life Book of Watches p.62 illustration (Country Life, 1967). The Ashmolean Museum also has a Turkish market watch by Geo. Charle. Turkish market watches usually had an elaborate third case - possibly this is missing for cwj209.",
      "Production.Place": "+&lt;PlaceName&gt;Prescot Street, London&lt;/PlaceName&gt;"
    },
    "cwj210": {
      "briefly": "Silver pair case watch inner and outer case hallmarked London 1787. Case inscribed on reverse &quot;W. Rose&quot;. White enamel face with hour numerals in Roman and minute numbers in Arabic numerals. Signed on face 'Andrew St. Austle', signed on movement 'Ben Andrews St. Austle 10056'. Verge movement. Plain brass hands.",
      "image": "watch/cwj210.jpg",
      "Identification.BriefDescription": "Silver pair case watch inner and outer case hallmarked London 1787. Case inscribed on reverse &quot;W. Rose&quot;. White enamel face with hour numerals in Roman and minute numbers in Arabic numerals. Signed on face 'Andrew St. Austle', signed on movement 'Ben Andrews St. Austle 10056'. Verge movement. Plain brass hands.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Condition": " (face cracked, glass scratched, catch missing off case)",
      "Identification.Note": "Watch paper of C. Dietschey, Devonport",
      "Description.Measurement": " (: diameter : 2&quot;)"
    },
    "cwj211": {
      "briefly": "Silver watch, no outer case. Hallmarked London 1788. White enamel face with Roman hour numerals and Arabic minute numerals. Verge movement well decorated. Signed 'B. Duhamet, London 878'.",
      "image": "watch/cwj211.jpg",
      "Identification.BriefDescription": "Silver watch, no outer case. Hallmarked London 1788. White enamel face with Roman hour numerals and Arabic minute numerals. Verge movement well decorated. Signed 'B. Duhamet, London 878'.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Condition": " (repair at juncture of pendant and watch.)",
      "Description.Measurement": " (: diameter : 1.75&quot;)",
      "Production.Note": "Duhamet not in Baillie or Britten"
    },
    "cwj212": {
      "briefly": "Brass watch movement with enamel face, with Roman and Arabic numerals. Inscribed &quot;J. Perrins, Strand, London 944&quot;.",
      "image": "watch/cwj212.jpg",
      "Identification.BriefDescription": "Brass watch movement with enamel face, with Roman and Arabic numerals. Inscribed &quot;J. Perrins, Strand, London 944&quot;.",
      "Identification.ObjectName.simple name": "watch movement",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Condition": " (face slightly cracked)",
      "Description.Measurement": " (: diameter : 1.5&quot;)",
      "Production.Note": "J. Perrins not in Britten or Bailie"
    },
    "cwj213": {
      "briefly": "Gilded brass pair case watch with plain inner case and tortoiseshell pique outer case. White enamel face with Roman and Arabic numerals. Verge movement signed 'Chas Leignes, London No. 544' pierced brass hands",
      "image": "watch/cwj213.jpg",
      "Identification.BriefDescription": "Gilded brass pair case watch with plain inner case and tortoiseshell pique outer case. White enamel face with Roman and Arabic numerals. Verge movement signed 'Chas Leignes, London No. 544' pierced brass hands",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Production.Person": "watchmaker: Leignes, Charles Peter",
      "Description.Condition": " (part of tortoiseshell cover missing, face cracked and repaired. Gold plating worn. Knob missing from catch on outer case; inner case loose : possibly a marriage.)",
      "Identification.Note": "Maroon silk watch paper",
      "Description.Measurement": " (: diameter : 2&quot;)",
      "Production.Note": "was apprenticed 1741, Clockmakers' Company 1749-1796",
      "Production.Place": "+&lt;PlaceName&gt;London&lt;/PlaceName&gt;"
    },
    "cwj214": {
      "briefly": "Brass watch movement Inscribed &quot;Jno Taylor. London 3427&quot;",
      "image": "watch/cwj214.jpg",
      "Identification.BriefDescription": "Brass watch movement Inscribed &quot;Jno Taylor. London 3427&quot;",
      "Identification.ObjectName.simple name": "watch movement",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Measurement": " (: diameter : 1.25&quot;)"
    },
    "cwj215": {
      "briefly": "Brass watch movement. Inscribed &quot;Higgs and Evans London 5565&quot;",
      "image": "watch/cwj215.jpg",
      "Identification.BriefDescription": "Brass watch movement. Inscribed &quot;Higgs and Evans London 5565&quot;",
      "Identification.ObjectName.simple name": "watch movement",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Production.Organisation": "manufacturer: Higgs and Evans, London",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Condition": " (face scratched otherwise good)",
      "Description.Measurement": " (: diameter : 1.25&quot;)",
      "Production.Note": "active 1775-1825",
      "Production.Place": "+&lt;PlaceName&gt;Sweetings Alley, London (later Royal Exchange, London)&lt;/PlaceName&gt;"
    },
    "cwj216": {
      "briefly": "Verge watch movement signed &quot;Grayhurst, London No. 913&quot;",
      "image": "watch/cwj216.jpg",
      "Identification.BriefDescription": "Verge watch movement signed &quot;Grayhurst, London No. 913&quot;",
      "Identification.ObjectName.simple name": "watch movement",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Production.Person": "watchmaker: Grayhurst, James",
      "Description.Measurement": " (: diameter : 1.75&quot;)",
      "Production.Note": "Guildhall Museum has a watch by him dated 1805",
      "Production.Place": "+&lt;PlaceName&gt;Strand, London&lt;/PlaceName&gt;"
    },
    "cwj217": {
      "briefly": "Silver outer watch case. Hallmarked London 1816,",
      "image": "watch/cwj217.jpg",
      "Identification.BriefDescription": "Silver outer watch case. Hallmarked London 1816,",
      "Identification.ObjectName.simple name": "watch case",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Condition": " (slight denting on reverse of case)",
      "Identification.Note": "3 silk watch papers and one watch paper printed 'DRAB'",
      "Description.Measurement": " (: diameter : 2.5&quot;)"
    },
    "cwj218": {
      "briefly": "Brass watch movement, white enamel face with Arabic numerals. Inscribed &quot;H. Jefferys, Fleet Street, London No. 989&quot;",
      "image": "watch/cwj218.jpg",
      "Identification.BriefDescription": "Brass watch movement, white enamel face with Arabic numerals. Inscribed &quot;H. Jefferys, Fleet Street, London No. 989&quot;",
      "Identification.ObjectName.simple name": "watch movement",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Production.Person": "watchmaker: Jeffrys, Henry",
      "Description.Measurement": " (: diameter : 1.5&quot;)",
      "Production.Note": "Salisbury Square, London (1799) &amp; Fleet Street, London (1804-1829)",
      "Production.Place": "+&lt;PlaceName&gt;London&lt;/PlaceName&gt;"
    },
    "cwj219": {
      "briefly": "One silver repoussé watch case with rococo design and Roman figures.",
      "image": "watch/cwj219.jpg",
      "Identification.BriefDescription": "One silver repoussé watch case with rococo design and Roman figures.",
      "Identification.ObjectName.simple name": "watch case",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Condition": " (case slightly dented and worn and split by hinge)",
      "Identification.Note": "with two cloth watch papers, one embroidered with date 1839",
      "Description.Measurement": " (: diameter : 2&quot;)"
    },
    "cwj220": {
      "briefly": "French silver pair case watch. Plain inner case, outer case engraved with an urn. White enamel face Roman hour numerals Arabic minute numerals signed 'Isaac Loret et fils' Verge movement signed 'Isaac Loret and Fils, 273' Beetle and poker hands.",
      "image": "watch/cwj220.jpg",
      "Identification.BriefDescription": "French silver pair case watch. Plain inner case, outer case engraved with an urn. White enamel face Roman hour numerals Arabic minute numerals signed 'Isaac Loret et fils' Verge movement signed 'Isaac Loret and Fils, 273' Beetle and poker hands.",
      "Identification.ObjectName.simple name": "watch",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Condition": " (hands loose, otherwise good)",
      "Description.Measurement": " (: diameter : 1.75&quot;)"
    },
    "cwj221": {
      "briefly": "Watch case gilded brass and shagreen and shagreen and pique",
      "image": "watch/cwj221.jpg",
      "Identification.BriefDescription": "Watch case gilded brass and shagreen and shagreen and pique",
      "Identification.ObjectName.simple name": "watch case",
      "Acquisition.Method": "transfer",
      "Acquisition.Date": "1916",
      "Acquisition.Organisation": "acquired from: Victoria and Albert Museum, London (via Trustees)",
      "Description.Note": "shagreen and gold plating worn",
      "Description.Condition": "fair",
      "Identification.Note": "blue silk watchpaper",
      "Description.Measurement": " (: diameter : 2&quot;)"
    }
  },
  "$props": [
    "briefly",
    "image",
    "Identification.BriefDescription",
    "Identification.ObjectName.simple name",
    "Association.Date",
    "Association.Period",
    "Acquisition.Method",
    "Acquisition.Person",
    "Acquisition.Date",
    "Acquisition.Note",
    "Production.Organisation",
    "Acquisition.Organisation",
    "Disposal.Note",
    "$Association.Period",
    "$Acquisition.Person",
    "Identification.ObjectName.other name",
    "Identification.Title",
    "Production.Person",
    "ConditionCheck.Condition",
    "ConditionCheck.Note",
    "ConditionCheck.Date",
    "Content.SummaryText",
    "Description.Note",
    "Description.Condition",
    "Identification.Note",
    "Disposal.Method",
    "Disposal.Organisation",
    "Disposal.Date",
    "Acquisition.ReferenceNumber",
    "Description.Material",
    "Description.Measurement",
    "Association.Note",
    "Conservation.Note",
    "Disposal.ReferenceNumber",
    "Reproduction.Note",
    "Association.Type",
    "Association.Person",
    "Description.Inscription",
    "Production.Date",
    "Production.Period",
    "Rights.Note",
    "$Description.Measurement",
    "Production.Note",
    "Identification.Title.other title",
    "Acquisition.CreditLine",
    "$Production.Person",
    "Production.Place",
    "Description.Completeness",
    "$Description.Note",
    "$Reproduction.Note",
    "$Content.SummaryText",
    "$tags"
  ],
  "$groups": [
    "$Identification",
    "$Association",
    "$Acquisition",
    "$Production",
    "$Disposal",
    "$Reproduction",
    "$ConditionCheck",
    "$Content",
    "$Description",
    "$Conservation",
    "$Rights"
  ],
  "$Identification": [
    "Identification.BriefDescription",
    "Identification.ObjectName.simple name",
    "Identification.ObjectName.other name",
    "Identification.Title",
    "Identification.Note",
    "Identification.Title.other title"
  ],
  "$Association": [
    "Association.Date",
    "Association.Period",
    "$Association.Period",
    "Association.Note",
    "Association.Type",
    "Association.Person"
  ],
  "$Acquisition": [
    "Acquisition.Method",
    "Acquisition.Person",
    "Acquisition.Date",
    "Acquisition.Note",
    "Acquisition.Organisation",
    "$Acquisition.Person",
    "Acquisition.ReferenceNumber",
    "Acquisition.CreditLine"
  ],
  "$Production": [
    "Production.Organisation",
    "Production.Person",
    "Production.Date",
    "Production.Period",
    "Production.Note",
    "$Production.Person",
    "Production.Place"
  ],
  "$Disposal": [
    "Disposal.Note",
    "Disposal.Method",
    "Disposal.Date",
    "Disposal.ReferenceNumber",
    "Disposal.Organisation"
  ],
  "$Reproduction": [
    "Reproduction.Note",
    "$Reproduction.Note"
  ],
  "$ConditionCheck": [
    "ConditionCheck.Condition",
    "ConditionCheck.Note",
    "ConditionCheck.Date"
  ],
  "$Content": [
    "Content.SummaryText",
    "$Content.SummaryText"
  ],
  "$Description": [
    "Description.Note",
    "Description.Condition",
    "Description.Material",
    "Description.Measurement",
    "Description.Inscription",
    "$Description.Measurement",
    "Description.Completeness",
    "$Description.Note"
  ],
  "$Conservation": [
    "Conservation.Note"
  ],
  "$Rights": [
    "Rights.Note"
  ]
};
