var cms_POTT = {
  "name": "ceramic tiles collection",
  "edition": "1",
  "date": "29 Sep 2018",
  "objects": {
    "po166.1-48": {
      "briefly": "Blue glazed majolica tiles with embossed leaf design. RD No. 397442 (1902).",
      "image": "pott/po166.1-48.jpg",
      "Identification.BriefDescription": "Blue glazed majolica tiles with embossed leaf design. RD No. 397442 (1902).",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po167.1-10": {
      "briefly": "Maroon glazed majolica tiles with embossed Art Nouveau tulip design. Three or more tiles making a panel.",
      "image": "pott/po167.1-10.jpg",
      "Identification.BriefDescription": "Maroon glazed majolica tiles with embossed Art Nouveau tulip design. Three or more tiles making a panel.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po168": {
      "briefly": "Blue glazed majolica tile with embossed geometric and floral design. RD No. 402548. (1903).",
      "image": "pott/po168.jpg",
      "Identification.BriefDescription": "Blue glazed majolica tile with embossed geometric and floral design. RD No. 402548. (1903).",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po169": {
      "briefly": "Green and brown glazed majolica tile with embossed geometric and floral design. (same design as po168)",
      "image": "pott/po169.jpg",
      "Identification.BriefDescription": "Green and brown glazed majolica tile with embossed geometric and floral design. (same design as po168)",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po170": {
      "briefly": "Pink, green and brown glazed majolica tile with floral embossed design.",
      "image": "pott/po170.jpg",
      "Identification.BriefDescription": "Pink, green and brown glazed majolica tile with floral embossed design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po171": {
      "briefly": "Tube lined tile with blue, green and yellow glazes. Water lily design. RD No. 397438.",
      "image": "pott/po171.jpg",
      "Identification.BriefDescription": "Tube lined tile with blue, green and yellow glazes. Water lily design. RD No. 397438.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1902",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po172": {
      "briefly": "Green glazed majolica tile with peacock feather design.",
      "Identification.BriefDescription": "Green glazed majolica tile with peacock feather design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po173": {
      "briefly": "Cream coloured glazed tile with impressed urn design. RD No. 401608.",
      "image": "pott/po173.jpg",
      "Identification.BriefDescription": "Cream coloured glazed tile with impressed urn design. RD No. 401608.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1902",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po174.1-2": {
      "briefly": "Two green glazed majolica tiles with Art Nouveau design. RD No. 421939.",
      "image": "pott/po174.1-2.jpg",
      "Identification.BriefDescription": "Two green glazed majolica tiles with Art Nouveau design. RD No. 421939.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1904",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po175": {
      "briefly": "Blue and white transfer printed tile with geometric design.",
      "image": "pott/po175.jpg",
      "Identification.BriefDescription": "Blue and white transfer printed tile with geometric design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po176": {
      "briefly": "Blue and white transfer printed tile with design of hearts and stylised flowers.",
      "image": "pott/po176.jpg",
      "Identification.BriefDescription": "Blue and white transfer printed tile with design of hearts and stylised flowers.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po177": {
      "briefly": "Blue and white transfer printed tile with design of shells and flowers.",
      "image": "pott/po177.jpg",
      "Identification.BriefDescription": "Blue and white transfer printed tile with design of shells and flowers.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po178": {
      "briefly": "Green glazed majolica tile with floral design. RD No. 309351.",
      "image": "pott/po178.jpg",
      "Identification.BriefDescription": "Green glazed majolica tile with floral design. RD No. 309351.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1897",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po179": {
      "briefly": "Green, white and yellow majolica tile with poppy design.",
      "image": "pott/po179.jpg",
      "Identification.BriefDescription": "Green, white and yellow majolica tile with poppy design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po180": {
      "briefly": "Plain green majolica tile, divided into four sections. RD No. 400270.",
      "image": "pott/po180.jpg",
      "Identification.BriefDescription": "Plain green majolica tile, divided into four sections. RD No. 400270.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1902",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po181": {
      "briefly": "White, yellow and green majolica tile with incised floral panel. RD No. 628548 (1911).",
      "image": "pott/po181.jpg",
      "Identification.BriefDescription": "White, yellow and green majolica tile with incised floral panel. RD No. 628548 (1911).",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po182.1-2": {
      "briefly": "Two white, yellow, green and blue glazed majolica tiles with incised cabochon design. RD No. 628549",
      "image": "pott/po182.1-2.jpg",
      "Identification.BriefDescription": "Two white, yellow, green and blue glazed majolica tiles with incised cabochon design. RD No. 628549",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1911 (around)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po183": {
      "briefly": "White, pink, green and yellow majolica tile with rose design incised. RD No. 656233. (C.1912).",
      "image": "pott/po183.jpg",
      "Identification.BriefDescription": "White, pink, green and yellow majolica tile with rose design incised. RD No. 656233. (C.1912).",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po184.1-2": {
      "briefly": "Two brown 3&quot; x 3&quot; majolica tiles with floral motif.",
      "image": "pott/po184.1-2.jpg",
      "Identification.BriefDescription": "Two brown 3&quot; x 3&quot; majolica tiles with floral motif.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 3&quot;, width: 3&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po185.1-2": {
      "briefly": "Two brown 3&quot; x 3&quot; majolica tiles with vine leaf design.",
      "image": "pott/po185.1-2.jpg",
      "Identification.BriefDescription": "Two brown 3&quot; x 3&quot; majolica tiles with vine leaf design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 3&quot;, width: 3&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po186.1-2": {
      "briefly": "Two pink and green 3&quot; x 3&quot; majolica tiles with flower and leaf design.",
      "image": "pott/po186.1-2.jpg",
      "Identification.BriefDescription": "Two pink and green 3&quot; x 3&quot; majolica tiles with flower and leaf design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 3&quot;, width: 3&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po187.1-4": {
      "briefly": "Four yellow 3&quot; x 3&quot; majolica tiles with incised design of arabesques.",
      "image": "pott/po187.1-4.jpg",
      "Identification.BriefDescription": "Four yellow 3&quot; x 3&quot; majolica tiles with incised design of arabesques.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 3&quot;, width: 3&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po188.1-3": {
      "briefly": "Three brown and yellow 3&quot; x 3&quot; majolica tiles with flower design.",
      "image": "pott/po188.1-3.jpg",
      "Identification.BriefDescription": "Three brown and yellow 3&quot; x 3&quot; majolica tiles with flower design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 3&quot;, width: 3&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po189": {
      "briefly": "White, blue and green tube lined type tiles, three or more forming a floral panel. RD No. 418021. (1903).",
      "image": "pott/po189.jpg",
      "Identification.BriefDescription": "White, blue and green tube lined type tiles, three or more forming a floral panel. RD No. 418021. (1903).",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po190.1-4": {
      "briefly": "Four brown glazed majolica tiles, three or more forming a floral panel.",
      "image": "pott/po190.1-4.jpg",
      "Identification.BriefDescription": "Four brown glazed majolica tiles, three or more forming a floral panel.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Minton Hollins & Co.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Stoke-on-Trent&lt;/PlaceName&gt;"
    },
    "po191a": {
      "briefly": "Blue and white transfer printed floor tile.",
      "image": "pott/po191a.jpg",
      "Identification.BriefDescription": "Blue and white transfer printed floor tile.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Lea & Boulton",
      "Description.Note": "marked L. &amp; B. T.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Tunstall, Staffordshire&lt;/PlaceName&gt;"
    },
    "po191b": {
      "briefly": "Blue, white, green and yellow tube lined type tile.",
      "image": "pott/po191b.jpg",
      "Identification.BriefDescription": "Blue, white, green and yellow tube lined type tile.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Lea & Boulton",
      "Description.Note": "marked L. &amp; B. T.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Tunstall, Staffordshire&lt;/PlaceName&gt;"
    },
    "po192": {
      "briefly": "White and green glazed tube lined type tile, shamrock design. RD No. 448143",
      "image": "pott/po192.jpg",
      "Identification.BriefDescription": "White and green glazed tube lined type tile, shamrock design. RD No. 448143",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: J. H. Barret & Co.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1904",
      "Production.Place": "+&lt;PlaceName&gt;Boothen Works, Stoke-on-Trent&lt;/PlaceName&gt;"
    },
    "po193": {
      "briefly": "White, green, blue and mauve glazed tube lined type tile with water lily design. RD No. 474333",
      "image": "pott/po193.jpg",
      "Identification.BriefDescription": "White, green, blue and mauve glazed tube lined type tile with water lily design. RD No. 474333",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: J. H. Barret & Co.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1906",
      "Production.Place": "+&lt;PlaceName&gt;Boothen Works, Stoke-on-Trent&lt;/PlaceName&gt;"
    },
    "po194": {
      "briefly": "White, green and red glazed tube lined type tile, iris design. RD No. 448143",
      "image": "pott/po194.jpg",
      "Identification.BriefDescription": "White, green and red glazed tube lined type tile, iris design. RD No. 448143",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: J. H. Barret & Co.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1905",
      "Production.Place": "+&lt;PlaceName&gt;Boothen Works, Stoke-on-Trent&lt;/PlaceName&gt;"
    },
    "po195": {
      "briefly": "Green and pink tube lined type tile with nasturtium design. RD No. 444952",
      "image": "pott/po195.jpg",
      "Identification.BriefDescription": "Green and pink tube lined type tile with nasturtium design. RD No. 444952",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: J. H. Barret & Co.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1904",
      "Production.Place": "+&lt;PlaceName&gt;Boothen Works, Stoke-on-Trent&lt;/PlaceName&gt;"
    },
    "po196": {
      "briefly": "White, green and purple glazed tube lined type tile with iris design. RD No. 433276",
      "image": "pott/po196.jpg",
      "Identification.BriefDescription": "White, green and purple glazed tube lined type tile with iris design. RD No. 433276",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: J. H. Barret & Co.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1904",
      "Production.Place": "+&lt;PlaceName&gt;Boothen Works, Stoke-on-Trent&lt;/PlaceName&gt;"
    },
    "po197": {
      "briefly": "Blue and white transfer printed tile with design of bamboo,",
      "image": "pott/po197.jpg",
      "Identification.BriefDescription": "Blue and white transfer printed tile with design of bamboo,",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Henry Abraham Ollivant, Etruscan Tile Works",
      "Description.Note": "marked C.O.V.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Cliffe Vale Stoke&lt;/PlaceName&gt;"
    },
    "po198": {
      "briefly": "Blue and white transfer printed floor tile with husk design.",
      "image": "pott/po198.jpg",
      "Identification.BriefDescription": "Blue and white transfer printed floor tile with husk design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Henry Abraham Ollivant, Etruscan Tile Works",
      "Description.Note": "marked C.O.V.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Cliffe Vale Stoke&lt;/PlaceName&gt;"
    },
    "po199": {
      "briefly": "White, green and yellow majolica tile with Art Nouveau flower and leaf design",
      "image": "pott/po199.jpg",
      "Identification.BriefDescription": "White, green and yellow majolica tile with Art Nouveau flower and leaf design",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Henry Abraham Ollivant, Etruscan Tile Works",
      "Description.Note": "marked C.O.V.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Cliffe Vale Stoke&lt;/PlaceName&gt;"
    },
    "po200": {
      "briefly": "White, green, pink and yellow tube lined tile with iris Art Nouveau design RD No. 445518",
      "image": "pott/po200.jpg",
      "Identification.BriefDescription": "White, green, pink and yellow tube lined tile with iris Art Nouveau design RD No. 445518",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Henry Abraham Ollivant, Etruscan Tile Works",
      "Description.Note": "marked C.O.V.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1904",
      "Production.Place": "+&lt;PlaceName&gt;Cliffe Vale Stoke&lt;/PlaceName&gt;"
    },
    "po201": {
      "briefly": "Yellow, green and brown glazed majolica tile with daffodil design.",
      "image": "pott/po201.jpg",
      "Identification.BriefDescription": "Yellow, green and brown glazed majolica tile with daffodil design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Henry Abraham Ollivant, Etruscan Tile Works",
      "Description.Note": "marked C.O.V.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Cliffe Vale Stoke&lt;/PlaceName&gt;"
    },
    "po202.1-2": {
      "briefly": "Two white tiles transfer printed with tulip design in brown and hand painted in green and yellow.",
      "image": "pott/po202.1-2.jpg",
      "Identification.BriefDescription": "Two white tiles transfer printed with tulip design in brown and hand painted in green and yellow.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Henry Abraham Ollivant, Etruscan Tile Works",
      "Description.Note": "marked C.O.V.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Cliffe Vale Stoke&lt;/PlaceName&gt;"
    },
    "po203.1-2": {
      "briefly": "Two white tiles transfer printed in brown with pansy design and hand painted in green, brown and pink.",
      "image": "pott/po203.1-2.jpg",
      "Identification.BriefDescription": "Two white tiles transfer printed in brown with pansy design and hand painted in green, brown and pink.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "marked HRTC P(?)",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po204": {
      "briefly": "White, yellow, green and blue glazed tube lined type tile with water lily design.",
      "image": "pott/po204.jpg",
      "Identification.BriefDescription": "White, yellow, green and blue glazed tube lined type tile with water lily design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: W. & E. Corn",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Top Bridge Works, Longton&lt;/PlaceName&gt;"
    },
    "po205": {
      "briefly": "Green glazed majolica tile with urn design.",
      "image": "pott/po205.jpg",
      "Identification.BriefDescription": "Green glazed majolica tile with urn design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: W. & E. Corn",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Top Bridge Works, Longton&lt;/PlaceName&gt;"
    },
    "po206": {
      "briefly": "Green glazed majolica tile with cherry design.",
      "image": "pott/po206.jpg",
      "Identification.BriefDescription": "Green glazed majolica tile with cherry design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: W. & E. Corn",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Top Bridge Works, Longton&lt;/PlaceName&gt;"
    },
    "po207.1-2": {
      "briefly": "Two white, blue, brown and turquoise tiles with tube lined type design in Art Nouveau style.",
      "image": "pott/po207.1-2.jpg",
      "Identification.BriefDescription": "Two white, blue, brown and turquoise tiles with tube lined type design in Art Nouveau style.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: W. & E. Corn",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Top Bridge Works, Longton&lt;/PlaceName&gt;"
    },
    "po208": {
      "briefly": "Brown glazed majolica tile with Art Nouveau pomegranate design.",
      "image": "pott/po208.jpg",
      "Identification.BriefDescription": "Brown glazed majolica tile with Art Nouveau pomegranate design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: W. & E. Corn",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Top Bridge Works, Longton&lt;/PlaceName&gt;"
    },
    "po209.1-2": {
      "briefly": "Two white, blue and yellow glazed floor tiles with repeated floral pattern. RD Mark",
      "image": "pott/po209.1-2.jpg",
      "Identification.BriefDescription": "Two white, blue and yellow glazed floor tiles with repeated floral pattern. RD Mark",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Minton & Co.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1880",
      "Production.Place": "+&lt;PlaceName&gt;Stoke-on-Trent&lt;/PlaceName&gt;"
    },
    "po210.1-2": {
      "briefly": "Two buff, white, blue and brown encaustic tiles for a border.",
      "image": "pott/po210.1-2.jpg",
      "Identification.BriefDescription": "Two buff, white, blue and brown encaustic tiles for a border.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: The Campbell Tile Co.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Stoke-on-Trent&lt;/PlaceName&gt;"
    },
    "po211.1-2": {
      "briefly": "Two brown, cream and white glazed floor tiles with a geometric design.",
      "image": "pott/po211.1-2.jpg",
      "Identification.BriefDescription": "Two brown, cream and white glazed floor tiles with a geometric design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po212.1-2": {
      "briefly": "Two brown, green and yellow glazed majolica tiles with chrysanthemum design.",
      "image": "pott/po212.1-2.jpg",
      "Identification.BriefDescription": "Two brown, green and yellow glazed majolica tiles with chrysanthemum design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "marked L. T.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po213": {
      "briefly": "Brown, red and grey glazed majolica tile with design of sprays and scrolls in cruciform.",
      "image": "pott/po213.jpg",
      "Identification.BriefDescription": "Brown, red and grey glazed majolica tile with design of sprays and scrolls in cruciform.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "marked L. T.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po214": {
      "briefly": "White tile transfer printed with brown and pink study of child in meadow.",
      "image": "pott/po214.jpg",
      "Identification.BriefDescription": "White tile transfer printed with brown and pink study of child in meadow.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "marked L. T.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po215": {
      "briefly": "Green and yellow majolica tile with heavily embossed geometric design.",
      "image": "pott/po215.jpg",
      "Identification.BriefDescription": "Green and yellow majolica tile with heavily embossed geometric design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "marked L. T.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po216": {
      "briefly": "Green, brown and red tile, design of tube lined type of grapes and leaves.",
      "image": "pott/po216.jpg",
      "Identification.BriefDescription": "Green, brown and red tile, design of tube lined type of grapes and leaves.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: W Sherwin & Co.",
      "Description.Note": "marked W. S. &amp; Co.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Longport, Staffordshire&lt;/PlaceName&gt;"
    },
    "po217": {
      "briefly": "Blue glazed majolica tile with arabesque design.",
      "image": "pott/po217.jpg",
      "Identification.BriefDescription": "Blue glazed majolica tile with arabesque design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: A J Wade Ltd",
      "Description.Note": "marked Flaxman",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Flaxman Tile Works, Burslem, Staffordshire&lt;/PlaceName&gt;"
    },
    "po218": {
      "briefly": "Red and green glazed tube lined tile with flower and leaf design. Autumn 1901.",
      "image": "pott/po218.jpg",
      "Identification.BriefDescription": "Red and green glazed tube lined tile with flower and leaf design. Autumn 1901.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "marked A.M. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po219": {
      "briefly": "Brown glazed majolica tile with Art Nouveau pomegranate design. RD No. 411150",
      "image": "pott/po219.jpg",
      "Identification.BriefDescription": "Brown glazed majolica tile with Art Nouveau pomegranate design. RD No. 411150",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "marked A.M. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1903"
    },
    "po220": {
      "briefly": "Green glazed majolica tile with Art Nouveau stylized flower design.",
      "image": "pott/po220.jpg",
      "Identification.BriefDescription": "Green glazed majolica tile with Art Nouveau stylized flower design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "marked Cleveland",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po221.1": {
      "briefly": "brown glazed majolica tile depicting young girl and cow",
      "image": "pott/po221.jpg",
      "Identification.BriefDescription": "brown glazed majolica tile depicting young girl and cow",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "marked B",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po221.2": {
      "briefly": "brown glazed majolica tile depicting young boy and donkey",
      "image": "pott/po221.jpg",
      "Identification.BriefDescription": "brown glazed majolica tile depicting young boy and donkey",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "marked B",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po222": {
      "briefly": "Blue and white transfer printed tile depicting an eagle and arabesques.",
      "image": "pott/po222.jpg",
      "Identification.BriefDescription": "Blue and white transfer printed tile depicting an eagle and arabesques.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "marked UCX",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po223.1-3": {
      "briefly": "Three brown, white, yellow and blue transfer printed portrait of Queen Victoria tiles with dates 1837-1897.",
      "image": "pott/po223.1-3.jpg",
      "Identification.BriefDescription": "Three brown, white, yellow and blue transfer printed portrait of Queen Victoria tiles with dates 1837-1897.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po224.1-2": {
      "briefly": "Two green and white transfer printed floor tiles with Willow pattern design.",
      "image": "pott/po224.1-2.jpg",
      "Identification.BriefDescription": "Two green and white transfer printed floor tiles with Willow pattern design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po225": {
      "briefly": "Green, yellow and brown glazed majolica tile with thistle design.",
      "image": "pott/po225.jpg",
      "Identification.BriefDescription": "Green, yellow and brown glazed majolica tile with thistle design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po226": {
      "briefly": "White, blue and green tile with tube lined type pattern in Art Nouveau design.",
      "image": "pott/po226.jpg",
      "Identification.BriefDescription": "White, blue and green tile with tube lined type pattern in Art Nouveau design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po227": {
      "briefly": "White, blue, green and pink glazed tube lined type tile with Art Nouveau design.",
      "image": "pott/po227.jpg",
      "Identification.BriefDescription": "White, blue, green and pink glazed tube lined type tile with Art Nouveau design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po228": {
      "briefly": "Blue and white transfer printed tile with arabesque design. RD No. 16307",
      "image": "pott/po228.jpg",
      "Identification.BriefDescription": "Blue and white transfer printed tile with arabesque design. RD No. 16307",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1884"
    },
    "po229": {
      "briefly": "Yellow glazed majolica tile with stylized flower design. RD No. 475285",
      "image": "pott/po229.jpg",
      "Identification.BriefDescription": "Yellow glazed majolica tile with stylized flower design. RD No. 475285",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1906"
    },
    "po230": {
      "briefly": "Blue and white transfer printed floor tile with design of flowers and hearts.",
      "image": "pott/po230.jpg",
      "Identification.BriefDescription": "Blue and white transfer printed floor tile with design of flowers and hearts.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po231.1-2": {
      "briefly": "Brown, green, yellow and pink majolica tile with cherry design, hand painted with brown stems.",
      "image": "pott/po231.1-2.jpg",
      "Identification.BriefDescription": "Brown, green, yellow and pink majolica tile with cherry design, hand painted with brown stems.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po232": {
      "briefly": "White, green, pink and brown tube lined tile with Art Nouveau tulip design. RD No. 517589",
      "image": "pott/po232.jpg",
      "Identification.BriefDescription": "White, green, pink and brown tube lined tile with Art Nouveau tulip design. RD No. 517589",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1907"
    },
    "po233": {
      "briefly": "Green and yellow glazed tube lined type of tile with flower and leaf design.",
      "image": "pott/po233.jpg",
      "Identification.BriefDescription": "Green and yellow glazed tube lined type of tile with flower and leaf design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po234": {
      "briefly": "Pale green glazed majolica tile with Art Nouveau flower design.",
      "image": "pott/po234.jpg",
      "Identification.BriefDescription": "Pale green glazed majolica tile with Art Nouveau flower design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po235": {
      "briefly": "Brown, green and yellow majolica tile with apple blossom design.",
      "image": "pott/po235.jpg",
      "Identification.BriefDescription": "Brown, green and yellow majolica tile with apple blossom design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po236": {
      "briefly": "Brown, green and yellow majolica tile, design with four leaves.",
      "image": "pott/po236.jpg",
      "Identification.BriefDescription": "Brown, green and yellow majolica tile, design with four leaves.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po237": {
      "briefly": "White, green and blue majolica tile, design with flower and leaves.",
      "image": "pott/po237.jpg",
      "Identification.BriefDescription": "White, green and blue majolica tile, design with flower and leaves.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po238": {
      "briefly": "Green glazed majolica tile with Art Nouveau tulip design.",
      "image": "pott/po238.jpg",
      "Identification.BriefDescription": "Green glazed majolica tile with Art Nouveau tulip design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po238a": {
      "briefly": "Blue and green glazed tube lined type tile with Art Nouveau flower design.",
      "image": "pott/po238a.jpg",
      "Identification.BriefDescription": "Blue and green glazed tube lined type tile with Art Nouveau flower design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po239": {
      "briefly": "Green, yellow and brown majolica tile with pansy design.",
      "image": "pott/po239.jpg",
      "Identification.BriefDescription": "Green, yellow and brown majolica tile with pansy design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po240": {
      "briefly": "White, green and brown tube lined type tile with chrysanthemum design.",
      "image": "pott/po240.jpg",
      "Identification.BriefDescription": "White, green and brown tube lined type tile with chrysanthemum design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po241": {
      "briefly": "Blue majolica tile with Art Nouveau design.",
      "image": "pott/po241.jpg",
      "Identification.BriefDescription": "Blue majolica tile with Art Nouveau design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po242": {
      "briefly": "Pink, white, green and blue majolica tile with rosebud design.",
      "image": "pott/po242.jpg",
      "Identification.BriefDescription": "Pink, white, green and blue majolica tile with rosebud design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po243": {
      "briefly": "Red, yellow, blue and green tube lined type tile with Art Nouveau tulip design",
      "image": "pott/po243.jpg",
      "Identification.BriefDescription": "Red, yellow, blue and green tube lined type tile with Art Nouveau tulip design",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po244": {
      "briefly": "Brown, yellow, cream and grey majolica type tile with sunflower and leaf design.",
      "image": "pott/po244.jpg",
      "Identification.BriefDescription": "Brown, yellow, cream and grey majolica type tile with sunflower and leaf design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po245.1-2": {
      "briefly": "Pink, yellow and green majolica tiles with orchid design.",
      "image": "pott/po245.1-2.jpg",
      "Identification.BriefDescription": "Pink, yellow and green majolica tiles with orchid design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po246.1-2": {
      "briefly": "Two green and white transfer printed tiles with stylized flower design, hand painted with blue, brown and red.",
      "image": "pott/po246.1-2.jpg",
      "Identification.BriefDescription": "Two green and white transfer printed tiles with stylized flower design, hand painted with blue, brown and red.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po247": {
      "briefly": "Green majolica tile with star design.",
      "image": "pott/po247.jpg",
      "Identification.BriefDescription": "Green majolica tile with star design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po248": {
      "briefly": "Pink and brown majolica type tile with thistle design",
      "image": "pott/po248.jpg",
      "Identification.BriefDescription": "Pink and brown majolica type tile with thistle design",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po249": {
      "briefly": "Green majolica tile with chrysanthemum design.",
      "image": "pott/po249.jpg",
      "Identification.BriefDescription": "Green majolica tile with chrysanthemum design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po250": {
      "briefly": "Green, brown and white tube lined type tile with Art Nouveau design.",
      "image": "pott/po250.jpg",
      "Identification.BriefDescription": "Green, brown and white tube lined type tile with Art Nouveau design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po251": {
      "briefly": "Blue and white transfer printed tile with formal flower and leaf pattern.",
      "image": "pott/po251.jpg",
      "Identification.BriefDescription": "Blue and white transfer printed tile with formal flower and leaf pattern.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po252": {
      "briefly": "Brown and mottled glaze 12&quot; x 6&quot; tile with rectangular geometric design.",
      "image": "pott/po252.jpg",
      "Identification.BriefDescription": "Brown and mottled glaze 12&quot; x 6&quot; tile with rectangular geometric design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 12&quot;)"
    },
    "po253.1-2": {
      "briefly": "Two green and white transfer printed tiles with poppy design.",
      "image": "pott/po253.1-2.jpg",
      "Identification.BriefDescription": "Two green and white transfer printed tiles with poppy design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po254": {
      "briefly": "White, green and red tube lined tile with poppy design. RD No. 374311",
      "image": "pott/po254.jpg",
      "Identification.BriefDescription": "White, green and red tube lined tile with poppy design. RD No. 374311",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1901"
    },
    "po256": {
      "briefly": "Brown and white transfer printed tile with sprigged flower and leaf design.",
      "image": "pott/po256.jpg",
      "Identification.BriefDescription": "Brown and white transfer printed tile with sprigged flower and leaf design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po257.1": {
      "briefly": "Majolica tile with flower and C scroll design  in cream, brown and blue glazes.",
      "image": "pott/po257.jpg",
      "Identification.BriefDescription": "Majolica tile with flower and C scroll design  in cream, brown and blue glazes.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po257.2": {
      "briefly": "Majolica tile with flower and C scroll design in green, yellow and pink glazes.",
      "image": "pott/po257.jpg",
      "Identification.BriefDescription": "Majolica tile with flower and C scroll design in green, yellow and pink glazes.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po258": {
      "briefly": "Green and pink majolica tile with flower and leaf design.",
      "image": "pott/po258.jpg",
      "Identification.BriefDescription": "Green and pink majolica tile with flower and leaf design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po259": {
      "briefly": "tile - hand painted underglaze with apple blossom design in browns, yellows and greens.",
      "image": "pott/po259.jpg",
      "Identification.BriefDescription": "tile - hand painted underglaze with apple blossom design in browns, yellows and greens.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po260": {
      "briefly": "Brown, yellow and pink tube lined type tile with peach spray design.",
      "image": "pott/po260.jpg",
      "Identification.BriefDescription": "Brown, yellow and pink tube lined type tile with peach spray design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po261": {
      "briefly": "White, yellow, pink and red majolica tile with poppy design.",
      "image": "pott/po261.jpg",
      "Identification.BriefDescription": "White, yellow, pink and red majolica tile with poppy design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po262": {
      "briefly": "Brown, green, white and red majolica tile with Arum Lily design.",
      "image": "pott/po262.jpg",
      "Identification.BriefDescription": "Brown, green, white and red majolica tile with Arum Lily design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po263": {
      "briefly": "Brown, majolica tile with Madonna lily design.",
      "image": "pott/po263.jpg",
      "Identification.BriefDescription": "Brown, majolica tile with Madonna lily design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po264": {
      "briefly": "Green, yellow and red majolica tile with oak leaf design.",
      "image": "pott/po264.jpg",
      "Identification.BriefDescription": "Green, yellow and red majolica tile with oak leaf design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po265": {
      "briefly": "White, green, brown, yellow and red majolica tile with stylized design of straps and acanthus leaves. RD. No. 145221",
      "image": "pott/po265.jpg",
      "Identification.BriefDescription": "White, green, brown, yellow and red majolica tile with stylized design of straps and acanthus leaves. RD. No. 145221",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1890"
    },
    "po266": {
      "briefly": "Green, brown and yellow majolica tile with violet design within geometric bands.",
      "image": "pott/po266.jpg",
      "Identification.BriefDescription": "Green, brown and yellow majolica tile with violet design within geometric bands.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po267.1-2": {
      "briefly": "Two brown, grey, yellow and red majolica tiles with Chrysanthemum design.",
      "image": "pott/po267.1-2.jpg",
      "Identification.BriefDescription": "Two brown, grey, yellow and red majolica tiles with Chrysanthemum design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po268": {
      "briefly": "Blue and white transfer printed floor tile with formal design of leaves and scrolls.",
      "image": "pott/po268.jpg",
      "Identification.BriefDescription": "Blue and white transfer printed floor tile with formal design of leaves and scrolls.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po269": {
      "briefly": "Blue and white transfer printed tile with formal design of flowers and scrolls.",
      "image": "pott/po269.jpg",
      "Identification.BriefDescription": "Blue and white transfer printed tile with formal design of flowers and scrolls.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po270.1-2": {
      "briefly": "Two polychrome transfer printed overglaze tiles with design of spray of parrot tulips.",
      "image": "pott/po270.1-2.jpg",
      "Identification.BriefDescription": "Two polychrome transfer printed overglaze tiles with design of spray of parrot tulips.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po271": {
      "briefly": "Pink tube lined type tile with stylized flower design.",
      "image": "pott/po271.jpg",
      "Identification.BriefDescription": "Pink tube lined type tile with stylized flower design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po272": {
      "briefly": "Blue, green and orange tube lined type tile with Art Nouveau design of leaf and two flower heads.",
      "image": "pott/po272.jpg",
      "Identification.BriefDescription": "Blue, green and orange tube lined type tile with Art Nouveau design of leaf and two flower heads.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po273.1-2": {
      "briefly": "Two red, green and yellow tube lined type tiles with Art Nouveau tulip design.",
      "image": "pott/po273.1-2.jpg",
      "Identification.BriefDescription": "Two red, green and yellow tube lined type tiles with Art Nouveau tulip design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po274": {
      "briefly": "Green and brown tube lined type tile with grapes and leaves design.",
      "image": "pott/po274.jpg",
      "Identification.BriefDescription": "Green and brown tube lined type tile with grapes and leaves design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po275.1-3": {
      "briefly": "Three green and white tube lined type tiles, two or more forming a floral panel.",
      "image": "pott/po275.1-3.jpg",
      "Identification.BriefDescription": "Three green and white tube lined type tiles, two or more forming a floral panel.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po276": {
      "briefly": "tile - brown transfer printed design of birds in prunus blossom within a geometric border. Hand coloured in yellow, pink, blue and green.",
      "image": "pott/po276.jpg",
      "Identification.BriefDescription": "tile - brown transfer printed design of birds in prunus blossom within a geometric border. Hand coloured in yellow, pink, blue and green.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po277": {
      "briefly": "tile - brown transfer printed design of blossom and sunflowers. Hand coloured in pink, yellow, brown and blue.",
      "image": "pott/po277.jpg",
      "Identification.BriefDescription": "tile - brown transfer printed design of blossom and sunflowers. Hand coloured in pink, yellow, brown and blue.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po278.1-2": {
      "briefly": "tile - brown transfer printed design of magnolia spray within a border of scrolls. Hand coloured in yellow, brown, green and pink.",
      "image": "pott/po278.1-2.jpg",
      "Identification.BriefDescription": "tile - brown transfer printed design of magnolia spray within a border of scrolls. Hand coloured in yellow, brown, green and pink.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po279.1-2": {
      "briefly": "tile - brown transfer printed magnolia spray within geometric border. Hand coloured in brown and yellow.",
      "image": "pott/po279.1-2.jpg",
      "Identification.BriefDescription": "tile - brown transfer printed magnolia spray within geometric border. Hand coloured in brown and yellow.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po280": {
      "briefly": "tile - brown transfer printed design of Arum lilies and leaves within Greek key border. Hand coloured in green and brown.",
      "image": "pott/po280.jpg",
      "Identification.BriefDescription": "tile - brown transfer printed design of Arum lilies and leaves within Greek key border. Hand coloured in green and brown.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po281.1-10": {
      "briefly": "Set of hand painted overglaze tiles with floral designs in pink and green forming a panel.",
      "image": "pott/po281.1-10.jpg",
      "Identification.BriefDescription": "Set of hand painted overglaze tiles with floral designs in pink and green forming a panel.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po282.1-2": {
      "briefly": "Two brown transfer printed tiles forming a panel of wild roses. Hand coloured in browns and green.",
      "image": "pott/po282.1-2.jpg",
      "Identification.BriefDescription": "Two brown transfer printed tiles forming a panel of wild roses. Hand coloured in browns and green.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po283.1-4": {
      "briefly": "Four brown transfer printed tiles, two forming a panel depicting an urn with scrolls and fruit and flowers. Hand coloured in turquoise, green, yellow, pink and brown.",
      "image": "pott/po283.1-4.jpg",
      "Identification.BriefDescription": "Four brown transfer printed tiles, two forming a panel depicting an urn with scrolls and fruit and flowers. Hand coloured in turquoise, green, yellow, pink and brown.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po284.1-2": {
      "briefly": "Two brown transfer printed tiles forming  a panel depicting chimeras, scrolls and daffodils within an architectural canopy. Hand coloured in brown, green, yellow and blue.",
      "image": "pott/po284.1-2.jpg",
      "Identification.BriefDescription": "Two brown transfer printed tiles forming  a panel depicting chimeras, scrolls and daffodils within an architectural canopy. Hand coloured in brown, green, yellow and blue.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po285": {
      "briefly": "Brown, pink and green majolica tile with lilac spray design. Hand coloured in brown.",
      "image": "pott/po285.jpg",
      "Identification.BriefDescription": "Brown, pink and green majolica tile with lilac spray design. Hand coloured in brown.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: T. A. Simpson & Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Furlong Tile Works, Burslem&lt;/PlaceName&gt;"
    },
    "po286": {
      "briefly": "Brown, yellow and pink majolica tile with pear and leaf design. RD No. 281642",
      "image": "pott/po286.jpg",
      "Identification.BriefDescription": "Brown, yellow and pink majolica tile with pear and leaf design. RD No. 281642",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: T. A. Simpson & Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1896",
      "Production.Place": "+&lt;PlaceName&gt;Furlong Tile Works, Burslem&lt;/PlaceName&gt;"
    },
    "po287": {
      "briefly": "Green tube lined type tile with Art Nouveau design of flowers and leaves and stems.",
      "image": "pott/po287.jpg",
      "Identification.BriefDescription": "Green tube lined type tile with Art Nouveau design of flowers and leaves and stems.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: H. & R. Johnson Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Crystal Tile Work, Cobridge&lt;/PlaceName&gt;"
    },
    "po288": {
      "briefly": "Blue majolica tile with Art Nouveau design of leaf and two flowers. RD No. 472078",
      "image": "pott/po288.jpg",
      "Identification.BriefDescription": "Blue majolica tile with Art Nouveau design of leaf and two flowers. RD No. 472078",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: H. & R. Johnson Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1907",
      "Production.Place": "+&lt;PlaceName&gt;Crystal Tile Work, Cobridge&lt;/PlaceName&gt;"
    },
    "po289": {
      "briefly": "Yellow majolica tile with Art Nouveau flower and leaves. RD. No. 425610",
      "image": "pott/po289.jpg",
      "Identification.BriefDescription": "Yellow majolica tile with Art Nouveau flower and leaves. RD. No. 425610",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: H. & R. Johnson Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1904",
      "Production.Place": "+&lt;PlaceName&gt;Crystal Tile Work, Cobridge&lt;/PlaceName&gt;"
    },
    "po290.1-8": {
      "briefly": "Set of transfer printed tiles, four forming a set. Some printed in blue and some in white. Design of scrolls and flowers.",
      "image": "pott/po290.1-8.jpg",
      "Identification.BriefDescription": "Set of transfer printed tiles, four forming a set. Some printed in blue and some in white. Design of scrolls and flowers.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po291": {
      "briefly": "3&quot; x 3&quot; brown majolica tile with design of leaves and buds.",
      "image": "pott/po291.jpg",
      "Identification.BriefDescription": "3&quot; x 3&quot; brown majolica tile with design of leaves and buds.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Production.Organisation": "manufacturer: Pilkington Tile & Pottery Co. Ltd.",
      "Description.Measurement": " (height: 3&quot;, width: 3&quot;)",
      "Production.Place": "+&lt;PlaceName&gt;Clifton Junction, Manchester&lt;/PlaceName&gt;"
    },
    "po292": {
      "briefly": "3&quot; x 3&quot; brown majolica tile with design of five daisies.",
      "image": "pott/po292.jpg",
      "Identification.BriefDescription": "3&quot; x 3&quot; brown majolica tile with design of five daisies.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 3&quot;, width: 3&quot;)"
    },
    "po293": {
      "briefly": "3&quot; x 3&quot; brown majolica tile with single flower head design.",
      "image": "pott/po293.jpg",
      "Identification.BriefDescription": "3&quot; x 3&quot; brown majolica tile with single flower head design.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 3&quot;, width: 3&quot;)"
    },
    "po294.1-2": {
      "briefly": "Two 6&quot; x 3&quot; green majolica tiles with rectangular design. (T. A. Simpson &amp; Co.)",
      "image": "pott/po294.1-2.jpg",
      "Identification.BriefDescription": "Two 6&quot; x 3&quot; green majolica tiles with rectangular design. (T. A. Simpson &amp; Co.)",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 3&quot;, width: 6&quot;)"
    },
    "po295.1-4": {
      "briefly": "Four tube lined type tiles in green, yellow and brown forming border of swags and roses.",
      "image": "pott/po295.1-4.jpg",
      "Identification.BriefDescription": "Four tube lined type tiles in green, yellow and brown forming border of swags and roses.",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po296.1-4": {
      "briefly": "Four majolica tiles with Art Nouveau pomegranate design. Two in green glaze, two in yellow glaze.",
      "image": "pott/po296.1-4.jpg",
      "Identification.BriefDescription": "Four majolica tiles with Art Nouveau pomegranate design. Two in green glaze, two in yellow glaze.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po297.1-2": {
      "briefly": "Two plain brown glazed tiles 6&quot; x 2&quot; (Pilkingtons).",
      "image": "pott/po297.1-2.jpg",
      "Identification.BriefDescription": "Two plain brown glazed tiles 6&quot; x 2&quot; (Pilkingtons).",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Millington, G, Mr, Preston",
      "Acquisition.Date": "1957",
      "Description.Note": "not marked",
      "Description.Measurement": " (height: 2&quot;, width: 6&quot;)"
    },
    "po435": {
      "briefly": "Six Tiles: Transfer printed underglaze with floral and geometric design",
      "image": "pott/po435.jpg",
      "Identification.BriefDescription": "Six Tiles: Transfer printed underglaze with floral and geometric design",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Whittaker, Mrs (Edenfield)",
      "Acquisition.Date": "1976",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)",
      "Production.Date": "1887"
    },
    "po436": {
      "briefly": "Five Tiles: Encaustic type with diaper pattern in cream, yellow and black.",
      "image": "pott/po436.jpg",
      "Identification.BriefDescription": "Five Tiles: Encaustic type with diaper pattern in cream, yellow and black.",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Whittaker, Mrs (Edenfield)",
      "Acquisition.Date": "1976",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    },
    "po437": {
      "briefly": "Three Tiles: Encaustic type with geometric design in cream, yellow, terra cotta and black",
      "image": "pott/po437.jpg",
      "Identification.BriefDescription": "Three Tiles: Encaustic type with geometric design in cream, yellow, terra cotta and black",
      "Identification.ObjectName.simple name": "tile",
      "Acquisition.Method": "gift",
      "Acquisition.Person": "donor: Whittaker, Mrs (Edenfield)",
      "Acquisition.Date": "1976",
      "Description.Measurement": " (height: 6&quot;, width: 6&quot;)"
    }
  },
  "$props": [
    "briefly",
    "image",
    "Identification.BriefDescription",
    "Identification.ObjectName.simple name",
    "Association.Date",
    "Association.Period",
    "Acquisition.Method",
    "Acquisition.Person",
    "Acquisition.Date",
    "Acquisition.Note",
    "Production.Organisation",
    "Acquisition.Organisation",
    "Disposal.Note",
    "$Association.Period",
    "$Acquisition.Person",
    "Identification.ObjectName.other name",
    "Identification.Title",
    "Production.Person",
    "ConditionCheck.Condition",
    "ConditionCheck.Note",
    "ConditionCheck.Date",
    "Content.SummaryText",
    "Description.Note",
    "Description.Condition",
    "Identification.Note",
    "Disposal.Method",
    "Disposal.Organisation",
    "Disposal.Date",
    "Acquisition.ReferenceNumber",
    "Description.Material",
    "Description.Measurement",
    "Association.Note",
    "Conservation.Note",
    "Disposal.ReferenceNumber",
    "Reproduction.Note",
    "Association.Type",
    "Association.Person",
    "Description.Inscription",
    "Production.Date",
    "Production.Period",
    "Rights.Note",
    "$Description.Measurement",
    "Production.Note",
    "Identification.Title.other title",
    "Acquisition.CreditLine",
    "$Production.Person",
    "Production.Place",
    "Description.Completeness",
    "$Description.Note",
    "$Reproduction.Note",
    "$Content.SummaryText",
    "$tags"
  ],
  "$groups": [
    "$Identification",
    "$Association",
    "$Acquisition",
    "$Production",
    "$Disposal",
    "$Reproduction",
    "$ConditionCheck",
    "$Content",
    "$Description",
    "$Conservation",
    "$Rights"
  ],
  "$Identification": [
    "Identification.BriefDescription",
    "Identification.ObjectName.simple name",
    "Identification.ObjectName.other name",
    "Identification.Title",
    "Identification.Note",
    "Identification.Title.other title"
  ],
  "$Association": [
    "Association.Date",
    "Association.Period",
    "$Association.Period",
    "Association.Note",
    "Association.Type",
    "Association.Person"
  ],
  "$Acquisition": [
    "Acquisition.Method",
    "Acquisition.Person",
    "Acquisition.Date",
    "Acquisition.Note",
    "Acquisition.Organisation",
    "$Acquisition.Person",
    "Acquisition.ReferenceNumber",
    "Acquisition.CreditLine"
  ],
  "$Production": [
    "Production.Organisation",
    "Production.Person",
    "Production.Date",
    "Production.Period",
    "Production.Note",
    "$Production.Person",
    "Production.Place"
  ],
  "$Disposal": [
    "Disposal.Note",
    "Disposal.Method",
    "Disposal.Date",
    "Disposal.ReferenceNumber",
    "Disposal.Organisation"
  ],
  "$Reproduction": [
    "Reproduction.Note",
    "$Reproduction.Note"
  ],
  "$ConditionCheck": [
    "ConditionCheck.Condition",
    "ConditionCheck.Note",
    "ConditionCheck.Date"
  ],
  "$Content": [
    "Content.SummaryText",
    "$Content.SummaryText"
  ],
  "$Description": [
    "Description.Note",
    "Description.Condition",
    "Description.Material",
    "Description.Measurement",
    "Description.Inscription",
    "$Description.Measurement",
    "Description.Completeness",
    "$Description.Note"
  ],
  "$Conservation": [
    "Conservation.Note"
  ],
  "$Rights": [
    "Rights.Note"
  ]
};
